### ISSUE TITLE
Segmentation Fault in Meshes Overlapping

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6921] opened 2018-10-22 15:00 UTC
Kevin,
Take a look at this case when you have time.

```
&HEAD CHID='test'/
&TIME T_END=10.0/

&MESH ID='MESH01-0', IJK=67,52,26, XB=-5.6,1.1,-6.2,-1.0,2.6,5.2/
&MESH ID='MESH05-1', IJK=64,34,26, XB=2.0,8.4,2.1,5.5,2.6,5.2/
&MESH ID='MESH04-1', IJK=32,17,43, XB=2.0,8.4,2.1,5.5,5.2,13.8/
&MESH ID='MESH06-2', IJK=32,19,13, XB=2.0,8.4,2.1,5.9,0.0,2.6/
&MESH ID='MESH02-2', IJK=67,22,26, XB=1.1,7.8,-5.2,-3.0,2.6,5.2/
&MESH ID='MESH03-2', IJK=22,53,26, XB=5.6,7.8,-3.0,2.3,2.6,5.2/
```
Using FDS6.7 it throws a segmentation fault 
```
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds.exe            00007FF6397C3BA6  Unknown               Unknown  Unknown
fds.exe            00007FF640EACCB7  FDS_ip_MESH_EXCHA        2308  main.f90
fds.exe            00007FF640E39CB1  MAIN__                    210  main.f90
fds.exe            00007FF640E28632  Unknown               Unknown  Unknown
fds.exe            00007FF641737A80  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFADAA53034  Unknown               Unknown  Unknown
ntdll.dll          00007FFADB161461  Unknown               Unknown  Unknown
```
The problem lies between Mesh03-02 and Mesh 05-01. When I fix the overlapping, 
```
&MESH ID='MESH01-0', IJK=67,52,26, XB=-5.6,1.1,-6.2,-1.0,2.6,5.2/
&MESH ID='MESH05-1', IJK=64,34,26, XB=2.0,8.4,2.1,5.5,2.6,5.2/
&MESH ID='MESH04-1', IJK=32,17,43, XB=2.0,8.4,2.1,5.5,5.2,13.8/
&MESH ID='MESH06-2', IJK=32,19,13, XB=2.0,8.4,2.1,5.9,0.0,2.6/
&MESH ID='MESH02-2', IJK=67,22,26, XB=1.1,7.8,-5.2,-3.0,2.6,5.2/
&MESH ID='MESH03-2', IJK=22,51,26, XB=5.6,7.8,-3.0,2.1,2.6,5.2/
```
I'm able to getting running, but why it's not sending an error message of meshes being overlapped instead?
With overlapping

![image](https://user-images.githubusercontent.com/20113030/47299899-31060180-d613-11e8-8480-579c54b84c0d.png)

Without overlapping. 
![image](https://user-images.githubusercontent.com/20113030/47299554-62ca9880-d612-11e8-9d15-8454106c7aaa.png)

Thanks !

**Comment by rmcdermo** [comment] 2018-10-22 15:23
Overlapping is permitted.  That is why you don't get a message.  We are looking into it.

**Comment by rmcdermo** [comment] 2018-10-22 15:39
Kevin,
I'm seeing the seg fault with latest code.  But the problem is with these two meshes
```
&MESH ID='MESH04-1', IJK=32,17,43, XB=2.0,8.4,2.1,5.5,5.2,13.8/
&MESH ID='MESH06-2', IJK=32,19,13, XB=2.0,8.4,2.1,5.9,0.0,2.6/
```
Comment those out and it runs.  Add either back and it fails.

**Comment by mcgratta** [comment] 2018-10-22 17:40
I don't get the seg fault, I just get a hang in one of the initial MPI calls. Move the last mesh to the front of the list and tell me if it works. If it does, I'll explain what I think is going on.

**Comment by rmcdermo** [comment] 2018-10-22 17:46
Yes moving last mesh to front works.  Seg fault happens in _dv or _db serial versions.

```
[rmcdermo@burn Issue_6921]$ fds_dv test.fds
 Reading input file ...
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fds_impi_intel_li  000000000851E4FD  Unknown               Unknown  Unknown
libpthread-2.12.s  000000398E20F7E0  Unknown               Unknown  Unknown
fds_impi_intel_li  00000000009F3581  fds_IP_mesh_excha        2381  main.f90
fds_impi_intel_li  00000000009D3917  MAIN__                    221  main.f90
fds_impi_intel_li  000000000054909E  Unknown               Unknown  Unknown
libc-2.12.so       000000398DA1ED20  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  0000000000548F29  Unknown               Unknown  Unknown
```

**Comment by mcgratta** [comment] 2018-10-22 18:18
So what is happening is that there is an ambiguous mesh connection between Mesh 6 and the meshes above and below. A mesh exchanges with the first mesh it finds, and usually the exchange is mutual. In this case it is not. There might be some logic to address this. I have to think about it.

**Comment by rmcdermo** [comment] 2018-10-22 19:03
There is a fast algorithm for testing whether an oriented bounding box (like our MESH) overlaps with another.  This is in Glenn's computational geometry book (I think Marcos has it in his office).  Given the generality you are trying to keep with overlapping, we should run through this algorithm once either first or at the end to make sure it is consistent with the final MESH connectivity map.

**Comment by saschagottfried** [comment] 2018-10-23 09:13
Since mesh overlapping is both allowed and documented in FDS User Guide several verification cases should demonstrate correctness of the logic that creates what the developers seem to call the "final MESH connectivity map". 

If several input files, demonstrating valid or invalid mesh overlapping examples, are part of the FDS verification process, your continuous integration process will tell you about bugs or [regressions](https://en.wikipedia.org/wiki/Regression_testing).

I am not aware of the current test coverage for mesh overlapping, searching for `overlap` in verification folder has a single result (dancing_eddies_tight_overlap.fds).

**Comment by rmcdermo** [comment] 2018-10-23 09:39
@saschagottfried True, we should add the test from this issue in CI.  But the verification case you are looking for is [random_meshes](https://github.com/firemodels/fds/blob/master/Verification/Adaptive_Mesh_Refinement/random_meshes.fds)

**Comment by sbenkorichi** [comment] 2018-10-23 09:44
That was misunderstanding from my end. Yes user guide explains it. I just had this impression of no overlapping allowed through pyrosim, as it's considered as a good practice. I'm sure Bryan can give more info on this.  And as it's said in the UG, there is a litte advantage to overlapping meshes.

**Comment by mcgratta** [comment] 2018-12-14 14:21
I'm going to close this issue. Any attempt to detect this kind of rare occurrence would probably do more harm than good. If more cases arise, I'll re-address.

**Closed as completed by mcgratta** 2018-12-14 14:21 UTC
