### ISSUE TITLE
Pyrolysis Simulation Time

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#6848] opened 2018-09-26 17:10 UTC
This input file results in a significant difference in the computational time between FDS version 6.2 and FDS version 6.7. From the output files it seems the majority of the difference is in the wall routine. The total run time on my machine in 6.2 is 33 seconds versus 410 seconds in 6.7. The input file is simulating ignition through a cone test.

[pyroSimTime.zip](https://github.com/firemodels/fds/files/2420802/pyroSimTime.zip)

**Comment by mcgratta** [comment] 2018-09-26 20:30
This should be fixed. Recompile the latest source code and let me know if the problem is fixed.

**Comment by johodges** [comment] 2018-10-02 12:41
Thanks for looking into this issue. I compiled the latest version and re-ran the comparison. The wall time is lower but the DIVG, MASS, and VELO times are higher than before. Please see the attached output/cpu files.
[comparisonzip.zip](https://github.com/firemodels/fds/files/2437829/comparisonzip.zip)

**Comment by mcgratta** [comment] 2018-10-02 22:07
Your new times are much higher. Are you sure you compiled the release, as opposed to debug, version. When I run the case, it is slightly slower than the 6.2 times, but probably just because of a difference in processor speed.

**Comment by johodges** [comment] 2018-10-03 12:19
Thanks for pointing that out, the increase in other times was a result of compiling the debug version. When I run the comparison with the release version the times are comparable. Thanks for the support.

**Comment by mcgratta** [comment] 2018-10-03 20:47
No problem. You caught a nasty bug.

**Closed as completed by mcgratta** 2018-10-03 20:47 UTC
