### ISSUE TITLE
Large differences in pressure when using one or two zones for a two-room model

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#3713] opened 2016-03-23 19:32 UTC
I am testing a model with an open door between two rooms. There is an air supply (0.228 m3/s) in one room and the other room has an open boundary (see attached image).

When I use two zones (one for each room), the pressure in the room with the supply rises to about 2E4 Pa. If I use only one zone, the pressure in the supply room stays approximately zero. 

I had expected that, since the two zones are open to communicate with each other, the pressures would be about the same in the two models.

![model](https://cloud.githubusercontent.com/assets/13338306/13998192/ef7b8a06-f103-11e5-8208-dd81af527e41.png)

![inner pressure with two zones](https://cloud.githubusercontent.com/assets/13338306/13998196/f4f027c6-f103-11e5-8b33-feb7a1ee6551.png)

![inner pressure with one zone](https://cloud.githubusercontent.com/assets/13338306/13998200/f8bf4972-f103-11e5-94c1-e511e850c336.png)

![pressure_contour_two_zones](https://cloud.githubusercontent.com/assets/13338306/13998209/00263478-f104-11e5-87f3-9fa53b7f8409.png)

![pressure_contour_one_zone](https://cloud.githubusercontent.com/assets/13338306/13998211/03060d4e-f104-11e5-9b36-a1fdc23c7ba1.png)

![pressure_two_zones fds](https://cloud.githubusercontent.com/assets/13338306/13998216/08b692c2-f104-11e5-86de-5798355749eb.png)

![pressure_one_zone fds](https://cloud.githubusercontent.com/assets/13338306/13998223/0c578b48-f104-11e5-8e7d-1dc4440069bf.png)

**Comment by mcgratta** [comment] 2016-03-23 19:54
I cannot view the input files. Paste them into a window using the syntax

```
&HEAD CHID=... /
```

That is, create a line with `, then paste the file, then another line`

**Comment by mcgratta** [comment] 2016-03-23 19:55
Sorry, use three back quotes above and below the pasted input file.

**Comment by drjfloyd** [comment] 2016-03-23 19:56
Kevin,

The files are uploaded with png appended to the extension (this was the work around before github let people upload text files).  Right click and save-as and change the extension to .fds

**Comment by mcgratta** [comment] 2016-03-23 19:59
OK, got it.

**Comment by mcgratta** [comment] 2016-03-23 20:30
I think the problem is that when a user specifies a zone via an `XB`, FDS expands that volume to encompass the largest sealed compartment containing that `XB`. In your case, Zone 1 expanded into Zone 2, and I don't think there's logic to stop this. I typically create sealed compartments and declare them to be zones. I break them using timers, as in the following example:

```
&HEAD CHID='two_zones' /
&TIME T_END=30.0 /
&MESH IJK=13,28,12, XB=0.0,3.25,0.0,7.0,0.0,3.0 /
&ZONE ID='Zone01', XB=0.5,2.25,0.0,2.0,0.0,3.0 /
&ZONE ID='Zone02', XB=0.5,2.25,5.0,7.0,0.0,3.0 /
&SURF ID='Supply', COLOR='GREEN', VOLUME_FLOW=-0.2 /
&VENT XB=0.0,0.0,0.5,0.75,2.25,2.5, SURF_ID='Supply' /
&OBST XB=0.0,3.25,1.75,2.0,0.0,3.0 /
&OBST XB=0.0,3.25,6.75,7.0,0.0,3.0, DEVC_ID='clock2' /
&HOLE XB=1.75,2.75,1.5,2.25,-0.025,2.25, DEVC_ID='clock' /
&DEVC ID='clock', QUANTITY='TIME', XYZ=0,0,0, SETPOINT=10., INITIAL_STATE=.FALSE. /
&DEVC ID='clock2', QUANTITY='TIME', XYZ=0,0,0, SETPOINT=20., INITIAL_STATE=.TRUE. /
&VENT MB='YMAX', SURF_ID='OPEN' /
&SLCF PBZ=1.5, QUANTITY='PRESSURE ZONE', CELL_CENTERED=.TRUE. /
&SLCF PBZ=1.5, QUANTITY='PRESSURE', CELL_CENTERED=.TRUE. /
&SLCF PBZ=1.5, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&TAIL /
```

Here, Zone 1 breaks after 10 s and equilibriates with Zone 2. After 20 s, the combined Zone 1 and 2 break to the outside, and the pressure drops to ambient.

I'll see if I can add some logic that would have stopped the multiple zone definition.

**Comment by dvswenson** [comment] 2016-03-23 20:48
Thanks.

**Comment by mcgratta** [comment] 2016-03-23 21:14
Jason -- can you think of any reason why we would not want to stop a calculation when the same grid cell is assigned to two different pressure zones? Any HVAC ramifications?

**Comment by mcgratta** [comment] 2016-03-24 14:28
I found two verification cases that caused a problem -- `HVAC/leak_test.fds` and `HVAC/leak_test_2.fds`. In both cases, Zone 1 was declared to be the entire domain, and Zone 2 was supposed to override Zone 1. This is no longer allowed. 

Commit #3716.

**Closed as completed by mcgratta** 2016-03-24 14:28 UTC

**Comment by drjfloyd** [comment] 2016-03-24 14:48
A grid cell should only be in one pressure zone.  If it is in two, either the ZONE inputs overlapped  or the two zones should be merged into one.  I agree that we shouldn't let user's overlap ZONE inputs as then order of the ZONE inputs will matter for what ZONE gets set. In the other case, hopefully we trap that in the logic to merge zones that are connected by some vent path.
