### ISSUE TITLE
CONVERT_VOLUME_TO_MASS and using intlet velocity profiles

### ISSUE THREAD

**Issue by amymensch** [firemodels/fds#6035] opened 2018-02-15 20:58 UTC
This is for a low velocity rectangular channel flow simulation with one hot wall and one cold wall to replicate my experiment.  My inlet boundary condition has a specified velocity and mass fraction of soot.  I also specify two velocity profiles in both directions across the rectangular inlet.  Initially I did not use CONVERT_VOLUME_TO_MASS = .TRUE., and the mass fraction at the inlet seems to be correct.  However, I added it based on the recommendation in Sect. 9.1.6 in the User Guide.  Once CONVERT_VOLUME_TO_MASS = .TRUE. was added, it seems to ignore my velocity profile RAMP lines, and the inlet velocity is now just -1 m/s.  The inlet soot mass fraction still seems to be the same.

Attached files are the fds input files, velocity profiles, and mass fraction profiles without the conversion (channel1.txt, VelProfile1.png, SootMFProfile1.png) and after adding the conversion command (channel2.txt, VelProfile2.png, SootMFProfile2.png).

I think I can just run without CONVERT_VOLUME_TO_MASS = .TRUE., but I didn't see any warning in the User Guide that RAMP profiles couldn't be used with this.

From 9.1.6 in the User Guide:
Note that specifying a combination of VEL and MASS_FRACTION can lead to inaccurate results if the specified velocity is small because diffusion will dominate the mass transport. To obtain an accurate species mass flux at a boundary, use MASS_FLUX.
Alternatively, add CONVERT_VOLUME_TO_MASS=.TRUE. for velocity boundaries (VEL, VOLUME_FLOW,
or MASS_FLUX_TOTAL), which converts volume flow to a mass flux based on the specified boundary composition (MASS_FRACTION) and temperature (TMP_FRONT):

Edit: Running FDS 6.6.0

[channel2.txt](https://github.com/firemodels/fds/files/1729330/channel2.txt)
![velprofile1](https://user-images.githubusercontent.com/25989959/36280661-efd3e7fc-1292-11e8-9c4f-f5f66b81f87d.png)
![velprofile2](https://user-images.githubusercontent.com/25989959/36280663-f0005c6a-1292-11e8-8e10-b1c2989ddf2f.png)
![sootmfprofile1](https://user-images.githubusercontent.com/25989959/36280664-f0134d8e-1292-11e8-8b5e-dbdf49d707e8.png)
![sootmfprofile2](https://user-images.githubusercontent.com/25989959/36280665-f0223c0e-1292-11e8-957d-82ba634cd641.png)
[channel1.txt](https://github.com/firemodels/fds/files/1729331/channel1.txt)

**Comment by rmcdermo** [comment] 2018-02-15 21:08
Thanks, Amy.  I think the RAMP should still work.  We'll take a look.

**Comment by rmcdermo** [comment] 2018-02-15 22:11
OK, the issue is that once you covert to volume to mass, you are using a MASS_FLUX boundary condition and the velocity ramps are not connected to those.  This is going to take some surgery to fix.  I recommend that you just use a MASS FLUX BC without a ramp and extend the domain upstream by 10 diameters or so (you can use coarse resolution in the streamwise direction for this), and just let FDS develop the velocity profile for you.  Would that work?  You must have some entrance length anyway in the experiment if you have a parabolic velocity profile.

**Comment by amymensch** [comment] 2018-02-15 22:21
I will think about that.  The velocity profile I set is not the fully developed profile - it is the velocity profile I found from running a Comsol CFD simulation that models the full upstream geometry (there's a converging inlet with a cylindrical rod across the flow).  But it may not be too much of an issue to extend it upstream and assume the parabolic profile starts at the inlet.
Alternatively, do you think I need to have the CONVERT_VOLUME_TO_MASS = .TRUE. since it looks like the mass fraction is the same at x = 0 either way?

**Comment by rmcdermo** [comment] 2018-02-23 21:55
Amy, what is the status?  For now I've pushed up a note to the user guide and code to throw an error is CONVERT_VOLUME_TO_MASS = .TRUE. is used with a velocity ramp. #6064 

I'm going to close this for now, but come by if you want to talk about other options for modeling the inlet.

**Closed as completed by rmcdermo** 2018-02-23 21:55 UTC
