### ISSUE TITLE
Pressure rise due to leakage, FDS version 5.5.3

### ISSUE THREAD

**Issue by linnealind** [firemodels/fds#7280] opened 2019-04-08 11:36 UTC
Hi,

I'm a student who just started to learn FDS and I have a question regarding pressure rise due to leakage. I'm using FDS version 5.5.3 since my computer is too old for newer versions.

The leakage area of my compartment is 0.023 m and I would like to compute the pressure rise due to fire for an air-tight compartment relative to outside. I have read about bulk leakage, localized leakage and pressure zones, but I'm not sure which method I can, or should, use.

What's the difference between bulk leakage and pressure zones? Is it fair to say they work the same and/or are equivalent? Do I need to have obstructions as outer walls even though pressure zone (1) consists of the entire compartment?

The input file is attached below. There might be major errors in it, so sorry about that.
I would really appreciate if someone could help me in this matter. 

Kind regards,
Linnea 

[Input.fds.txt](https://github.com/firemodels/fds/files/3054049/Input.fds.txt)

**Comment by sbenkorichi** [comment] 2019-04-08 11:39
Hi Linnea,
Questions are to be asked in the discussion group here 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/fds-smv

I'm closing this as it's not a bug in the code.

**Closed as completed by sbenkorichi** 2019-04-08 11:39 UTC

**Comment by linnealind** [comment] 2019-04-08 11:41
Oh, sorry. Thanks!
