### ISSUE TITLE
Different results FDS 6.4.0 vs. FDS 6.6.0

### ISSUE THREAD

**Issue by gsztar** [firemodels/fds#5676] opened 2017-11-04 18:02 UTC
I would like to came back to issue #5639.
The same cases but calculated with different versions on FDS. The results derived with FDS 6.6.0 doesn't look realistic.
I remeshed case but it didn't help. Problem occurs with mesh with fire. 
**FDS 6.6.0**
![sd1_test_0625](https://user-images.githubusercontent.com/16048248/32408077-8185eefe-c192-11e7-8d63-b9ece02f3d64.png)
**FDS 6.4.0**
![sd1_test6proc_0625](https://user-images.githubusercontent.com/16048248/32408084-9eadc236-c192-11e7-86e6-fcf625cc009e.png)

**Comment by sbenkorichi** [comment] 2017-11-04 18:11
Try using the new pressure solver. 
Add this line to your input file
`&PRES SOLVER='GLMAT' /`
See if it helps.

**Comment by gsztar** [comment] 2017-11-04 18:41
This problem in my opinion is not related with pressure solver. The same I reported in version 6.5.3.

**Comment by sbenkorichi** [comment] 2017-11-04 19:20
Do you get same results when you run it in serial i.e. as fds job.fds 
If you haven't tried it, can you give it a shot. I would like to know if this has to do with parallelism or not.
I think we need to set some verification cases for this type of runs.

**Comment by gsztar** [comment] 2017-11-04 19:34
I will try a come back soon.

**Comment by sbenkorichi** [comment] 2017-11-04 19:35
Thanks !

**Comment by gsztar** [comment] 2017-11-05 07:47
Please, look at results of serial. 
The calculation are still in progress. Results for next seconds I will deliver in the end of a day.
Still problem in the mesh with fire. Fire is defined as a vent.
![sd1_test_0215](https://user-images.githubusercontent.com/16048248/32412897-656d3830-c205-11e7-8e2e-c2fdbdf7a3e9.png)

**Comment by mcgratta** [comment] 2017-11-05 18:07
I ran the original case, `SD1.fds`, with FDS 6.6.0, parallel, linux. This is what I see:
![image](https://user-images.githubusercontent.com/11333911/32417628-308b7f94-c22a-11e7-8e84-787449afc52e.png)

**Comment by gsztar** [comment] 2017-11-05 19:44
The case SD1.fds in issue #5639 is simple version. Original case (show above) is much more complected. 
The smoke should pass top smoke barrier. 
If you can please show slice of temperature and velocity on z=1,6 m
My proposal is that we have to check this phenomenon on original case. I attached original case.
[SD1_test.txt](https://github.com/firemodels/fds/files/1444354/SD1_test.txt)

**Comment by gsztar** [comment] 2017-11-06 06:52
@mcgratta I have received similar results for simple case. Please look at next results for original case.
![sd1_test_0439](https://user-images.githubusercontent.com/16048248/32428658-2bbc7764-c2c7-11e7-80a8-53c9760436dd.png)
![t_sd1_test_0439](https://user-images.githubusercontent.com/16048248/32428708-774be584-c2c7-11e7-8d38-fa3c119d38f0.png)

**Comment by sbenkorichi** [comment] 2017-11-07 10:16
I now can see what's going in your case.
I don't see any issue of communication between the meshes. You have set a wind (velocity) that is pushing the smoke at these two edges. It is simple, your smoke has to be dense enough in order to push through these two barriers in order to pass. Then, once it passes, it will be sucked by the other edge. I don't see how can this be an issue of communication between these meshes.


![sd1_0625](https://user-images.githubusercontent.com/20113030/32488266-f99c7814-c3a3-11e7-81c5-e0b8a5ad38c1.png)

![sd1_1200](https://user-images.githubusercontent.com/20113030/32488442-83c1cb20-c3a4-11e7-872b-47bc01ffca2c.png)

**Comment by gsztar** [comment] 2017-11-07 10:27
Salah,
you are right for simple model. Please look at full case.

**Comment by sbenkorichi** [comment] 2017-11-07 18:26
No luck, 
I run it towards 150s, everything seems to be ok, ( you can see the smoke passes through that upper velocity, but then gets sucked by it to return it back to the other mesh. 
I need to rerun the case, after I've broken my system lol. I was trying to setup a cluster by adding another computer to my machine, everything was working fine, can loggin to each one, yet I messed it when I was setting up NFS-server on the master node. I messed up with my dpgk, now I have to reinstall it. I'll try to set it back as soon as possible.

**Comment by gsztar** [comment] 2017-11-07 20:07
Salah,
please observer smoke from 90 s to end of simulation. At this time exhaust shaft starts.

**Comment by sbenkorichi** [comment] 2017-11-08 15:20
500s
Your smoke moves fine, it does passes to the other meshes until you trigger the devices at 90s, then they will push and suck the smoke back. See the arrows in Fig. 2. The smoke needs to get dense and accumulated, in order to be able to move to the other meshes against that vel that you've defined.
There might be a slight difference in results from machine to another, but no big divergence is noticed.

![sd1_test_0504](https://user-images.githubusercontent.com/20113030/32556615-d3c667b8-c497-11e7-9088-58705011acdd.png)

![sd1_test_0502](https://user-images.githubusercontent.com/20113030/32556585-c2163e58-c497-11e7-9a5f-6332b2023096.png)

**Comment by gsztar** [comment] 2017-11-08 19:05
Please look at results in 500 s (FDS 6.4.0).  Sorry but results from FDS 6.6.0 are not realistic. 
Your border of smoke and velocity is a mesh border.
![sd1_0500](https://user-images.githubusercontent.com/16048248/32567786-a2a953c8-c4bc-11e7-8825-e0c17b75557d.png)
And velocity z=2,0 m (0.0 -9,5 m/s) as in your slice.
![sd1_v_0500](https://user-images.githubusercontent.com/16048248/32568138-b15e2f3c-c4bd-11e7-9590-74eaac417750.png)

**Comment by sbenkorichi** [comment] 2017-11-08 19:16
Well, I will try to go back and check with 6.4. Maybe I can spot the cause of this differences.

**Comment by sbenkorichi** [comment] 2017-11-08 19:20
I need to know this:
did you run it in parallel with 6.4? If yes, where did you get openmpi from? 
Or is it you who compiled it?
Paste the way how you run the case with.

**Comment by gsztar** [comment] 2017-11-08 19:29
I tested on parallel and single. Results are similar.
I downloaded FDS from website: https://github.com/firemodels/fds/releases
To run I used: mpirun -np 8 -hostfile host.txt fds SD1.fds
And NUM_OMP_THREADS=1

**Comment by sbenkorichi** [comment] 2017-11-08 19:33
Where did you get mpirun from? It's not in the 6.4.

**Comment by gsztar** [comment] 2017-11-08 19:36
_fds@n1:~$ mpirun --version
mpirun (Open MPI) 1.8.4_

**Comment by sbenkorichi** [comment] 2017-11-08 19:37
Do me this:
`$ which mpirun `

**Comment by gsztar** [comment] 2017-11-08 19:38
_fds@n1:~$ which mpirun
/shared/openmpi_64/bin/mpirun_

**Comment by sbenkorichi** [comment] 2017-11-08 19:40
Hmm, 
How did you installed there? Was it you who compile it ? 
Do you know which setps that you followed to get it installed there? Was it from one of our wiki pages?

**Comment by gsztar** [comment] 2017-11-08 19:56
It was from your wiki page https://github.com/firemodels/fds/wiki/Installing-Open-MPI-on-a-Linux-Cluster.
Installing Open MPI from Pre-Compiled Binaries.

**Comment by sbenkorichi** [comment] 2017-11-08 20:03
Ok, now I see. I can't download it, looks like the links are expired. I will just compile it and compile the source code.

**Comment by mcgratta** [comment] 2017-11-08 22:37
Here is my result at 500 s with FDS 6.6.0. Is there a problem with this image?

![image](https://user-images.githubusercontent.com/11333911/32578466-555c0338-c4ab-11e7-8dc1-74aac629d027.png)

**Comment by sbenkorichi** [comment] 2017-11-08 22:42
Hmm,
I had to run it with mpiexec -n 5.
Did you use -n 8?
Also, looks like your case already finished. Mine still at 610. Probably the case needs first to finish then reload the smoke.

**Comment by gsztar** [comment] 2017-11-09 08:04
@mcgratta It looks very similar. Are you using FDS on Linux or rather Windows? Could you please show results for 120 s and 300 s? Why @sbenkorichi and my are different than yours?
What did you change in your FDS or in fds file? Where is the trick?
@sbenkorichi  I run with mpiexec -n 8. If we have to wait for finish the case and than we reload the results, the all advantages with controlling simulation during calculation time disappears.

**Comment by sbenkorichi** [comment] 2017-11-09 09:12
@gsztar 
My answer is that we have to let it finish and check. I agree with you that would be a problem to monitor results only after run time. I left it running last night. I doubt that there's a problem between different platforms, if so we need to isolate the issue.

**Comment by mcgratta** [comment] 2017-11-09 13:06
I ran this with 8 MPI processes, FDS 6.6.0, Open MPI, linux OS.

**Comment by sbenkorichi** [comment] 2017-11-09 13:14
I see, you run it on the cluster and view it with windows. Fair enough.
The run time is at 900s. Still waiting for it to finish to verify the final results ( I don't want to speculate for now). 
In case, I would get results similar to yours at the end of the run, then why results aren't as accurate during the middle of run as the end of run time? Since we're running parallel jobs, I would assume that result at certain time should stay the same, despite the fact that simulation didn't end. -- Unless, I'm missing something here. Thanks !

![sd1_test_0501](https://user-images.githubusercontent.com/20113030/32606976-2efd8fe6-c54f-11e7-85ff-cf8457e70714.png)

**Comment by gsztar** [comment] 2017-11-09 13:50
@mcgratta Could you please show us results for 120 s and 300 s?

**Comment by sbenkorichi** [comment] 2017-11-10 12:24
My case has finished, but looks like we're getting different results here, this is weird: 
FDS6.6 : 500s.
![sd1_test_0501](https://user-images.githubusercontent.com/20113030/32658407-c5fea19c-c611-11e7-86fd-18cbb8f0492e.png)

1000s 
![sd1_test_1001](https://user-images.githubusercontent.com/20113030/32658424-d6e08bb0-c611-11e7-9c7d-6eda736be64c.png)

1200s

![sd1_test_1201](https://user-images.githubusercontent.com/20113030/32658428-dc63fcf2-c611-11e7-8b57-889f83b18a18.png)

**Comment by sbenkorichi** [comment] 2017-11-10 12:50
@gsztar Have you restarted the job? If so, can you tell how many times? 
My first guess goes to the restart function since I've did it couple times. I doubt Kevin has restarted his case. I will rerun the case without restarting it.

**Comment by gsztar** [comment] 2017-11-10 13:00
@sbenkorichi No, I did not restart my jobs.

**Comment by sbenkorichi** [comment] 2017-11-10 13:07
Ok,
Since you and I have set OMP_NUM_THREADS=1, I would will wait for Kevin when he's back to see if he has set it to 1 or not. I'm just trying to understand the reason behind these differences.

**Comment by gsztar** [comment] 2017-11-10 13:24
@sbenkorichi In my opinion and observations the problem starts when ventilation is switch on.
My results in FDS 6.4.0 in 900 s and 1200 s
![sd1_test6proc_0900](https://user-images.githubusercontent.com/16048248/32660380-e126a3c8-c622-11e7-8629-51d2f3c58b0f.png)
![sd1_test6proc_1200](https://user-images.githubusercontent.com/16048248/32660383-e5277312-c622-11e7-8abd-bdc18cc8a031.png)

**Comment by sbenkorichi** [comment] 2017-11-10 15:07
Well, I can't come to that conclusion easily-- Ventilation switch on for all of us, i.e. we should get close results- unless it's behaving differently on different PCs. I would still make some experiments first. I've just rerun the case on my cluster, while setting up 2 threads for OpenMP, it's at 100s. We'll see.

**Comment by gsztar** [comment] 2017-11-10 15:39
I will be waiting.

**Comment by mcgratta** [comment] 2017-11-10 18:38
![image](https://user-images.githubusercontent.com/11333911/32673135-f32441ea-c61b-11e7-8db3-49ec48461bc2.png)

![image](https://user-images.githubusercontent.com/11333911/32673166-0dfe41e6-c61c-11e7-99ed-8d594cf41c25.png)

![image](https://user-images.githubusercontent.com/11333911/32673210-3fb71d16-c61c-11e7-9a30-570a2545b7fb.png)

![image](https://user-images.githubusercontent.com/11333911/32673219-4d436d9a-c61c-11e7-9a93-7fc2d6383a35.png)

**Comment by sbenkorichi** [comment] 2017-11-10 18:44
Some pre-results
Setting `OMP_NUM_THREADS=2`
`$ mpiexec -n 8 fds SD1_test.fds`
Results are quite similar to what Kevin is showing.

![sd1_test_0120](https://user-images.githubusercontent.com/20113030/32673328-acadb07c-c646-11e7-9c1d-34c09507ecac.png)

Whereas with `OMP_NUM_THREADS=1 `
This is what it gave: 
![sd1_test_0123](https://user-images.githubusercontent.com/20113030/32673391-fffec220-c646-11e7-94c7-dbc1cfea5c71.png)

I still need to try some tests before pointing out to Nbr of threads.

**Comment by gsztar** [comment] 2017-11-11 10:06
@mcgratta Kevin,Did you use OMP_NUM_THREADS=2?

**Comment by sbenkorichi** [comment] 2017-11-11 11:27
@gsztar as I said in my last post,  I don't want to point out to nbr of threads. I've rerun the case once again with `OMP_NUM_THREADS=1 `
And no adverse effects are noticed, it's somehow coming randomly. Still more tests to know (maybe) why it's behaving that way after the activation of the vents.
![sd1_test_0189](https://user-images.githubusercontent.com/20113030/32688994-1ee9f45c-c6d3-11e7-99ef-9d3ddcee6913.png)

**Comment by gsztar** [comment] 2017-11-11 11:40
@sbenkorichi OK, but it doesn't happen in FDS 6.4.0. It does start from FDS 6.5.x

**Comment by sbenkorichi** [comment] 2017-11-11 11:45
@gsztar , I can't be sure of that, unless to do more testing with 6.4. Currently, I'm focusing on 6.6.
Chances that you didn't get it once or twice with 6.4 doesn't mean you might not get it in 10x case test.
I will try to work on simplifying the case, I can't wait 1 day to see the result of one run.

**Comment by gsztar** [comment] 2017-11-11 12:40
@sbenkorichi _Chances that you didn't get it once or twice with 6.4 doesn't mean you might not get it in 10x case test._ How can I understand this? Is system unstable? I am using the same meshes size, the same boundary and initial conditions and the same models. Why the results should be different?

**Comment by sbenkorichi** [comment] 2017-11-11 13:30
Theoretically, yes, you should get similar results, but not with this input setup. Chances, that there might be a hidden bug in the code that appears with what you are specifying in your inputfile. First, we need to reproduce this issue with simplified case in order to isolate the issue.

**Comment by gsztar** [comment] 2017-11-11 13:39
OK. Thank you.

**Comment by mcgratta** [comment] 2017-11-11 15:07
I ran the case with 1 OpenMP thread. Can you tell me whether my result is what you expect based on the older version. Also, are your new results unphysical, or just different than the older results? There are various reasons why you might see different results between versions. For example, the butterfly effect. Obviously, there are small differences in various routines as we go from one version to the next. Some simulations might be sensitive to these changes, much like you cannot expect two actual fire experiments to yield the exact same result.

**Comment by sbenkorichi** [comment] 2017-11-11 15:20
Well, in your case looks more reasonable, and smoke isn't stuck in the mesh (in red), but rather keeps spreading. This behaviour comes randomly after t=90s as in the CTRL setpoint, with FDS6.6, when I run it first, I had this issue, then I rerun it, I didn't get this issue. 
![sd1_test_0232](https://user-images.githubusercontent.com/20113030/32690740-558ec576-c6f3-11e7-824f-e1b08eb3a152.png)

![sd1_test_0233](https://user-images.githubusercontent.com/20113030/32690760-cdfe9a40-c6f3-11e7-825e-d268ccf9db18.png)

**Comment by gsztar** [comment] 2017-11-11 15:35
@mcgratta Yes, your results look OK. But the question is, why @sbenkorichi's and my results in FDS 6.6.0 are significantly different.
I agree with you that two full fire experiments could give different results. This is because the initial conditions are different, like ambient temperature, wind, humidity and others. But if you carry out two full scale experiments at the same time and place, the results should be similar. The one of advantages of CFD is that you can check different fire scenario at the same initial and boundary conditions.

**Comment by mcgratta** [comment] 2017-11-11 19:16
Are the differences just in the 3D smoke rendering, or does a horizontal slice of TEMPERATURE also indicate a problem?

**Comment by sbenkorichi** [comment] 2017-11-11 19:27
I think temperature is ok, it's giving reasonable values depending on smoke location. 
![sd1_test_0501](https://user-images.githubusercontent.com/20113030/32692754-cf966e74-c715-11e7-9154-a22b221194d3.png)
![sd1_test_1201](https://user-images.githubusercontent.com/20113030/32692755-cfaab26c-c715-11e7-804e-31070c30ed6e.png)

**Comment by gsztar** [comment] 2017-11-11 19:44
Both are wrong.
![sd1_test6proc_0500](https://user-images.githubusercontent.com/16048248/32692918-29c546e4-c721-11e7-98c6-2addc76822a8.png)
![sd1_test6proc_1200](https://user-images.githubusercontent.com/16048248/32692920-2d7230d6-c721-11e7-9047-41322044c72d.png)

**Comment by sbenkorichi** [comment] 2017-11-11 21:04
This is a different result than the previous ones. See the deposition of the smoke at the mesh interfaces (as shown in the black flesh). Smoke doesn't return to the mesh in the middle.
--Kevin, try to run this case on your system as:` $ mpiexec -n 5 fds SD1_test.fds `
With `OMP_NUM_THREADS=1`
[SD1_test.fds.txt](https://github.com/firemodels/fds/files/1464114/SD1_test.fds.txt)

![sd1_test_0119](https://user-images.githubusercontent.com/20113030/32693460-1c8ac858-c723-11e7-9b50-b786693913ca.png)
![sd1_test_0120](https://user-images.githubusercontent.com/20113030/32693461-1c9ee7ac-c723-11e7-9c16-b8d410260b3c.png)

**Comment by mcgratta** [comment] 2017-11-11 22:20
I'm going to run the full case (14 meshes) with 9 MPI processes.

**Comment by sbenkorichi** [comment] 2017-11-11 22:25
Ok that's another option. What I noticed is when running the full scale with 5 process receive this behaviour, whereas with 8 I don't. -- might to do with impair processes -- not sure yet. Will try more experiments.

**Comment by sbenkorichi** [comment] 2017-11-12 17:22
See full scale with 7 MPI process, different behaviour noticed as well:
I will try with 6 and 4 to confirm how they're solving.
![sd1_test_0120](https://user-images.githubusercontent.com/20113030/32701449-cca98274-c7cd-11e7-9f8f-3b4b9752cbde.png)
 as well:

**Comment by mcgratta** [comment] 2017-11-12 17:58
Here's what I get with 9 MPI process, where I assign the smaller sized meshes to share a process with a big one.

![image](https://user-images.githubusercontent.com/11333911/32701760-2b4ec32c-c7a9-11e7-893d-ec04aed1f0fe.png)

**Comment by sbenkorichi** [comment] 2017-11-12 19:15
Hmm, interesting, still your system is not having any issues. Check this 4 MPI process, there is an improvment in results between black and blue mesh, but still between black and red. I think the way how these meshes are assigned to MPI_PROCESS which is making these differences.
Kevin --To see if you could receive similar behaviour, can you run this full case with 5 MPI process as they're set in the inputfile, let's see if you would get it or not.
[SD1_test.fds.txt](https://github.com/firemodels/fds/files/1465011/SD1_test.fds.txt)

I will do another test to see if it has to do with assigning them to MPI_PROCESS.
![sd1_test_0120](https://user-images.githubusercontent.com/20113030/32702317-20088eba-c7dd-11e7-83f5-3e829ea75198.png)

**Comment by gsztar** [comment] 2017-11-12 19:28
@mcgratta and @sbenkorichi 
How can I help?

**Comment by sbenkorichi** [comment] 2017-11-12 19:36
Well, I'm going to leave this case run at least for 120s and see if changing how the mpi process are assigned would make the difference. It won't hurt if you run the case under your system as well to double check with my results. 
[SD1_test.fds.txt](https://github.com/firemodels/fds/files/1465028/SD1_test.fds.txt)
run it as `$ mpiexec -np 7 fds SD1_test.fds`

**Comment by sbenkorichi** [comment] 2017-11-12 22:14
This is my results with 7 MPI process after changing the assigned mpi process. Results are better now compared with previous case when meshes were randomly assigned to mpi processes --Though, still the black mesh isn't communicating well with the red one.
![sd1_test_0120](https://user-images.githubusercontent.com/20113030/32704017-978fa9dc-c7f6-11e7-9e69-01e992fd1b57.png)

**Comment by sbenkorichi** [comment] 2017-11-13 09:29
Now, I'm getting appropriate results after assigning black, red, and brick meshes in different MPI_PROCESS, I'm using 7 MPI process and getting no adverse effects.
[SD1_test.fds.txt](https://github.com/firemodels/fds/files/1466242/SD1_test.fds.txt)

**EDIT:** 
I rerun the case for the second time, the same result obtained as in the attached picture.

**EDIT2**
I rerun the case for the third time. No adverse errors are noticed. Looks like separating them on different MPI_PROCESS helped. 

![sd1_test_0120](https://user-images.githubusercontent.com/20113030/32721209-a56c166e-c85d-11e7-9b8d-77d81ccd56e7.png)

**Comment by mcgratta** [comment] 2017-11-14 21:16
@gsztar, is your original problem solved? Can you tell me what is not working properly in FDS 6.6.0?

**Comment by gsztar** [comment] 2017-11-15 07:53
@mcgratta, my problem with FDS 6.6.0 still exists - we have got random error with communication between meshes as you can see above. As you know I reported this problem in FDS 6.5.2 also. This kind of problems have never occured in FDS 6.4.0. To solve my problem I would like to know:
 - What are the quidelines for assigning the meshes to MPI_PROCESS?
 - Are there any limits with numbers of meshes assigned to one MPI_PROCESS?
 - What about OMP_NUM_THREADS? Should it be set as 1 or not. How should we set this variable for example: Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 cores) ? Does it depend on type of processor?
 - Why did @sbenkorichi's and I receive different results than you for the same case? What kind of setting  should be set in Linux?

**Comment by mcgratta** [comment] 2017-11-15 15:07
Answer the following
1. Which input file are you referring to? There are several above. Let's focus on just one.
2. If you assign one mesh to each MPI process, and set OMP_NUM_THREADS=1, do you have problems?
3. If the answer to 2 is no, what number of MPI processes and OpenMP threads causes problems?

**Comment by sbenkorichi** [comment] 2017-11-15 15:23
This is my feedback:
Through the tests that I did: 

1. Any inputfile from above.
2. When Either of red, brick, black meshes are assigned together in same MPI_PROCESS (whether RED and BLACK, or BLACK and BRICK etc..). I notice this weird behaviour between them. Whenever they're not assigned together, I don't. My results are quite similar to yours. 
3. I'm not sure if OMP_THREAD is an issue. It's really hard to diagnose this large input. I'm planning to make some further testing for MPI_PROCESS on different cases (as the one in Verification suite) To just check if we do have a problem or not.

**Comment by mcgratta** [comment] 2017-11-15 21:32
Give me 1 case that fails. Specify it exactly.

**Comment by sbenkorichi** [comment] 2017-11-15 21:57
`$mpiexec -np 5 fds SD1_test.fds`
`OMP_NUM_THREDS=1`
t_end =120s i sufficient
[SD1_test.fds.txt](https://github.com/firemodels/fds/files/1476496/SD1_test.fds.txt)

**Comment by gsztar** [comment] 2017-11-16 07:23
@sbenkorichi Did you run your case on 1 computer?

**Comment by sbenkorichi** [comment] 2017-11-16 07:29
The case of 5MPI was ran on one computer. But for 7, 8 was ran on 2 computers(cluster).

**Comment by sbenkorichi** [comment] 2017-11-16 07:53
@gsztar 
Can you run this case and report if it shows issues on your system or not. I've run it more than 3 times and it proves to work. I just had to put the three main meshes on the left on different MPI_PROCESS, I'm no longer receiving any adverse effect. --Just want to make sure it works on your side or not.
Notice that this is the same case was having issues with before changing assignment of meshes.
`$ mpiexec -np 7 fds SD1_test.fds`
`$ OMP_NUM_THREADS=1`
[SD1_test.fds.txt](https://github.com/firemodels/fds/files/1477718/SD1_test.fds.txt)

**Comment by gsztar** [comment] 2017-11-16 13:05
**@sbenkorichi** 
OK, I will do this.

**Comment by mcgratta** [comment] 2017-11-16 13:47
![image](https://user-images.githubusercontent.com/11333911/32894353-98cc312e-caaa-11e7-826f-95553bf1b5dc.png)

I can also confirm that something is not right when running the case with 5 MPI processes, dividing the meshes as was done in the `SD1_test.fds` case. I am not sure of the cause, but for the moment, do not put multiple large meshes on a single MPI process.

**Comment by sbenkorichi** [comment] 2017-11-16 14:20
Glad you could reproduce it from your end as well. I will make some cases from simpler to complex to see at what point this behaviour starts.

**Comment by gsztar** [comment] 2017-11-16 18:43
There is not hardware limitation in my opinion. The same case, on the same hardware but using FDS 6.4.0 works well.

**Comment by gsztar** [comment] 2017-11-22 15:41
Are there any news about solution of problem?

**Comment by mcgratta** [comment] 2017-11-22 15:42
No, and there might not be one for some time. For now, do not assign your big meshes to the same MPI process.

**Comment by mcgratta** [comment] 2018-01-02 20:29
I am going to close this issue. The case is too complex to diagnose. Do not overload large meshes on the same MPI process. It is possible that this imbalance in resources leads to different processes running too far ahead of the others. This is not supposed to happen, but I have not extensively tested it. This is not a particularly good test case.

**Closed as completed by mcgratta** 2018-01-02 20:29 UTC

**Comment by gsztar** [comment] 2018-01-03 08:28
Kevin, this case is a real case. In my opinion real cases are always good for test.

**Comment by sbenkorichi** [comment] 2018-06-27 13:55
@gsztar 
Try the latest release (6.7.0). Kevin has fixed this issue recently. 
Report back if it fixes your problem. 

https://pages.nist.gov/fds-smv/downloads.html

Thanks !
