### ISSUE TITLE
Place of the MESH in negativ Z area ends with access violation

### ISSUE THREAD

**Issue by CsSzikra** [firemodels/fds#4814] opened 2017-03-12 07:58 UTC
Dear All,

It seems to be, when the MESH is totally in negative Z area, fds ends with access violation. I made a simple test case. Only the default mesh was set, then it was shifted by 3.25m to get negative Z coordinate. This is the result:
``
Starting FDS: C:\Program Files\PyroSim 2017\fds\fds.exe...
 Mesh      1 is assigned to MPI Process      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : March 11, 2017  22:14:23
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1
 Revision Date    : Thu Jan 19 16:12:59 2017 -0500
 Compilation Date : Fri 01/20/2017  09:11 PM

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.3 for Windows* OS

 Job TITLE        : 
 Job ID string    : MESH

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source             
fds.exe            00007FF780F647B5  Unknown               Unknown  Unknown
fds.exe            00007FF780F54D56  Unknown               Unknown  Unknown
fds.exe            00007FF780F44649  Unknown               Unknown  Unknown
fds.exe            00007FF780F435BF  Unknown               Unknown  Unknown
fds.exe            00007FF780C4DAA0  MAIN__                    533  main.f90
fds.exe            00007FF780C4A8BE  Unknown               Unknown  Unknown
fds.exe            00007FF78139A840  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFCFD7C8364  Unknown               Unknown  Unknown
ntdll.dll          00007FFCFDC070D1  Unknown               Unknown  Unknown

And the FDS source:

MESH.fds
Generated by PyroSim - Version 2017.1.0209
2017.03.11. 22:37:25

&HEAD CHID='MESH'/
&TIME T_END=10.0/
&DUMP RENDER_FILE='MESH.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0/

&MESH ID='Mesh01', IJK=40,40,12, XB=0.0,10.0,0.0,10.0,-3.25,-0.25/

&TAIL / 

Also I have tested the code in earlier FDS version (6.4.0), but it was OK. 

Any Idea about this problem?

Best Regards,
Csaba Szikra

**Comment by sbenkorichi** [comment] 2017-03-12 10:35
Hi CsSzikra,
You are right, I tested it on my end with the latest release, it doesn't seem to be working when the entire Z is negative. I tested now the previous release, FDS 6.5.2 SMV 6.3.12 - Git-r21-0-g4e9103f . It works fine.
Maybe there is something was changed in the latest release that causing this issue. 
Wait for Kevin, or another member to check the cause of this issue.
Regards,
Salah

**Comment by rmcdermo** [comment] 2017-03-12 11:56
Thanks for the report.  I confirm the release does not work.  However, the latest source seems to work.  So, maybe Kevin fixed something.  I will let him confirm.  But this should be working in next maintenance release.

**Comment by mcgratta** [comment] 2017-03-13 12:35
Yes, I fixed this. For now, set `STRATIFICATION=.FALSE.` on the `MISC` line. Let me know if that fixes it.

**Comment by sbenkorichi** [comment] 2017-03-13 13:35
Kevin,

I confirm adding:  &MISC STRATIFICATION=.FALSE / fixed the issue.

Regards,
Salah

**Comment by rmcdermo** [comment] 2017-03-13 13:42
Thanks.  General fix will be in next release, so I will close.

**Closed as completed by rmcdermo** 2017-03-13 13:42 UTC

**Comment by CsSzikra** [comment] 2017-03-13 15:17
Thank you. It works.

Regards,
Csaba
