### ISSUE TITLE
Velocity error at mesh interface

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#4232] opened 2016-08-23 09:46 UTC
I'm trying to validate a fire scenario in tunnel using FDS 6.5.0, the simulation runs well and it doesn't show any numerical instability, but the results are quite strange at the mesh interface before the tunnel's outlet. I attach the plots of temperature and velocity along the middle plane in order to show the discontinuity in the flow field, the input file and the out file. 
For the simulation's convergence I set up VELOCITY_TOLERANCE=0.001, MAX_PRESSURE_ITERATIONS=40 and the maximum errors are never exceeding 0.1 m/s. 
I already validated this case with the previous version of FDS 6.1.1 which fitted quite well the experimental results and didn't show any strange behaviour at the interface of the meshes. I tried to move the mesh interface in order to see if this can improve the solution, but the flow discontinuity was following the mesh interface. 

Thanks for your help,

Kind regards,

Matteo

[input_tunnel.fds.txt](https://github.com/firemodels/fds-smv/files/432106/input_tunnel.fds.txt)
[french_tunnel.out.txt](https://github.com/firemodels/fds-smv/files/432075/french_tunnel.out.txt)
![u_velocity](https://cloud.githubusercontent.com/assets/15084725/17886890/302410c6-6924-11e6-984b-c5e5e3f93ed2.png)
![temperature](https://cloud.githubusercontent.com/assets/15084725/17886889/30237616-6924-11e6-8d8c-fc9a46a527ff.png)

**Comment by rmcdermo** [comment] 2016-08-23 12:25
Thanks for the report.  We'll have a look.

**Comment by mcgratta** [comment] 2016-08-23 12:58
Try running with the latest release, 6.5.1. I have been making improvements to the pressure solver in geometries like tunnels.

**Comment by mpachera** [comment] 2016-08-23 13:41
Unfortunately I cannot install the last release because I don't have the root access to the computer and I have to contact first the computer tech, hope I will have the new release in the next week.

**Comment by mcgratta** [comment] 2016-08-23 13:52
Why don't you just install it in your home directory?

**Comment by mpachera** [comment] 2016-08-23 15:05
Thanks for the advise now I'm running the case with the last version 6.5.1 I will post the results once they will be ready.

**Comment by mcgratta** [comment] 2016-08-23 15:07
I am too, but the problem is still there. The one bit of advice for you is to remove the PRES line. This does not seem to be helping, but I am not sure why at the moment.

**Comment by mcgratta** [comment] 2016-08-23 21:00
The outflow condition seems a bit awkward. You have set the velocity to 1 m/s uniformly over the exit of the tunnel. In reality, hot gases will probably flow faster near the top of the fan. Try these things:

Simpler meshing

```
&MESH IJK=60,25,25 XB=-22.5,-16.5,-1.25,1.25,0.0,2.5, MULT_ID='mesh' /
&MULT ID='mesh', DX=6., I_UPPER=7 /
```

More natural outflow condition

```
&VENT XB=25.5, 25.5,-1.25,1.25,0.0,2.5, SURF_ID='OPEN', DYNAMIC_PRESSURE=-2. /
```

Note that the -2 Pa is just a guess. I ran the case without the fire and by trial and error came up with -2. You may want to be more precise.

I've run the case out to about 140 s and things seem stable. I'll let it go overnight and let you know how things turn out tomorrow.

**Comment by mpachera** [comment] 2016-08-24 06:07
I know my boundary condition is quite strange, but from the experiment I know the volume flow extracted and I don't have any information about the pressure. From the experiment the volume flow extracted by the fan was kept constant, so I don't think the pressure would be constant in time. Also the VOLUME_FLOW cannot help me because the velocity will be constant anyway on the outlet. I can try to model differently the geometry of the outlet in order to create a mixing zone and impose the volume at the outlet. Just I thought that it is strange that the older version of FDS didn't show this problem.

**Comment by rmcdermo** [comment] 2016-08-24 12:21
I think your bc is fine.  I agree that there is a problem at the mesh
boundary that needs to be addressed.

**Comment by mpachera** [comment] 2016-08-24 13:14
I tried to use a more realistic boundary condition creating a cone at the outlet of the tunnel which should uniform the flow, but the problem is still here. I attach the plot of velocity and temperature for this case.
![temp](https://cloud.githubusercontent.com/assets/15084725/17931761/4c43b07e-6a0d-11e6-972e-6dd7d19f7916.png)
![u_velocity](https://cloud.githubusercontent.com/assets/15084725/17931760/4c3f54f2-6a0d-11e6-9f35-27314fde1836.png)

**Comment by mcgratta** [comment] 2016-08-24 20:13
OK, let's try again. Given the input file you originally posted, I first replaced the mesh lines with:

```
&MESH IJK=60,25,25, XB=-22.5,-16.5,-1.25,1.25,0.0,2.5, MULT_ID='mesh' /
&MULT ID='mesh', DX=6., I_UPPER=7 /
```

Then I modified the `PRES` line:

```
&PRES PRESSURE_TOLERANCE=1000., VELOCITY_TOLERANCE=0.001, MAX_PRESSURE_ITERATIONS=40/
```

It is difficult to explain what `PRESSURE_TOLERANCE` means. You would have to read the FDS Technical Reference Guide, section "Coupling the Velocity and Pressure". In short, I lowered the `PRESSURE_TOLERANCE` from 2000 to 1000. This acts to tighten the coupling of the baroclinic torque term in the overall pressure iteration scheme. This term is particularly troublesome in tunnel geometries. 

Try this and let me know if it works for you. I have your original case run almost to completion.

**Comment by mpachera** [comment] 2016-08-29 09:40
I ran some cases implementing the new mesh cutting and the pressure tolerance with some interesting results. Using the new mesh the and the pressure tolerance the results look better and there is no discontinuity on the mesh interface fig_1, using only the pressure tolerance and my old mesh the fluctuations are still there fig_2.  I was actually using my old mesh just to don't have mesh interface close to the fire and I didn't thought the result could be so sensitive on the mesh cutting. 

I compared the results obtained with the new version FDS 6.5.1 with the old one already validated FDS 6.1.1 and I found out that the temperature in the last version are always higher compared to the previous version. In particular the temperature near the fire are quite different since with FDS 6.1.1 the flame temperature near the ceiling is about 800 °C, fig 3, while with FDS 6.5.1 the temperature is about 1150 °C fig_1, fig_2. I know that the radiative fraction changed among the two versions (https://github.com/firemodels/fds-smv/wiki/FDS-Release-Notes) and I also ran a case with my old set up with radiative fraction 0.35 but this didn't affect the temperature in the fire region fig_4. 
I would like to know if there are other set up that are driving the flame temperature or I'm missing some other changes between the versions.
I thank you once more for your help,
Kind regards,
Matteo Pachera

fig_1
![fig_1](https://cloud.githubusercontent.com/assets/15084725/18047318/91fe2d88-6ddc-11e6-9856-eacde38d3f7b.jpg)
fig_2
![fig_2](https://cloud.githubusercontent.com/assets/15084725/18047319/91ff0b18-6ddc-11e6-9200-6c3bea88ecb7.jpg)
fig_3
![fig_3](https://cloud.githubusercontent.com/assets/15084725/18047320/92018f32-6ddc-11e6-8569-b72265bfc9ab.jpg)
fig_4
![fig_4](https://cloud.githubusercontent.com/assets/15084725/18047317/91fdf0de-6ddc-11e6-9da8-2013f5290a99.jpg)

**Comment by mcgratta** [comment] 2016-08-29 12:54
I hesitate to draw conclusions about version changes from just one point of one experiment. Are you comparing your results with more than just a single point? If so, what is the overall trend? As we change minor releases (6.1 to 6.2, for example) we sometimes modify slightly numerical coefficients in the transport and combustion algorithms. We run our entire validation suite (about 1000 cases) to determine if there is a significant change in results.

**Comment by rmcdermo** [comment] 2016-08-29 13:03
Matteo,

My suspicion is that your original instability was caused by our removing
the Von Neumann stability constraint in an effort to increase the time
step.  I suspect that the plume temperature rise is due to removing the
heat release limiter in v6.3.  But these are just guesses.  As Kevin said,
each of these change passed all the validation before being accepted.

The issue has spawned some thinking in how we can physically limit the
baroclinic term for the given time step to avoid instabilities.  We have
derived a realizable constraint on the baroclinic force (prevents negative
kinetic energy).  I implemented this new force and your case ran to
completion with a single pressure iteration.  We are currently testing this
new term on other core validation cases.  If successful, it will likely be
available in the next minor release.

Randy

**Comment by mpachera** [comment] 2016-08-29 14:16
@mcgratta I reran another case that I previously validated with FDS 6.1 with the new FDS 6.5.1 and I didn't find any big difference between the two versions. In this experiment I have several temperature measurements both upstream and dowstream the fire and it seems that the temperature near the ceiling are higher when calculated by FDS 6.5.1. This can be consequence of the different temperature in the flame region, with the new FDS 6.5.1 the temperature peak is close to the ceiling while in the old version 6.1.1 the peak is closer to the pool. Unfortunately I don't have measurements in the fire region therefore I can only compare the two numerical results. 
@rmcdermo I can try to run my case with CHECK_VN=.TRUE and see if this avoids the instabilities also with my original grid.

Thanks to both of you for your interest in my case,

Regards,

Matteo Pachera

**Comment by rmcdermo** [comment] 2016-08-29 14:33
If you want the original case to get past the instability with 6.5.1,
another trick is to set CFL_VELOCITY_NORM=1.  You have a relatively heavy
fuel.  For some reason we have not figured out yet, heavy fuels need a
tighter CFL constraint.  If you look at your case closely in Smokeview, you
will see checkerboarding of the temperature is just a few places.  This is
tell-tale sign of DT being too large.  We struggle to thread the needle on
DT to keep things stable for a purely explicit scheme while not slowing
down the code.

**Comment by mpachera** [comment] 2016-08-29 19:24
I will try to run the case with these two options, and is there any parameter I can investigate to control the flame shape now that there is no more heat flux limiter?

**Comment by rmcdermo** [comment] 2016-08-29 19:27
No, nor would you want to.  The EDC model has been tested for Heskestad and
McCaffrey plumes.

**Comment by mcgratta** [comment] 2016-09-01 19:36
I'm going to close this issue because the original issue has been resolved. Open a new issue if you want to pursue some other aspect of this case. That will prevent confusion.

**Closed as completed by mcgratta** 2016-09-01 19:36 UTC
