### ISSUE TITLE
Problem when using wide band model (with user-defined bounds) 

### ISSUE THREAD

**Issue by jsterckm** [firemodels/fds#9586] opened 2021-06-23 13:13 UTC
Hello,

I wanted to simulate my experimental set-up on FDS. To get the the radiative heat flux generated by different spectral bands to compare the results with experiments. For that, I am using the wide band model where I chose my own band limits : the first simulation with band limits 1.0, 2.63, 3.08, the second with band limits 3.08, 3.85, 5.13 and the third with band limits 5.13, 8.51, 200 if needed. All these band limits are these included in the « Technical Reference Guide » for propane. I just wanted to obtain the intensity for two bands at once, instead of integrated intensity.  Unfortunately, I obtained negative radiative heat flux (in average -0.4 2 kW/m2, -0.4 kW/m2 and 0.001 kW/m2, respectively for my 3 simulations) and I really don't know why.

You will find attached to this message the first of these simulations (the scenario is simple : just a propane burner and a device) :
[propane_WB.fds.txt] (https://github.com/firemodels/fds/files/6702045/propane_WB.fds.txt)

Thank you

**Comment by mcgratta** [comment] 2021-06-23 14:53
There appears to be a bug here. 

Simo -- can you look at this case that I modified from the original. I am seeing negative heat flux from a small fire on an opposing wall.
```
&HEAD CHID='propane_WB', TITLE='propane_WB' /
&MESH XB=0,2,0.5,1.0,0,0.5, IJK=100,25,25 /
&TIME T_END = 6 /
&VENT MB = 'XMAX' SURF_ID = 'OPEN' /
&VENT MB = 'YMIN' SURF_ID = 'OPEN' /
&VENT MB = 'YMAX' SURF_ID = 'OPEN' /
&VENT MB = 'ZMAX' SURF_ID = 'OPEN' /
&REAC FUEL = 'PROPANE', SOOT_YIELD=0.01 /
&RADI NUMBER_RADIATION_ANGLES = 300. /
&RADI WIDE_BAND_MODEL = .TRUE. /
&RADI BAND_LIMITS = 1,2.63,3.08 /BANDES 1 ET 2
&SURF ID='BURNER', SPEC_ID='PROPANE', HRRPUA=223.52 /
&VENT XB=1.35,1.65,0.6,0.9,0.0,0.0, XYZ=1.5,0.75,0.0, RADIUS=0.15, COLOR='MAROON', SURF_ID = 'BURNER' /
&DEVC ID = 'Radiative heat flux bande1', QUANTITY = 'RADIATIVE HEAT FLUX' , XYZ=0,0.75,0.1, IOR=1 /
&BNDF QUANTITY='RADIATIVE HEAT FLUX', CELL_CENTERED=T /
&SLCF PBY=0.75, QUANTITY='INTEGRATED INTENSITY', CELL_CENTERED=T /
&SLCF PBY=0.75, QUANTITY='RADIATION LOSS', CELL_CENTERED=T /
&TAIL /
```

**Comment by shostikk** [comment] 2021-06-23 15:25
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by shostikk** [comment] 2021-06-23 22:55
This change will limit emission (radiation loss) of boundaries to within BAND_LIMITS. Previously it was simply sigma T**4, regardless of wide_band model.

Meanwhile, you can use INCIDENT HEAT FLUX output, which is not affected by wall emission.

**Comment by jsterckm** [comment] 2021-06-24 08:01
Thank you, I will get a try.

**Comment by gforney** [comment] 2021-06-24 08:42
Simo
When i am in the middle of working on stuff and i need to fix a bug. I make
a topic branch and fix the bug in it. There is a wiki on topic branches on
github in the fds central repo. You can then just push up your fix and not
push up other stuff that is not ready
Glenn

**Comment by shostikk** [comment] 2021-06-28 15:57
Thanks Glenn for tip! That wiki was very helpful. I followed it and merged my topic branch (#9604)

**Comment by mcgratta** [comment] 2021-06-28 17:09
Thanks, Simo.

To the original poster -- are you able to recompile the code and test this on your case?

**Comment by shostikk** [comment] 2021-06-28 17:26
I tested the case, and noticed that, even with very wide bands (1....200 micron), the heat flux is very different from gray model. Keep in mind that wide band model (box model) uses Planck mean absorption coefficients.

**Comment by mcgratta** [comment] 2021-06-28 17:37
Is the wide band model, in theory, the same as the gray gas if one uses a single band over the "entire" spectrum? In other words, does the wind band model "converge" to the gray gas? Or is the selection of the type of abs coeff very important?

**Comment by shostikk** [comment] 2021-06-28 18:18
No it is not the same. Indeed, we select Planck mean for wide band model, and min of Planck mean and effective mean for gray, and it makes it very different for anything except optically very thin systems. Of course, it would be easy to provide a switch for enforcing them to use e.g. Planck in both cases.

**Comment by gforney** [comment] 2021-06-28 18:22
Glad it helped.  Think randy wrote it.  I have to follow it whenever i use
topic branches.  I always forget details of creating new clean branches and
pushing them to github

**Comment by mcgratta** [comment] 2021-06-28 18:31
Have you ever tried using Planck for gray gas model? What typically happens?

**Comment by jsterckm** [comment] 2021-06-28 18:44
Hello,

Thanks to the device "Incident heat flux", I obtained what I was looking for.
When I do the sum of the three incident heat flux from my three simulations (as described in my first message), I now obtain approximately the same results that if I treated a simulation directly with 6 bands. 
Personnally, for the same scenario but with the gray gas model, I have an averaged incident heat flux very close to the one obtained with wide band models (with a difference of less than 10W/m2).

In any case thank you very much for your quick help!

**Comment by mcgratta** [comment] 2021-06-28 19:24
One thing to consider, in addition to the wide band vs gray gas issue, is that the flux pattern to a distant wall is not smooth, but rather a function of the number of angles. Be careful not to misinterpret to the heat flux to a distant, single point.

**Comment by shostikk** [comment] 2021-06-28 20:10
> Have you ever tried using Planck for gray gas model? What typically happens?

 I think I studied and reported these differences 20 years ago somewhere. Maybe slides in a presentation at NIST.  Got to see if I find them somewhere.

**Comment by mcgratta** [comment] 2021-06-30 15:53
I had to revert commit b2faa113bd612ad847a4c50b7df472f8ec953b9f. It broke some test cases and I could not figure out how to get them working again. The issue is that Q_RAD_OUT is changed elsewhere in the code.

**Comment by mcgratta** [comment] 2021-06-30 20:32
I fixed Simo's commit. Simo, could you double-check what I did. The important point is that we do not want to zero out or change Q_RAD_OUT in radi.f90 if the surface has internal radiation.

**Comment by shostikk** [comment] 2021-07-05 10:36
Thanks Kevin. I didn't realize the internal radiation case needs Q_RAD_OUT.

**Comment by mcgratta** [comment] 2021-07-05 20:07
Yes, it's tricky figuring out where these various variables are zeroed out or summed. Thanks for your help.

To the original poster, you can either re-compile the latest source code or download a [test version](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC)

**Closed as completed by mcgratta** 2021-07-05 20:07 UTC
