### ISSUE TITLE
FDS+EVAC executed with MPI

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#8386] opened 2020-05-29 14:15 UTC
Hi all,

I have found another possible bug which should be investigated. I have generated a file for a FDS+EVAC simulation which I would like to run on FDS 6.7.0. I tried to run it using OpenMP and it works OK, but when I turn on OpenMPI I get the following exception:

![image](https://user-images.githubusercontent.com/7260681/83269497-7911e080-a1c7-11ea-8919-bbfdbe6498e4.png)

I made some more tests with FDS 6.7.4 and I got similar problems, so I don't think the version makes any difference. Now, I could also share with you the FDS file [I have been allowed by my clients] but only with NIST, so I need an email or something where I could send it.

Let me know and thanks for your great work!

**Comment by mcgratta** [comment] 2020-05-29 14:20
Rather than sending us the file, could you remove all features of the file that identify the particular application until you have a simple case that we can debug. The failure at line 215 in main.f90 indicates that this has something to do with the set up. It may not even be an Evac thing.

**Comment by rupole1185** [comment] 2020-05-29 14:28
Allright. I try to do my best to get the file you need. I just need a bit of time to simplify the FDS file.

**Comment by mcgratta** [comment] 2020-05-29 14:57
Yes, because that is what we would have to do, and you know more about it than we.

**Comment by rupole1185** [comment] 2020-05-29 15:38
This is a simplified version of the file. I preferred not to touch all the part that refers to EVAC because I suppose there you have the problem.

As I said, if you execute it using FDS 6.7.0 and 6.7.4 as:

fds FSE_SCN_A_COL_06.fds -> works OK
mpiexec -np 16 fds FSE_SCN_A_COL_06.fds -> failure

[FSE_SCN_A_COL_06.txt](https://github.com/firemodels/fds/files/4702747/FSE_SCN_A_COL_06.txt)

PS: I have also tried to use MPI_PROCESS and assign each mesh individually with no success ...

**Comment by mcgratta** [comment] 2020-05-29 16:06
This is a problem with the evacuation routines. 

Timo, in read.f90, I get this error:

```
   ! Find the first non-solid cell in the main evacuation mesh of this zone
   M => MESHES(NM_EVAC)
   EVAC_K_LOOP: DO K=1,M%KBAR
      EVAC_J_LOOP: DO J=1,M%JBAR
         EVAC_I_LOOP: DO I=1,M%IBAR
            IF (M%SOLID(M%CELL_INDEX(I,J,K))) CYCLE EVAC_I_LOOP   <--  Attempt to fetch from allocatable variable SOLID when it is not allocated
            P_ZONE(N)%X = M%XC(I)
            P_ZONE(N)%Y = M%YC(J)
            P_ZONE(N)%Z = M%ZC(K)
            EXIT EVAC_K_LOOP
         ENDDO EVAC_I_LOOP
      ENDDO EVAC_J_LOOP
   ENDDO EVAC_K_LOOP
```

**Comment by rupole1185** [comment] 2020-06-12 07:57
@mcgratta may I ask if there are updates on this issue? Will it be resolved and published on the next release of FDS in particular?

**Comment by rupole1185** [comment] 2020-06-16 11:53
Hi @mcgratta . Sorry for being annoying. I wonder if you have news about this topic. In case not: is there a workaround that I can apply to the fds file which allows me to use the MPI with the current version of fds?

**Comment by rmcdermo** [comment] 2020-06-16 11:58
@gjaeger @godisreal 

Please have a look at this.  We have been discussing maintenance of FDS+Evac.  This is exactly the time we need you to help.  Thanks

**Comment by gjaeger** [comment] 2020-06-16 13:07
@rmcdermo I'll look at it.

**Comment by rmcdermo** [comment] 2020-06-16 13:12
Thanks!

**Comment by gjaeger** [comment] 2020-06-16 14:08
> This is a simplified version of the file. I preferred not to touch all the part that refers to EVAC because I suppose there you have the problem.

More than 1500 lines... a simplified version 😉  

Let's get started:

> `fds FSE_SCN_A_COL_06.fds` -> works OK

I'm not suprised. 18 fire meshes and 4 evac meshes run on one process.

> `mpiexec -np 16 fds FSE_SCN_A_COL_06.fds` -> failure

I'm not suprised. You spread 22 meshes over 16 processes. These are 1.3 meshes for each process. 

_Remember:_
All evacuation meshes have to put to the last process (or “thread”) for a MPI run and all evacuation meshes should be defined in the input file after the fire meshes (see FDS+Evac User's Guide, page 109, February 12, 2018).

> PS: I have also tried to use MPI_PROCESS and assign each mesh individually with no success.

@rupole1185 Can you post the lines with the MESH definitions (with MPI_PROCESS) and the entire error message?

I also found a few things in the `PERS` definition that are not pretty:
- In `PERS ID = 'globals'` the setting `DEFAULT_PROPERTIES` was forgotten.
- In `PERS ID = 'ADULTI'`, the setting was ended prematurely by comments. Not all settings are made.

I didn't go any deeper.

**Comment by mcgratta** [comment] 2020-06-16 14:16
I run into trouble when running the case with 19 MPI processes. 18 processes for the fire meshes, and 1 for the evac. The problem is in the set up, but I cannot figure out how to solve it because I am unfamiliar with this part of the code. Timo has answered a few posts today, so we need him to look at this.

**Comment by rupole1185** [comment] 2020-06-16 14:20
Hi all. I run the simulation in multiple configurations:

1) Using MPI with the settings of the FDS file
2) Only with MP
3) Using MPI with all EVAC meshes gathered into a single process

Every time I used MPI I got the error pasted in the image above (https://user-images.githubusercontent.com/7260681/83269497-7911e080-a1c7-11ea-8919-bbfdbe6498e4.png).

I know there might be problem in the settings, but I wonder then: why is it running on a single process?

**Comment by mcgratta** [comment] 2020-06-16 14:25
The case runs for a single process because the single process has access to information about all the meshes. When run in parallel, information about meshes and obstructions is stored by each process and not shared by default. The line of code that fails is one in which one MPI process is trying to access information about another mesh that has not been shared with it. This is the usual reason for failure of jobs running with multiple MPI processes.

**Comment by gjaeger** [comment] 2020-06-16 14:54
Kevin wrote:
> The problem is in the set up, but I cannot figure out how to solve it ...

It's the same for me. Therefore I use a simple and well-known example.

@rupole1185 Can you start the example [evac_example2a.fds](https://github.com/firemodels/fds/files/4787282/evac_example2a.zip) with the command 
`mpiexec -np 2 fds evac_example2a.fds`?

If it works, we can go back to your file.

**Comment by rupole1185** [comment] 2020-06-16 15:01
Hi @gjaeger ,

I can run the file evac_example2a.fds easily on my machine using MPI. I used FDS 6.7.0 but I can try also on FDS 6.7.4. [I mean that it works correctly]

PS: if you want I can also give you the script I use to lauch the analysis (https://github.com/CFD-FEA-SERVICE/CloudHPC/blob/master/scripts/fds6.7.4)

**Comment by gjaeger** [comment] 2020-06-17 15:08
I tried to find the error. The calculation with `&MISC NO_EVACUATION=.TRUE.` works with and without MPI. With `&MISC NO_EVACUATION=.FALSE.` and `EVACUATION_MC_MODE = .TRUE.` works without MPI. An MPI calculation with a large fire mesh (enveloping the evac meshes) on one process and the evac meshs on another one, works too. 

I can't explain it. Very mysterious.

**Comment by marcosvanella** [comment] 2020-06-17 15:25
Hi Gregor, have you tried running your tests in debug mode? Might be that there is a memory corruption issue not being picked up, which is giving mysterious outcomes.

**Comment by godisreal** [comment] 2020-06-18 21:18
> I tried to find the error. The calculation with `&MISC NO_EVACUATION=.TRUE.` works with and without MPI. With `&MISC NO_EVACUATION=.FALSE.` and `EVACUATION_MC_MODE = .TRUE.` works without MPI. An MPI calculation with a large fire mesh (enveloping the evac meshes) on one process and the evac meshs on another one, works too.
> 
> I can't explain it. Very mysterious.

OK. The evac code was initially written for single process.  An important issue is whether the evac example can be run through in EVACUATION_MC_MODE=.TRUE.  If so, you can always run through the whole example by two steps.  

From the user side, users do not need to run fds and evac together, especially for large-scale examples.  fds requires much computational time while evac does not.  In fact evac simulation can run very fast when there is no fire computation.  So I suggest that users first run fire simulation with MPI and then run evac simulation with EVACUATION_MC_MODE=.TRUE. without MPI, and this method will be an easy solution, and it will not increase much computational time.   

In fact evac module itself runs well without MPI.  So please also consider Randy's suggestion of outsourcing evac as an independent component.  That's a feasible way.  If so, there will be no such MPI problem any more.

**Comment by mcgratta** [comment] 2020-06-18 21:22
There is no mystery here. This is a simple bug as I have explained above. Timo K must address it. I cannot.

**Comment by rupole1185** [comment] 2020-06-18 21:23
Hi @godisreal ,

thanks for you feedback. I can try to run it as you mentioned using a bash script for the moment.

One question [maybe stupid, in case sorry]: EVAC and FDS do not communicate each other during the analysis? Will evacuation be dependent on the fire evolution or not?

**Comment by godisreal** [comment] 2020-06-19 04:05
@rupole1185
If you set EVACUATION_MC_MODE=.TRUE., EVAC read in FDS output data and run evacuation simulation.  Such evacuation simulaiton depends on the fire output in your last run.  The result is the same as you run EVAC and FDS together.  Because the fire simulation is not repeated in EVACUATION_MC_MODE=.TRUE., the evac run can be really fast in this mode.  Please refer to FDS+Evac User Guide for details (Section 8.4 The MISC Namelist Group).

Usually EVAC users run fire+evac together in the first run, and then run multiple evac simulation with EVACUATION_MC_MODE=.TRUE.  Since you have reported this bug, a temperory solution is that you first run fire simulation without evac part (NO_EVACUATION=.TRUE.), and then run multiple evac simulation (EVACUATION_MC_MODE=.TRUE.).  Please let me know if this two-step solution works well for your case.

**Comment by godisreal** [comment] 2020-06-19 04:42
Based on Kevin's message, it seems that there is a bug with read.f90 in the following commit. 
https://github.com/firemodels/fds/commit/f171471a17538fb89aa5425ba2f18884e53258c8
So I suppose the problem does not exist in any version before that commit.   Since nobody has reported similar problems before, the problem does not exist in Version 6.7.0.  This is probably why rupole1185 can run through an example by using 6.7.0.  

Also, a simple solution is reversing the above commit in read.f90.  However, I think Timo has a reason for the above commit.  So I agree that it is better to wait for Timo's response first.

**Comment by gjaeger** [comment] 2020-06-19 10:29
@mcgratta I used the term "mysterious" in reference to my efforts to find a workaround under the given conditions. I was hoping to find a solution for the special inputfile (like issue #7744). This could be used until the bug is solved. I join the queue of those waiting.

@marcosvanella I'm working on my skills. 😉 I hope to solve these simple bugs myself soon.

**Comment by tkorhon1** [comment] 2020-06-26 10:39
Well, I just download the  case. Well, I have commented this already, probably in FDS-SMV discussion group. 
I will put this running in our Linux cluster. Yes, I got error, when usinm mpirun -np 19:

FDS version (Linux machine):
Current Date     : June 26, 2020  13:23:56
 Revision         : FDS6.7.4-780-gea81a380f-master
 Revision Date    : Sun Jun 21 12:50:51 2020 -0400
 Compiler         : Intel ifort 18.0.1
 Compilation Date : Jun 26, 2020  13:14:44

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source      
fds_mpi_intel_lin  0000000006AA41DD  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B5260147630  Unknown               Unknown  Unknown
fds_mpi_intel_lin  000000000082B587  read_input_mp_rea       12164  read.f90
fds_mpi_intel_lin  00000000007CB28B  read_input_mp_rea         113  read.f90
fds_mpi_intel_lin  000000000091D81C  MAIN__                    117  main.f90
fds_mpi_intel_lin  000000000040F01E  Unknown               Unknown  Unknown
libc-2.17.so       00002B526123A555  __libc_start_main     Unknown  Unknown
fds_mpi_intel_lin  000000000040EF29  Unknown               Unknown  Unknown

The source part 
! Find the first non-solid cell in the main evacuation mesh of this zone
   M => MESHES(NM_EVAC)
   EVAC_K_LOOP: DO K=1,M%KBAR
      EVAC_J_LOOP: DO J=1,M%JBAR
         EVAC_I_LOOP: DO I=1,M%IBAR
            IF (M%SOLID(M%CELL_INDEX(I,J,K))) CYCLE EVAC_I_LOOP   <--  Attempt to fetch from allocatable variable SOLID when it is not allocated
            P_ZONE(N)%X = M%XC(I)
            P_ZONE(N)%Y = M%YC(J)
            P_ZONE(N)%Z = M%ZC(K)
            EXIT EVAC_K_LOOP
         ENDDO EVAC_I_LOOP
      ENDDO EVAC_J_LOOP
   ENDDO EVAC_K_LOOP
that Kevin pointed out  is doing the zones for each door/exit on the evacuation meshes, or something like that. It seems that this is working for a serial run, but MPI run is not working for this specific input file. I'll do this some time during my holidays (June). Right now I have some trouble to see the files on our Linux cluster using laptop (I should use scp to copy the files and use "command line emacs" to edit files in Linux cluster. That is not very nice.

Well, I check this sometime during my holidays. Something strange here, because I run my test cases also using MPI always, there are cases, where I have 2 fire meshes and 2 evacuation meshes and mpirun -np 3 is used.

**Comment by tkorhon1** [comment] 2020-06-26 10:44
Well, I'll attach my simple test cases that I promised to send to Gregor few months ago. There is:

${MPI_DIR}/mpirun -bind-to none -np 3 ${FDS_EXE} evac_simple_test_4.fds > evac_simple_test_4.err 2>&1

And 2 fire meshes and 2 evacuation meshes. And this is running nicely using MPI (at least a week ago, when I last run it)
[GitHub_VerificationCases.zip](https://github.com/firemodels/fds/files/4836479/GitHub_VerificationCases.zip)

**Comment by tkorhon1** [comment] 2020-06-26 11:21
Well, I did not yet found anything. The simple test case is running, it does not stop there and no warnigs when using the _db executable. So, the FSE... input file has something that makes it a case that I have not found before. Something with the ZONEs, perhaps.

**Comment by godisreal** [comment] 2020-06-26 16:18
@rmcdermo
Let us talk about the idea with Timo.  I read some source code recently and think again about your suggestion.  I become more and more interested in outsourcing evac as an independent execuable.  I think the suggestion is feasible. FDS is under development whereas EVAC almost stops there.  So it is reasonable to prepare a backup solution to a problem like this issue.  
Technically it is not too difficult to separate evac from fds in source code, but it is a little tedious task.  Perhaps Timo has ever thought about this method as an easy solution to many unexpected problems.  So he developed EVACUATION_MC_MODE to partly decouple execuation of FDS and EVAC.  From there we can move further to generate an independent execuable to only run evac simulation.  As a result, the source code of FDS and EVAC are no longer twisted with each other, and this will be a systematic solution in a long term.  
Here I am glad to hear about Timo's opinion.  I hope Timo will also support your suggestion.

**Comment by rmcdermo** [comment] 2020-06-26 21:19
@godisreal I am warming up to the idea of an independent Evac module.  I think it could take some initial surgery, but could have many benefits long-term.  Let's see what @tkorhon1 says and also others interested in this project.

**Comment by tkorhon1** [comment] 2020-08-03 12:27
I did some test (I had a summer vacation, now back at home office) . It seems that one can just remove those lines

! Find the first non-solid cell in the main evacuation mesh of this zone
M => MESHES(NM_EVAC)
EVAC_K_LOOP: DO K=1,M%KBAR
EVAC_J_LOOP: DO J=1,M%JBAR
EVAC_I_LOOP: DO I=1,M%IBAR
IF (M%SOLID(M%CELL_INDEX(I,J,K))) CYCLE EVAC_I_LOOP <-- Attempt to fetch from allocatable variable SOLID when it is not allocated
P_ZONE(N)%X = M%XC(I)
P_ZONE(N)%Y = M%YC(J)
P_ZONE(N)%Z = M%ZC(K)
EXIT EVAC_K_LOOP
ENDDO EVAC_I_LOOP
ENDDO EVAC_J_LOOP
ENDDO EVAC_K_LOOP

They are not anymore used by the evacuation flow field calculation. Now the flow fields are separately calculated for each DOOR/EXIT and the evacuation pressure zones are (re)defined there for each door/exit flow field calculation. I.e., there the door/exit line XB is used to find the empty space in front of the door => the zone definition is started from there.

I just finnished my evacuation V&V suite calculation with this modification and things seem to be nice. But I just check that the calculatin did finnish nicely (STOP: FDS completed successfully). I did not yet do the SMV figures and Excel-based graphs etc. data processing.

**Comment by tkorhon1** [comment] 2020-08-03 12:36
Well, the above lines (zone loop for evacuation) was programmed well before than the 

            DO NOM=LOWER_MESH_INDEX,UPPER_MESH_INDEX

stuff was introduced. So, things are not working, when there is really many meshes. My test cases do not have very many meshes. Mäybe I should generate a one.

Kevin/Randy: How many meshes there should be, before the LOWER_MESH_INDEX,UPPER_MESH_INDEX stuff has something to do? I plan make just simple case: a long domain with open boundaries and divided to many meshes, say, in the x direction. I use just minimal number of IJK for the meshes. Does it matter, if the meshes are grouped together to same processes? Is the  LOWER_MESH_INDEX,UPPER_MESH_INDEX still the same? Or should the meshes have their own processes? If so, how one can use more processes than there are (logical) cores on a machine, (i.e., whan "mpirun command line" should one use?

**Comment by rmcdermo** [comment] 2020-08-03 12:50
@tkorhon1 In read.f90 you find
```
IF (MYID==CURRENT_MPI_PROCESS) THEN
   LOWER_MESH_INDEX = MIN(LOWER_MESH_INDEX,NM)
   UPPER_MESH_INDEX = MAX(UPPER_MESH_INDEX,NM)
ENDIF
```
All the usual rules apply for meshes and processes---you cannot oversubscribe processes (N procs <= N meshes).

**Comment by godisreal** [comment] 2020-10-01 11:40
Excuse me.  Why pressure zones are defined for evacuation flow field (eff) in fds6?  It seems that such pressure zones are not defined for eff in fds5.  Is it due to VENTs placed for eff in fds5?

**Comment by gjaeger** [comment] 2020-10-01 12:07
Dear Peng, 

what do you mean with 
> Why pressure zones are defined for evacuation flow field (eff) in fds6?

Do you relate your question to an example or a part of the source code? I don't understand the background of your question.

**Comment by godisreal** [comment] 2020-10-04 15:04
Dear Gregor.  Thanks for your reply.  Please compare READ_ZONE in fds5 and fds6, and you will find the difference.  My question refers to why such pressure zones are required for evac flow computation in fds6.  If users attach a vent with each door and exit, I suppose a flow field is obtained for evac computation.  Then I wonder how the pressure zones affect the evac flow field (eff).    

Suppose a user defines one main evacuation mesh with three exits.  There will be three eff calculation to give three evac flow fields.  These flow fields guide agents towards three exits, respectively.  In fds6 I understand each evac flow field calculation has just one exit/door, i.e., outflow vent, but I do not get why pressure zone is defined so that the front of the door is in the pressure zone and why there is no such zones in fds5.  More importantly, how do such pressure zones change the velocity field toward the door or exit?  If I understand evac algorithm correctly, only the velocity field is currently used for evac module, or more specifically only the direction of velocity in evac flow field (eff) is used for evac computation.  Thus, does the pressure zone change any direction of velocity in evac flow field (eff)?

**Comment by gjaeger** [comment] 2020-10-09 10:42
@tkorhon1 Timo, Does your pull request #8808 solve this issue? Can we close it?

@godisreal Peng, Do we want to continue this discussion in the [Discussion Forum](https://groups.google.com/forum/?fromgroups#!forum/fds-smv)?

**Comment by godisreal** [comment] 2020-10-12 14:04
@gjaeger Do you think it is more proper to discuss Fortran code and algorithm in google list?  I don't get your point.  As you requested, I have explained more details of my question.  So if you want to discuss or answer my question, I suppose you will first answer here.  Thanks.

**Comment by tkorhon1** [comment] 2021-04-23 12:28
Well, this can be closed. Things are now working (forthcoming fds 6.7.6) so that there are only fire meshes or only evacuation meshes in the fds.exe execution (depending on the input keywords). And the evacuation meshes are done in a single process. And later this separation of fire and evacuation mesh calculations is going to be separated more.

Note: Now there is no general evacuation guiding flow field, where all doors/exits suck "air". Calculation is done separately for each door/exit. And at each door/exit calculation phase, a point in front of the door/exit XB is taken as the XYZ of a pressure zone and the (fire) pressure zone definition routines are used to calculate the "evacuation zone" of this door.

TimoK

**Closed as completed by tkorhon1** 2021-04-23 12:28 UTC
