### ISSUE TITLE
Intel & Gnu: Restart fails when having particles in the input file

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5628] opened 2017-10-26 18:37 UTC
To reproduce the issue:
Get the device_test.fds file from the Verification/Controls/ directory.
Restart fails after 2 or 3 trials.

**Comment by sbenkorichi** [comment] 2017-10-26 20:30
@marcosvanella 
I should have submitted them here. Here are the two cases:

Gnu:
```
$ /home/salah/firemodels/fds/Build/mpi_gnu_linux_64/fds_mpi_gnu_linux_64 device_test.fds 
 Mesh 1 is assigned to MPI Process 0
 Mesh 2 is assigned to MPI Process 0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : October 26, 2017  21:26:42
 Version          : FDS 6.5.3
 Revision         : FDS6.6.0-48-g0b69ca2-dirty-master
 Revision Date    : Wed Oct 25 16:39:30 2017 -0400
 Compiler         : Gnu gfortran 7.2.0-1ubuntu1~16.04)
 Compilation Date : Oct 26, 2017  19:16:19

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Open MPI v3.0.0, package: Open MPI salah@sbenkorichi Distribution, ident: 3.0.0, repo rev: v3.0.0, Sep 12, 2017

 Job TITLE        : Test sprinklers, heat detectors and smoke detectors
 Job ID string    : device_test

At line 2847 of file ../../Source/part.f90
Fortran runtime error: Index '0' of dimension 1 of array 'lagrangian_particle_class' below lower bound of 1
```

Intel:
```
forrtl: severe (408): fort: (3): Subscript #1 of the array LAGRANGIAN_PARTICLE_CLASS has value 0 which is less than the lower bound of 1

Image              PC                Routine            Line        Source             
fds_mpi_intel_lin  0000000008DECF96  Unknown               Unknown  Unknown
fds_mpi_intel_lin  00000000022D3FDD  part_mp_remove_pa        2847  part.f90
fds_mpi_intel_lin  0000000002262037  part_mp_move_part        1658  part.f90
fds_mpi_intel_lin  000000000223FE16  part_mp_update_pa        1220  part.f90
fds_mpi_intel_lin  0000000003434476  MAIN__                    688  main.f90
fds_mpi_intel_lin  000000000040DD1E  Unknown               Unknown  Unknown
libc-2.23.so       00002AB2A0ABF830  __libc_start_main     Unknown  Unknown
fds_mpi_intel_lin  000000000040DC39  Unknown               Unknown  Unknown
```

**Comment by sbenkorichi** [comment] 2017-10-26 21:18
This keeps happening with lagrangian particles, we had this before, and some fixes were done,
here are some references:
https://github.com/firemodels/fds/issues/4884 and https://github.com/firemodels/fds/issues/4770

**Comment by marcosvanella** [comment] 2017-10-26 22:13
Salah do an update on the code and let me know if you can link the gnu targets to the Intel MKL library. I did it in my Ubuntu Linux with the free downloadable MKL from Intel.
You will have to add these lines in your ~/.bashrc:

```
# MKL Environment Variables:
export INTEL_COMPILERS_AND_LIBS=/opt/intel/compilers_and_libraries_2017/linux
source $INTEL_COMPILERS_AND_LIBS/mkl/bin/mklvars.sh intel64
```
assuming you are using intel17. Check that the verification case:

`YOURFORK/fds/Verification/Pressure_Solver/duct_flow_glmat.fds`

runs correctly.

**Comment by marcosvanella** [comment] 2017-10-26 22:14
Sorry wrong button.

**Comment by sbenkorichi** [comment] 2017-10-26 22:15
Yea I saw your commit. I will let you know tomorrow morning.

**Comment by marcosvanella** [comment] 2017-10-26 22:17
The -O2 is a change suggested by Randy. Somehow -O3 has given trouble in the past.

**Comment by sbenkorichi** [comment] 2017-10-26 22:25
Yea but that was with gfortran 4. We are at 7, the issue I noticed is regarding floating points once the run finishes you get certain warning. I believe we should go with O3 if there are issues, it's better we address them at least for the long run not necessarily by tomorrow, just to ensure better Quality in the code, especially when it comes to run time. You get people who still stuck with fds5 for what?  For less run time.

**Comment by sbenkorichi** [comment] 2017-10-27 19:21
@mcgratta 
Kevin, this is the thread that I opened for that case. Please read the above description of the two errors.
The case run successfully under both compilers. It only fails when I use the restart 2 or 3 times.

**Comment by mcgratta** [comment] 2017-10-30 21:10
Commit #5650 does not fix the bug, but it was an error.

**Comment by sbenkorichi** [comment] 2017-10-30 21:11
Ok. Let me know when you think it's fixed.

**Comment by mcgratta** [comment] 2017-10-31 13:26
This is the simplest case that exhibits the seg fault after 2 or 3 restarts:
```
&HEAD CHID='junk' /

&MISC RESTART=.TRUE. /

&MESH IJK=30,10,10, XB=0.0,3.0,0.0,1.0,0.0,1.0 /
&MESH IJK=10,40,10, XB=3.0,4.0,0.0,4.0,0.0,1.0 /

&TIME T_END=60. /

&SURF ID='BLOW', VEL=-2., PART_ID='smoke', DT_INSERT=0.05 /
&VENT XB=3.0,4.0,4.0,4.0,0.0,1.0, SURF_ID='OPEN' /
&VENT XB=0.6,1.0,0.3,0.7,0.0,0.0, SURF_ID='BLOW' /

&PART ID='smoke', MASSLESS=.TRUE., SAMPLING_FACTOR=1 /

&TAIL /
```
The error is caused by two particles sharing the same storage space in memory, but  I have not yet determined how this case happen. It is related to the transfer of a particle from one mesh to another, and the reordering of memory that occurs when this happens.

**Comment by sbenkorichi** [comment] 2017-10-31 14:51
Nice finding. 
My suggestion is we should first tackle this issue by just using single mesh, then we can check for multiple meshes. You can use 1st &MESH line and you still be able to reproduce the error. This might give you more insight to the root of the bug.

**Comment by mcgratta** [comment] 2017-10-31 15:07
I know exactly where it is failing, and I'm close to figuring out why. It just takes time. It is related to the reorganization of storage space when a particle crosses from one mesh to another.

**Comment by mcgratta** [comment] 2017-11-20 21:43
This bug should be fixed now.

**Closed as completed by mcgratta** 2017-11-20 21:43 UTC

**Comment by sbenkorichi** [comment] 2017-11-21 15:07
Ok,
confirmed from both compilers.

**Comment by Er9y714** [comment] 2017-12-05 19:51
I have (had) an ongoing calculation that I had started with FDS 6.5.3. It consists stationary particles. 
At the moment I cannot restart and I wonder if it is due to these particles. 

Do you think it is possible to restart the calculation with this fixed FDS version? If so, is it possible to get a compiled version of 6.5.x includes this fix? Because I cannot restart it with 6.6.0. 

ps. particles in the model can be discarded in order to save the calculation and continue to run. 

Thank you.

**Comment by sbenkorichi** [comment] 2017-12-05 19:58
I doubt it, the fix is only valid for the current code not even for 6.6.0. It's really pointless for us to go back and maintain previous releases. I believe this bug will be fixed for the coming release. For now, it's better to avoid restart using particles. 6.6.0 can do restart with particles but only once or twice, can't go beyond that. As for 6.5.3 we already had those issues reported which with made the improvement into 6.6.0. 
Or, you can compile the current code and you won't have these issues if it's so urgent.

**Comment by Er9y714** [comment] 2017-12-05 20:03
Thank you for the reply. 
As for the suggestion, 
6.6.0 version gives an error  (input statement requires too much data), whereas 6.5.3 gives "program violation ..." error. I assumed 6.6.0 is not compatible to use in 6.5.3 cases. 

Do you think if I compile the current code (will be 6.6.x) then I can use it in my case?

**Comment by sbenkorichi** [comment] 2017-12-05 20:09
Nah, if 6.6.0 isn't then the current wont. The reason is we're constantly improving the code, and many fixes are done and improvements as well. You can compile the current code and run the case, but then has to fix your input file to run as what 6.6.0 is constructed. I give you an example of the Wind, you can't run case of 6.5.3 with the current code since the code has changed the way how it's structured. Two options:
1. Just run the case with 6.5.3 without changing the code and don't use the restart.
2. compile the latest code and adjust the inputfile to suit the 6.6.0 case, you can use restart (and again not everything is guaranteed, maybe it might not handled, if your case is special).
It's always recommended to use the latest release as many bugs were fixed and improvements were done.

**Comment by Er9y714** [comment] 2017-12-05 20:13
There is not any line that is not compatible with 6.6.0. I also do not intend to change the code. I have to restart because it was unintentionally interrupted. 

I have never compiled any exe. I will follow the wiki, hopefully manage somehow. 
Thank you for the hope.

  https://github.com/firemodels/fds/wiki/FDS-Compilation

**Comment by Er9y714** [comment] 2017-12-05 20:41
Intel compiler seems to be not free and more than 3GByte. 
@sbenkorichi do you happen to have a recently compiled version? This would save me a huge amount of time. I would like to try 6.6.0 with the part fix. Maybe you could share with googledrive?

**Comment by sbenkorichi** [comment] 2017-12-05 20:49
Intel is commercial package. Gnu is free open source. 

Ok, I've just gave it a try, it won't work with the latest code. The reason is because as Kevin said, the issue is due to storage recognition, so after the way 6.6.0 and before, they do it differently then the current code. So, after you receive the error it's not possible to restore it. The current code will be helpfully only if you run the case from zero, then you can restart later, as if you run it while it's already thrown an error from previous releases it wont help. --Therefore, I don't see a point for you to compile.

**Comment by sbenkorichi** [comment] 2017-12-05 20:54
This error should be similar to what you received with 6.6.0. 
`forrtl: severe (67): input statement requires too much data, unit 19, file /home/salah/A-fds-example/particles/junk_0001.restart`

**Comment by Er9y714** [comment] 2017-12-05 20:56
Yes, it is the same error. 

Thanks for clarifying 6.6.0 will not help my case. That saved me spending time for compiling as well.

The reason I tried to install Intel compiler is that the wiki preliminaries page. I misunderstood the bullet points. I thought the third point about GNU is third step, instead of an alternative to Intel compiler. 

I will now quit my task recovering this calculation. 
Thank you
Have a nice day.

**Comment by sbenkorichi** [comment] 2017-12-05 21:03
Well, don't have much experience with FDS compilation under Windows. And usually, the guys are using Intel when it comes to Windows.
