### ISSUE TITLE
HVAC and pressure oscillations, tiny DT does things bad

### ISSUE THREAD

**Issue by tkorhon1** [firemodels/fds#7116] opened 2019-01-22 08:56 UTC
Hi Jason, 

This Issue is a branch of the Issue 7040. Randy thought that it would be a good idea to start a new issue for the HVAC stuff. So, I'll copy-and-paste here something from the Issue 7040.

If the Figures and other links do not work, you can find them in Issue 7040. My test case geometry is very simple. It is 3m long tube, the +x end is blocked, the -x end is open to a small volume where there are an OPEN boundary condition. The HVAC case has a HVAC connecting the tube to this small volume. The case without HVAC, did run "nicely" using a tiny DT. But the HVAC case did not.

Issue 7040:

Well, I did some more tests using the simple tube case, same as above. And I set CHECK_HT=T. But this did not help. I was already using DT=0.xxxx so small, that check_ht did not make the time step smaller in "my best, i.e., smallest dt, cases.

Anyway, below are figures for the flows, densities and pressures fo the cases:
Tube, one side opens directly to a small volume, where is an OPEN boundary

    DT= 0.01s, 0.002 s, and 0.0001 s
    Tube, one side has HVAC duct to a small volume, where is an OPEN boundary
    DT= 0.02 s, 0.001 s, and 0.0001 s

The plain open tube (without any HVAC) is not too bad. But there is pressure (and flow)
oscillations. But these are more or less same with different DT.

The havc tube case is bad. The DT behaviour is odd. The DT=0.001 s seems to work
reasonably, but the smaller DT=0.0001s is really bad.

I attach the input files (I used the same files, just changing DT accordingly)

hot_tube_duct_v1B3NEW3.txt
hot_tube_open_v1B3NEW3.txt

And here are the results:

hvacduct_dt_0p0001s_denspres
hvacduct_dt_0p0001s_flows
hvacduct_dt_0p001s_denspres
hvacduct_dt_0p001s_flows
hvacduct_dt_0p01s_denspres
hvacduct_dt_0p01s_flows
openduct_dt_0p0001s_flows
openduct_dt_0p0001s_rhopres
openduct_dt_0p01s_flows
openduct_dt_0p01s_rhopres
openduct_dt_0p002s_flows
openduct_dt_0p002s_rhopres

Fire Dynamics Simulator

Current Date : January 15, 2019 15:16:02
Revision : FDS6.7.1-85-g889eccd69
Revision Date : Sat Jan 12 15:17:48 2019 -0500
Compiler : Intel ifort 18.0.1
Compilation Date : Jan 15, 2019 12:56:24

MPI Enabled; Number of MPI Processes: 1
OpenMP Enabled; Number of OpenMP Threads: 1

MPI version: 3.1
MPI library version: Open MPI v2.1.3, package: Open MPI tstopi@espvm5m030.ad.vtt.fi Distribution, ident: 2.1.3, repo rev: v2.1.2-129-gcfd8f3f, Mar 13, 2018

Job TITLE : ISO furnace a tiny and fast model
Job ID string : hot_tube_open_v1B3NEW3

   Time Step  609900   January 15, 2019  17:53:17
   Step Size:    0.100E-03 s, Total Time:      59.99 s
   Pressure Iterations:      1
   Maximum Velocity Error:  0.73E-06 on Mesh   1 at (   4   6   4)
   Maximum Pressure Error:  0.66E+02 on Mesh   1 at (  64   4   4)
   ---------------------------------------------------------------
   Max CFL number:  0.40E-01 at (   4,   5,   4)
   Max divergence:  0.30E-01 at (   2,   6,   4)
   Min divergence: -0.77E-01 at (   2,   4,   4)
   Max VN number:   0.61E-04 at (   3,   5,   5)

   Time Step  610000   January 15, 2019  17:53:19
   Step Size:    0.100E-03 s, Total Time:      60.00 s
   Pressure Iterations:      1
   Maximum Velocity Error:  0.44E-06 on Mesh   1 at (   4   6   4)
   Maximum Pressure Error:  0.13E+03 on Mesh   1 at (  64   4   5)
   ---------------------------------------------------------------
   Max CFL number:  0.38E-01 at (   4,   5,   4)
   Max divergence:  0.29E-01 at (   2,   6,   4)
   Min divergence: -0.75E-01 at (   2,   4,   4)
   Max VN number:   0.56E-04 at (   2,   5,   5)

Time Stepping Wall Clock Time (s): 9436.691
Total Elapsed Wall Clock Time (s): 9441.909

STOP: FDS completed successfully (CHID: hot_tube_open_v1B3NEW3)

Well, I'm not sure about the revision string, I updated my source on Tuesday, so
it had Kevin's fix for the tmp_front boundary in wall.f90. I compile on our Linux
cluster, but my Git is on my laptop. So, I change the revision string manually in
the makefile that is in Linux.

Timo

**Comment by drjfloyd** [comment] 2019-01-22 12:55
I'll take a look; however, I'll note this isn't the application the HVAC model was designed for. The model was designed for building HVAC systems. The flow rates in those systems are generally low with respect to the room volumes, and the room boundary area occupied by vents is typically a small fraction of the wall area. The HVAC pressure solver and the FDS pressure solver are not directly coupled.

**Comment by drjfloyd** [comment] 2019-01-22 20:36
With one end of the tube open the background pressure in the tube can't change.  The HVAC model takes the pressures at the start of the timestep and predicts the duct flow based on estimated end of timestep pressures. Since the HVAC VENT is the entire end of the duct, small pressure changes mean large volume flows in relation to the compartment size. Since the end is OPEN, the HVAC model can't predict the fact that the pressure will drop in the tube as outflow occurs. I don't think this is a favorable geometry for using HVAC on the tube end.

**Comment by tkorhon1** [comment] 2019-02-11 11:25
Ok, I can survive with the current source code. I will make my simple ISO furnace model such that this is not a problem. So, I use smaller h_coeff for the furnace walls. The air is heated a little bit slower, but this does not matter much. It is close to the ISO 384 curve enough. And this is showing up just in the beginning of the simulation, first hundreds of seconds only, when the ISO curve is rapidly rising. Later the temperature is not rising so fast and a smaller h_coeff makes the air to be close enough to the ISO temperature.

Actually, I did not have any ducts to amb in the ISO furnace model. I had HVACs that stirred the air inside the simple model: suck from left => blow right, and an another pair suck from right => blow left. These had a fan inside the HVAC ducts. So, I simplified the case a really much => the simple tube with one end open and linear temperature rise of tube walls. But my ISO furnace started to work better, when Kevin fixed the specified temperature boundary condition. I had zone leak on all heated walls, so things were going badly with the old fixed temperature boundary condition.

I will chekc the DT issue using my simple ISO furnace geometry with the HVAC stirrers. If I have there similar result, that the tiny DT makes things bad, I'll report.  In this geometry, the HVAC vents are not too large compared to the wall area. And the pressure relaxation is dealed with zone leakage.

I was two weeks out of office. I and my kids had flu. I'm nowadays a single parent of three under school age children, so I do not have any spare time. Lucily, I need a ISO furnace model in one of the projects that we do at work, so I can spend some time for this issue (and the other pressure oscillation issue).

Timo

**Comment by obscureed** [comment] 2020-02-12 10:50
One potentially relevant comment:
You can run into trouble if you specify 
`&TIME T_END=100, DT=0.002`
or any other small timestep that is an exact multiple of T_END.

The trouble is that after 50000 timesteps (in the example above), it is possible that time has reached (T_END-tiny), and so FDS does a final timestep of size tiny. (The example is a real one, which resulted in timestep 50001 of size 0.5e-10s.) A tiny timestep can obviously result in some wild behaviour -- something somewhere is divided by DT and it never recovers. So then if you look at a slice of pressure, you may see an enormous range of values and conclude that DT=0.002 is very bad. In fact, the enormous range is needed only because of the final timestep; running with DT=0.002001 or DT=0.001999 would be very different.

Should I report this as a bug?

**Comment by mcgratta** [comment] 2020-04-06 18:51
Should we close this issue?

**Comment by rmcdermo** [comment] 2020-04-06 18:55
obscureed's comment has been dealt with.  The issues with convergence in tunnels remain, of which this is one example.  I'm fine to close if others are, as I believe the central issue is still in my assignments.

**Closed as completed** 2020-04-06 21:26 UTC
