### ISSUE TITLE
Getting Different Results for the same Input File - FDS v.6.3.2 

### ISSUE THREAD

**Issue by DineshMyilsamy** [firemodels/fds#3398] opened 2016-01-26 06:15 UTC
Dear Sir,
     I am Dinesh Myilsamy, currently I am working on a project which is based on compartment fire in an under ventilated condition.

OUTLINE OF MY RESEARCH:

```
Hot unburnt fuel mixtures (at 373 K)  will be present inside a closed compartment and there is an ignition source which is kept at one of the compartment  (Temp. 1500 k at its top surface), when the compartment window is opened the atmospheric air will get into the compartment due to the density difference. Fresh air will start to move inside the compartment and it will reach to the ignition source which is kept at other end of the compartment (opposite to window). 
```

 When the fresh air reacts with the unburnt fuel in the presence of ignition source  there will be a rapid flame propagation (BACKDRAFT) inside the compartment with and it moves out of the compartment as a fireball.

![picture1](https://cloud.githubusercontent.com/assets/16892714/12573429/5d23d9f4-c43c-11e5-8081-b44e583171af.png)

```
          This has to be carried out using LES Turbulence Model and EDC as a combustion Model.
```

MY ISSUES.

```
        1.  For my simulation I am using FDS v.6.3.2 in an  Intel Core 2 E8400, 3.0 GHz, 32 Core Cluster. - Linux Operating system.

         I am getting two different solutions when I tried to simulate my  FDS input file. 

         I did not even change a single letter in my FDS file, I used the same computer, using 15 Cores. but I found a two different solution. 
```

![press](https://cloud.githubusercontent.com/assets/16892714/12573465/d3a96f12-c43c-11e5-9ef9-52177027babc.png)

```
       2.  To resolve this problem I got a guidance from FDS google group. In that they adviced me to use   NOISE =.FALSE.

          I have tried by specifying NOISE=.FALSE,  NOISE_VELOCITY = 0.005 but the problem didn't get resolved
```

![noise_005](https://cloud.githubusercontent.com/assets/16892714/12573614/5ae504cc-c43e-11e5-821f-4a141a9dd49e.png)

My input parameters

MISC PARAMETERS

& MISC TMPA=25.0, DNS=.FALSE., NOISE=.FALSE., NOISE_VELOCITY=0.005, SUPPRESSION=.FALSE. /
& RADI RADIATION=.TRUE./

REAC PARAMETERS

& REAC FUEL='METHANE', 
      SPEC_ID_NU='METHANE','OXYGEN','CARBON DIOXIDE','WATER VAPOR' 
      NU=-1,-2,1,2,
      SPEC_ID_N_S='METHANE','OXYGEN',
      A = 5.2E13,
      N_S= 1,1, HEAT_OF_COMBUSTION = 50240, E = 123980.0
      FIXED_MIX_TIME=0.003/

IGNITION SOURCE REACTION TIME

&RAMP ID='N2_V',   T=  0.000,  F=  0.0                                       /
&RAMP ID='N2_V',   T=  3.000,  F=  0.0                                       /
&RAMP ID='N2_V',   T=  3.500,  F=  1.0                                       /
&RAMP ID='N2_V',   T=  4.000,  F=  0.0                                       /
&RAMP ID='N2_V',   T=  10.00,  F=  0.0                                       /
                                                                             /
&RAMP ID='N2_T',   T=  0.000,  F=  0.0                                       /
&RAMP ID='N2_T',   T=  3.000,  F=  0.0                                       /
&RAMP ID='N2_T',   T=  3.500,  F=  1.0                                       /
&RAMP ID='N2_T',   T=  4.000,  F=  0.0                                       /
&RAMP ID='N2_T',   T=  10.00,  F=  0.0                                       /

**Comment by rmcdermo** [comment] 2016-01-26 12:09
Please post your input file.  Change the extension to *.txt and attach it to your post.  Thanks.

**Comment by DineshMyilsamy** [comment] 2016-01-26 12:37
For your information Hereby I have attached my input file.

[Temp_100_FMT_1_00.txt](https://github.com/firemodels/fds-smv/files/104879/Temp_100_FMT_1_00.txt)

**Comment by mcgratta** [comment] 2016-01-26 12:40
I'll take a look at this case. It is possible that the difference in results is due to the order in which the different MPI processes progress through a time step. Just a hunch at this point.

**Comment by DineshMyilsamy** [comment] 2016-01-26 12:58
Okay Sir, I did as like you said

**Comment by mcgratta** [comment] 2016-01-26 17:53
Which pressure device did you plot?

**Comment by mcgratta** [comment] 2016-01-26 23:00
I ran the case twice. The results for the first pressure device are identical.

**Comment by DineshMyilsamy** [comment] 2016-01-27 00:34
I have plotted for the device ID='P_WALL_01

**Comment by DineshMyilsamy** [comment] 2016-01-27 00:38
Hi Sir,

Very nice to hear that from you

Did you make any changes in that input file ?

Have you seen at other Devc location is it same?

May I know how many cores did  you used  and your computer configuration

**Comment by DineshMyilsamy** [comment] 2016-01-27 11:54
Hello Sir, (Mr.Kevin McGrattan & Randy McDermott)

```
       I am sorry to bother you,

      I hope you might have seen my problem description and my input
```

file.

```
       with reference to my problem details and to my input file, do
```

you have any idea what is the problem on my side ?

Thank you,

Best Regards,
Dinesh Myislamy

**Comment by mcgratta** [comment] 2016-01-27 13:26
```
[mcgratta@burn Test]$ diff backdraft_devc.csv backdraft2_devc.csv
[mcgratta@burn Test]$
```

The output files from my two runs are identical. 

It is difficult to say what is wrong. Maybe your cluster is losing packets, meaning that the MPI messages are corrupted. I can say that your input file is badly designed. It is poor practice to create thin mesh layers with only 6 cells in the vertical direction. In effect, you are maximizing the amount of information this is communicated process to process. You are also maximizing the error associated with using multiple meshes. 

MIRROR boundaries should, in general, not be used for LES calculations. There is no symmetry plane in a turbulent flow like this.

Do not use ADIABATIC walls. There is no such thing as an ADIABATIC wall. We only use this parameter for diagnostic purposes.

INIT lines. Why? Why not just simulate the scenario starting from ambient conditions?

Your combustion issues are being addressed in another thread.

Why all the PRESSURE lines? What do you expect to learn from them?

Could you tell me what reference you used to design this calculation? I am interested because I see these mistakes made very often in input files that are sent to us. I do not know the source of the information that is compelling alot of people to do these things.

**Comment by drjfloyd** [comment] 2016-01-27 13:47
I don't agree with the statement that adiabatic walls should only be used for diagnostic purposes. 

If I am doing a calculation looking at how quickly a smoke layer can drop in a space, the use of adiabatic walls will add a degree of conservatism as it prevents heat removal from the smoke layer (higher temperature means lower density which results in the layer dropping faster).

**Comment by mcgratta** [comment] 2016-01-27 15:25
OK -- but if the calculation exhibits erratic behavior, that is one of the things I would eliminate.

**Comment by sinaparsa75** [comment] 2020-03-02 04:57
> 
> 
> Dear Sir,
> I am Dinesh Myilsamy, currently I am working on a project which is based on compartment fire in an under ventilated condition.
> 
> OUTLINE OF MY RESEARCH:
> 
> ```
> Hot unburnt fuel mixtures (at 373 K)  will be present inside a closed compartment and there is an ignition source which is kept at one of the compartment  (Temp. 1500 k at its top surface), when the compartment window is opened the atmospheric air will get into the compartment due to the density difference. Fresh air will start to move inside the compartment and it will reach to the ignition source which is kept at other end of the compartment (opposite to window). 
> ```
> 
> When the fresh air reacts with the unburnt fuel in the presence of ignition source there will be a rapid flame propagation (BACKDRAFT) inside the compartment with and it moves out of the compartment as a fireball.
> 
> ![picture1](https://cloud.githubusercontent.com/assets/16892714/12573429/5d23d9f4-c43c-11e5-8081-b44e583171af.png)
> 
> ```
>           This has to be carried out using LES Turbulence Model and EDC as a combustion Model.
> ```
> 
> MY ISSUES.
> 
> ```
>         1.  For my simulation I am using FDS v.6.3.2 in an  Intel Core 2 E8400, 3.0 GHz, 32 Core Cluster. - Linux Operating system.
> 
>          I am getting two different solutions when I tried to simulate my  FDS input file. 
> 
>          I did not even change a single letter in my FDS file, I used the same computer, using 15 Cores. but I found a two different solution. 
> ```
> 
> ![press](https://cloud.githubusercontent.com/assets/16892714/12573465/d3a96f12-c43c-11e5-9ef9-52177027babc.png)
> 
> ```
>        2.  To resolve this problem I got a guidance from FDS google group. In that they adviced me to use   NOISE =.FALSE.
> 
>           I have tried by specifying NOISE=.FALSE,  NOISE_VELOCITY = 0.005 but the problem didn't get resolved
> ```
> 
> ![noise_005](https://cloud.githubusercontent.com/assets/16892714/12573614/5ae504cc-c43e-11e5-821f-4a141a9dd49e.png)
> 
> My input parameters
> 
> MISC PARAMETERS
> 
> & MISC TMPA=25.0, DNS=.FALSE., NOISE=.FALSE., NOISE_VELOCITY=0.005, SUPPRESSION=.FALSE. /
> & RADI RADIATION=.TRUE./
> 
> REAC PARAMETERS
> 
> & REAC FUEL='METHANE',
> SPEC_ID_NU='METHANE','OXYGEN','CARBON DIOXIDE','WATER VAPOR'
> NU=-1,-2,1,2,
> SPEC_ID_N_S='METHANE','OXYGEN',
> A = 5.2E13,
> N_S= 1,1, HEAT_OF_COMBUSTION = 50240, E = 123980.0
> FIXED_MIX_TIME=0.003/
> 
> IGNITION SOURCE REACTION TIME
> 
> &RAMP ID='N2_V', T= 0.000, F= 0.0 /
> &RAMP ID='N2_V', T= 3.000, F= 0.0 /
> &RAMP ID='N2_V', T= 3.500, F= 1.0 /
> &RAMP ID='N2_V', T= 4.000, F= 0.0 /
> &RAMP ID='N2_V', T= 10.00, F= 0.0 /
> /
> &RAMP ID='N2_T', T= 0.000, F= 0.0 /
> &RAMP ID='N2_T', T= 3.000, F= 0.0 /
> &RAMP ID='N2_T', T= 3.500, F= 1.0 /
> &RAMP ID='N2_T', T= 4.000, F= 0.0 /
> &RAMP ID='N2_T', T= 10.00, F= 0.0 /

hello Mr.Myilsamy;
i'm reading your paper with a title "Large eddy simulation of the backdraft dynamics in compartments with different opening geometries" and i want to use this paper for my validation project. but i dont have some specification. could you send me fds code for case 1 in this paper? please help me for this case.
my email: s2_parsa@yahoo.com

**Comment by mcgratta** [comment] 2020-03-02 14:24
I need you to do two tasks:

1. Run your case with the latest released version of FDS.
2. If you still see multiple solutions, post the input file.

**Comment by sinaparsa75** [comment] 2020-03-03 04:27
> 
> 
> I need you to do two tasks:
> 
>     1. Run your case with the latest released version of FDS.
> 
>     2. If you still see multiple solutions, post the input file.

Hello Mr.Kevin
I ran the code with the latest version. But my Problem exactly with multiple solutions. i have some problem with reaction and ignition source of this paper : https://www.researchgate.net/publication/332830944_Large_eddy_simulation_of_the_backdraft_dynamics_in_compartments_with_different_opening_geometries
I'm Trying to learn Backdraft phenomena for case 1 in this paper.
Could you help me reproduce the Code form this article?
I want to reach same this pictures. thank you.
********************************************
my code:
&HEAD CHID='v2'/
&TIME T_END=15.0, DT=0.01/
&DUMP RENDER_FILE='v2.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0, DT_SL3D=0.25/
&MISC TMPA=25.0, Y_O2_INFTY=0.232379/

&MESH ID='Mesh01', IJK=128,21,43, XB=0.0,3.84,0.0,0.64,0.0,1.28/

&SPEC ID='OXYGEN'/
&SPEC ID='NITROGEN'/
&SPEC ID='CARBON MONOXIDE'/
&SPEC ID='CARBON DIOXIDE'/

&REAC ID='METHANE',
      FYI='AFT NIST Multi-Floor FDS5 Validation',
      FUEL='METHANE',
      CRITICAL_FLAME_TEMPERATURE=4000.0,
      AUTO_IGNITION_TEMPERATURE=150.0,
      CO_YIELD=0.015,
      HEAT_OF_COMBUSTION=5.3E4/

&CTRL ID='invert', FUNCTION_TYPE='ALL', LATCH=.FALSE., INITIAL_STATE=.TRUE., INPUT_ID='TIMER->OUT2'/
&DEVC ID='O2', QUANTITY='MASS FRACTION', SPEC_ID='OXYGEN', XYZ=0.62,0.32,0.32/
&DEVC ID='THCP', QUANTITY='THERMOCOUPLE', XYZ=1.24,0.32,0.32/
&DEVC ID='TIMER->OUT', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=2.85/
&DEVC ID='TIMER->OUT2', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=0.01/

&MATL ID='STEEL2',
      SPECIFIC_HEAT=0.77,
      CONDUCTIVITY=45.8,
      DENSITY=7700.0,
      EMISSIVITY=0.7/

&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      ADIABATIC=.TRUE./
&SURF ID='STEEL',
      RGB=226,14,243,
      TMP_INNER=25.0,
      BACKING='INSULATED',
      MATL_ID(1,1)='STEEL2',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=3.0E-4/
&SURF ID='Surface01',
      RGB=255,102,0,
      TMP_FRONT=1500.0/

&INIT ID='Meth', TEMPERATURE=67.0, SPEC_ID='CARBON DIOXIDE','CARBON MONOXIDE','METHANE','NITROGEN','OXYGEN', MASS_FRACTION=0.021,1.2E-3,0.1224,0.7094,0.146, XB=0.02,1.22,0.02,0.62,0.02,0.3/ 
&INIT ID='Meth U', TEMPERATURE=103.0, SPEC_ID='CARBON DIOXIDE','CARBON MONOXIDE','METHANE','NITROGEN','OXYGEN', MASS_FRACTION=0.021,1.2E-3,0.1224,0.7094,0.146, XB=0.02,1.22,0.02,0.62,0.3,0.62/ 

&OBST ID='Obstruction', XB=0.0,3.84,0.0,0.64,0.0,0.02, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,0.02,0.02,0.62,0.02,0.62, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,1.24,0.0,0.64,0.62,0.64, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,1.24,0.0,0.02,0.02,0.62, COLOR='INVISIBLE', SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,1.24,0.62,0.64,0.02,0.62, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.02,0.17,0.245,0.395,0.02,0.17, SURF_ID='STEEL'/ 
&OBST ID='Obstruction', XB=1.23,1.23,0.213333,0.426667,0.029767,0.625116, SURF_ID='ADIABATIC', CTRL_ID='invert'/ 
&OBST ID='Obstruction', XB=1.23,1.23,0.030476,0.213333,0.029767,0.625116, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=1.23,1.23,0.426667,0.609524,0.029767,0.625116, SURF_ID='ADIABATIC'/ 

&VENT ID='Mesh Vent: Mesh01 [XMAX]', SURF_ID='OPEN', XB=3.84,3.84,0.0,0.64,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,0.64,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [YMAX]', SURF_ID='OPEN', XB=0.0,3.84,0.64,0.64,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [YMIN]', SURF_ID='OPEN', XB=0.0,3.84,0.0,0.0,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [ZMAX]', SURF_ID='OPEN', XB=0.0,3.84,0.0,0.64,1.28,1.28/ 
&VENT ID='Vent02', SURF_ID='Surface01', XB=0.02,0.17,0.245,0.395,0.17,0.17, DEVC_ID='TIMER->OUT'/ 

&SLCF QUANTITY='MASS FRACTION', SPEC_ID='METHANE', PBY=0.32/
&SLCF QUANTITY='TEMPERATURE', PBY=0.32/


&TAIL /
![22](https://user-images.githubusercontent.com/47948506/75742876-4ff6c680-5d24-11ea-8de4-12ec049a9cf6.PNG)
![33](https://user-images.githubusercontent.com/47948506/75742897-5b49f200-5d24-11ea-876a-83cd8bb6f004.PNG)
![Capture3333](https://user-images.githubusercontent.com/47948506/75742903-600ea600-5d24-11ea-90cb-9df8606c344b.PNG)

**Comment by sinaparsa75** [comment] 2020-03-03 07:17
I write another Code with better information... But it didnt work also
Code:
&HEAD CHID='v2'/
&TIME T_END=15.0, DT=0.01/
&DUMP RENDER_FILE='v2.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0, DT_SL3D=0.25/
&MISC TMPA=25.0, Y_O2_INFTY=0.232379/

&MESH ID='Mesh01', IJK=128,21,43, XB=0.0,3.84,0.0,0.64,0.0,1.28/

&SPEC ID='OXYGEN'/
&SPEC ID='CARBON DIOXIDE'/
&SPEC ID='CARBON MONOXIDE'/
&SPEC ID='NITROGEN'/

&REAC ID='METHANE',
      FYI='AFT NIST Multi-Floor FDS5 Validation',
      FUEL='METHANE',
      CRITICAL_FLAME_TEMPERATURE=3000.0,
      AUTO_IGNITION_TEMPERATURE=150.0,
      CO_YIELD=0.015,
      HEAT_OF_COMBUSTION=5.3E4/

&CTRL ID='invert', FUNCTION_TYPE='ALL', LATCH=.FALSE., INITIAL_STATE=.TRUE., INPUT_ID='TIMER->OUT'/
&DEVC ID='O2', QUANTITY='MASS FRACTION', SPEC_ID='OXYGEN', XYZ=0.62,0.32,0.32/
&DEVC ID='THCP', QUANTITY='THERMOCOUPLE', XYZ=1.24,0.32,0.32/
&DEVC ID='TIMER->OUT', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=0.01/

&MATL ID='STEEL2',
      SPECIFIC_HEAT=0.77,
      CONDUCTIVITY=45.8,
      DENSITY=7700.0,
      EMISSIVITY=0.7/

&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      ADIABATIC=.TRUE./
&SURF ID='STEEL',
      RGB=226,14,243,
      TMP_INNER=25.0,
      BACKING='INSULATED',
      MATL_ID(1,1)='STEEL2',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=3.0E-4/
&SURF ID='Surface01',
      RGB=239,7,5,
      TMP_FRONT=1500.0,
      RAMP_T='Surface01_RAMP_T',
      VEL=-0.05,
      RAMP_V='Surface01_RAMP_V',
      MASS_FRACTION=1.0,
      SPEC_ID='METHANE',
      TAU_MF=1.0E-3/
&RAMP ID='Surface01_RAMP_T', T=0.0, F=0.0/
&RAMP ID='Surface01_RAMP_T', T=2.4, F=0.0/
&RAMP ID='Surface01_RAMP_T', T=2.9, F=1.0/
&RAMP ID='Surface01_RAMP_T', T=3.5, F=0.0/
&RAMP ID='Surface01_RAMP_T', T=8.0, F=0.0/
&RAMP ID='Surface01_RAMP_V', T=0.0, F=0.0/
&RAMP ID='Surface01_RAMP_V', T=2.4, F=0.0/
&RAMP ID='Surface01_RAMP_V', T=2.9, F=1.0/
&RAMP ID='Surface01_RAMP_V', T=3.5, F=0.0/
&RAMP ID='Surface01_RAMP_V', T=8.0, F=0.0/

&INIT ID='Meth', TEMPERATURE=67.0, SPEC_ID='CARBON DIOXIDE','CARBON MONOXIDE','METHANE','NITROGEN','OXYGEN', MASS_FRACTION=0.021,1.2E-3,0.1224,0.7094,0.146, XB=0.02,1.22,0.02,0.62,0.02,0.3/ 
&INIT ID='Meth U', TEMPERATURE=103.0, SPEC_ID='CARBON DIOXIDE','CARBON MONOXIDE','METHANE','NITROGEN','OXYGEN', MASS_FRACTION=0.021,1.2E-3,0.1224,0.7094,0.146, XB=0.02,1.22,0.02,0.62,0.3,0.62/ 

&OBST ID='Obstruction', XB=0.0,3.84,0.0,0.64,0.0,0.02, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,0.02,0.02,0.62,0.02,0.62, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,1.24,0.0,0.64,0.62,0.64, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,1.24,0.0,0.02,0.02,0.62, COLOR='INVISIBLE', SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.0,1.24,0.62,0.64,0.02,0.62, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0.02,0.17,0.245,0.395,0.02,0.17, SURF_ID='STEEL'/ 
&OBST ID='Obstruction', XB=1.23,1.23,0.213333,0.426667,0.029767,0.625116, SURF_ID='ADIABATIC', CTRL_ID='invert'/ 
&OBST ID='Obstruction', XB=1.23,1.23,0.030476,0.213333,0.029767,0.625116, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=1.23,1.23,0.426667,0.609524,0.029767,0.625116, SURF_ID='ADIABATIC'/ 

&VENT ID='Mesh Vent: Mesh01 [XMAX]', SURF_ID='OPEN', XB=3.84,3.84,0.0,0.64,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,0.64,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [YMAX]', SURF_ID='OPEN', XB=0.0,3.84,0.64,0.64,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [YMIN]', SURF_ID='OPEN', XB=0.0,3.84,0.0,0.0,0.0,1.28/ 
&VENT ID='Mesh Vent: Mesh01 [ZMAX]', SURF_ID='OPEN', XB=0.0,3.84,0.0,0.64,1.28,1.28/ 
&VENT ID='Vent02', SURF_ID='Surface01', XB=0.02,0.17,0.245,0.395,0.17,0.17/ 

&SLCF QUANTITY='MASS FRACTION', SPEC_ID='METHANE', PBY=0.32/
&SLCF QUANTITY='TEMPERATURE', PBY=0.32/


&TAIL /
*************************************
ignition source not burned and i cant see backdraft phenomena
please help me to reach a correct Code.

**Comment by mcgratta** [comment] 2020-03-03 18:44
Sorry, the purpose of the FDS Issue Tracker is to resolve problems and bugs in FDS. Unless there is something specifically wrong with FDS, we cannot help you. Perhaps you can reach out to the authors of the paper and ask them to share their input files.

**Closed as completed by mcgratta** 2020-03-03 18:44 UTC

**Comment by sinaparsa75** [comment] 2020-03-05 09:44
> 
> 
> For your information Hereby I have attached my input file.
> 
> [Temp_100_FMT_1_00.txt](https://github.com/firemodels/fds-smv/files/104879/Temp_100_FMT_1_00.txt)

I cant download this file! could u put it again?
