### ISSUE TITLE
.stop files no longer kill running FDS processes

### ISSUE THREAD

**Issue by mabboud123** [firemodels/fds#4726] opened 2017-02-14 06:31 UTC
Hi there,

We have recently installed the latest pre-built linux installer:

===
FDS_6.5.3-SMV_6.4.4_linux64.sh:

worker@node1 ~]$ fds

 Fire Dynamics Simulator

 Current Date  : February 14, 2017  17:02:37
 Version           : FDS 6.5.3
 Revision          : FDS6.5.3-598-geb56ed1
 Revision Date    : Thu Jan 19 16:12:59 2017 -0500
 Compilation Date : Jan 22, 2017  18:04:30

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Open MPI v1.8.4, package: Open MPI gforney@burn Distribution, ident: 1.8.4, repo rev: v1.8.3-330-g0344f04, Dec 19, 2014

===
...running on the head node of our CentOS v7 Cluster.

We've noticed that putting a CHID.stop file in the Output folder of our running jobs will, more often than not, NOT stop running calculations.

Nothing has changed in our Cluster since the last installer release as far as we know, and I'm wondering if there is an issue with this latest pre-built release at all?

Do let me know if there is any further info you may need.

Best regards,
Michael Abboud and Dr. Sam Alshroof

Olsson Fire and Risk
Sydney, Australia

**Comment by rmcdermo** [comment] 2017-02-14 13:23
Thanks for the report.  We'll take a look.

**Comment by mcgratta** [comment] 2017-02-14 14:59
Can you post a case that does not stop? Keep in mind that jobs do not stop instantly. They do not stop until the radiation field has been completely updated, which is by default every 15 time steps. So maybe the problem is that you expect the job to stop very quickly, but sometimes it might require a few minutes.

**Comment by mabboud123** [comment] 2017-02-15 22:24
Thanks Kevin, Randy - we're just prepping a test case which I can upload.  Is there a way I can submit the case privately, out of concerns for sensitive customer information?

**Comment by mcgratta** [comment] 2017-02-15 22:44
No, strip out any info you don't want public. It's best to make your case as simple as possible.

**Comment by mabboud123** [comment] 2017-02-16 06:56
Ok thanks Kevin, understood - see the attached for reference

Michael

[CFD17005_TEstFile2.fds6.txt](https://github.com/firemodels/fds/files/779288/CFD17005_TEstFile2.fds6.txt)

**Comment by mcgratta** [comment] 2017-02-16 13:44
I tried to stop your case and it did stop. However, it stopped with an error and did not produce any restart files. So there is something wrong in this case. I'll look into it. In the meantime, don't stop jobs. Even if we determine the problem, the fix probably won't come until the next release, and it may not be possible to restart old cases with the new version.

**Comment by mcgratta** [comment] 2017-02-16 22:29
Disregard my previous post. I accidentally ran an old version of FDS. Using the latest Linux release, I successfully stopped your job about 5 times but failed to stop it once. In that case, the code just hung. When your job fails to stop, does FDS also stop producing output? Does it still continue to run, even though the output files do not grow?

**Comment by mabboud123** [comment] 2017-02-16 22:57
Yes, that is exactly the set of symptoms we're seeing:

 - Intermittent failure to stop
 - No further output is produced
 - FDS jobs continue to run but the output files stop growing

Michael

**Comment by mcgratta** [comment] 2017-08-16 18:46
I cannot consistently cause this failure to occur. How often do you jobs fail to stop?

**Comment by mcgratta** [comment] 2017-09-05 14:22
I am closing this issue for now. If you notice that a job is consistently failing to stop and start, submit with a new issue.

**Closed as completed by mcgratta** 2017-09-05 14:22 UTC
