### ISSUE TITLE
Pressue Zone Temperature Slice

### ISSUE THREAD

**Issue by kinmanwong** [firemodels/fds#2534] opened 2015-07-22 18:53 UTC
I have a pressure zone leakage model. I used interim obstruction (removed at 1ss.) across zone boundaries that have no physical obstruction. Results show continuous spread across the removed obstruction except temperature slice. I am attaching a much simplified FDS file. Please compare the 3D Smoke and Density Slice with the Temperature Slice. That latter suggested that the interim obstruction remains and traps the temperature within the source zone. Help appreciated.

zone_test.fds
Generated by PyroSim - Version 2012.1.1221
21-Jul-2015 3:31:54 PM

&HEAD CHID='zone_test', TITLE='Zone_test'/
&TIME T_END=1000.0/
&DUMP RENDER_FILE='zone_test.ge1', DT_PL3D=10.0, MASS_FILE=.TRUE./

&MESH ID='Mesh', IJK=50,50,12, XB=0.0,10.0,0.0,10.0,0.0,2.4/

&ZONE ID='ZONE1', XB=0.0,5.4,0.0,5.0,0.0,2.4, LEAK_AREA(2)=0.016/
&ZONE ID='ZONE2', XB=5.4,10.0,0.0,10.0,0.0,2.4/
&ZONE ID='ZONE3', XB=0.0,5.4,5.0,10.0,0.0,2.4/

&REAC ID='display',
      FYI='Display',
      C=3.0,
      H=8.0,
      O=0.0,
      N=0.0/

&DEVC ID='pres_1', QUANTITY='PRESSURE', XYZ=1.0,1.0,1.0/
&DEVC ID='pres_2', QUANTITY='PRESSURE', XYZ=7.5,5.0,1.0/
&DEVC ID='pres_3', QUANTITY='PRESSURE', XYZ=2.5,7.5,1.0/
&DEVC ID='door 3', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=20.0, INITIAL_STATE=.TRUE./
&DEVC ID='TIMER', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=1.0, INITIAL_STATE=.TRUE./
&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=500.0/

&OBST XB=5.0,5.2,0.0,2.0,0.0,2.4, SURF_ID='INERT'/ Obstruction #1a
&OBST XB=5.0,5.2,3.0,5.2,0.0,2.4, SURF_ID='INERT'/ Obstruction #1b
&OBST XB=0.0,5.2,5.0,5.2,0.0,2.4, SURF_ID='INERT'/ Obstruction #2
&OBST XB=0.0,0.0,6.0,7.0,0.0,2.0, SURF_ID='INERT', DEVC_ID='door 3'/ Obstruction #3
&OBST XB=5.0,5.2,5.2,10.0,0.0,2.4, OUTLINE=.TRUE., SURF_ID='INERT', DEVC_ID='TIMER'/ Zone_obst
&OBST XB=5.0,5.2,2.0,3.0,2.0,2.4, SURF_ID='INERT'/ Obstruction #1c

&VENT SURF_ID='Fire', XB=2.0,3.0,2.0,3.0,0.0,0.0/ Fire block
&VENT SURF_ID='OPEN', XB=0.0,0.0,6.0,7.0,0.0,2.0/ Vent #2

&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBZ=1.0/
&SLCF QUANTITY='PRESSURE', PBZ=1.0/
&SLCF QUANTITY='DENSITY', PBZ=1.0/

&TAIL /

**Comment by drjfloyd** [comment] 2015-07-22 23:53
Kevin,

Something seems amiss with the zone logic in the current source. There are three zones defined.  At t=0 two of these zones should be immediately merged. At t=1 the third should merge.  Temperature shows ok behavior, but pressure is showing a different rise in each zone.  

![zone_test_0019](https://cloud.githubusercontent.com/assets/12799217/8840120/03ffadc8-30ab-11e5-91c0-1a9f5161124f.png)
![zone_test_0015](https://cloud.githubusercontent.com/assets/12799217/8840121/0401a222-30ab-11e5-8059-ffa745373261.png)

**Comment by mcgratta** [comment] 2015-07-24 19:42
Your ZONE definitions go beyond the intended compartments. You do not have a door defined, and FDS extends ZONE 1 into ZONE 2. Here is a simple input file that shows that things are working.

&HEAD CHID='zone', TITLE='Zone_test'/

&TIME T_END=60.0/

&MESH IJK=50,50,12, XB=0.0,10.0,0.0,10.0,0.0,2.4/

&ZONE ID='ZONE1', XB=0.0,5.0,0.0,5.0,0.0,2.4, LEAK_AREA(2)=0.016/
&ZONE ID='ZONE2', XB=5.4,10.0,0.0,10.0,0.0,2.4/
&ZONE ID='ZONE3', XB=0.0,5.0,5.2,10.0,0.0,2.4/

&DEVC ID='pres_1', QUANTITY='PRESSURE', XYZ=1.0,1.0,1.0/
&DEVC ID='pres_2', QUANTITY='PRESSURE', XYZ=7.5,5.0,1.0/
&DEVC ID='pres_3', QUANTITY='PRESSURE', XYZ=2.5,7.5,1.0/
&DEVC ID='door 3', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=20.0, INITIAL_STATE=.TRUE./
&DEVC ID='TIMER', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=1.0, INITIAL_STATE=.TRUE./
&SURF ID='Blow', COLOR='RED', VEL=-0.1/

&OBST XB=5.0,5.2,0.0,2.0,0.0,2.4, / 
&OBST XB=5.0,5.2,3.0,5.2,0.0,2.4, / 
&OBST XB=0.0,5.2,5.0,5.2,0.0,2.4, / 
&OBST XB=0.0,0.0,6.0,7.0,0.0,2.0, DEVC_ID='door 3'/ 
&OBST XB=5.0,5.2,5.2,10.0,0.0,2.4 DEVC_ID='TIMER'/ 
&OBST XB=5.0,5.2,2.0,3.0,2.0,2.4 / 
&OBST XB=5.0,5.2,2.0,3.0,0.0,2.0 DEVC_ID='TIMER' / 

&VENT SURF_ID='Blow', XB=2.0,3.0,2.0,3.0,0.0,0.0/
&VENT SURF_ID='OPEN', XB=0.0,0.0,6.0,7.0,0.0,2.0/ Vent #2

&SLCF QUANTITY='TEMPERATURE', PBZ=1.0, CELL_CENTERED=.TRUE. /
&SLCF QUANTITY='PRESSURE', PBZ=1.0, CELL_CENTERED=.TRUE. /
&SLCF QUANTITY='DENSITY', PBZ=1.0, CELL_CENTERED=.TRUE. /

&TAIL /

**Comment by kinmanwong** [comment] 2015-07-27 18:45
Hi Kevin

Thanks for your response. The example is a simplification of a project so that I can illustrate the error.

I am afraid it is my interpretation of the following details of the FDS guidelines that confuse me a bit. I am going to revise my model without the abutting requirement.

“Note that if you plan to have one zone open up to another via the removal of an obstruction, make
sure that the coordinates of the two zones abut (i.e., touch) even if one of the zones includes the solid
obstruction that separates them. FDS recognizes that a zone boundary has been removed when two adjacent
cells belonging to two different zones have no solid obstruction between them. It is recommended that you
extend at least one of the zone boundaries into the solid obstruction separating the two zones.”

Kin

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image002.jpg@01D0C861.A5C6B370]

**Comment by mcgratta** [comment] 2015-08-03 20:00
Has this issue been resolved?

**Comment by kinmanwong** [comment] 2015-08-06 15:58
Hi Kevin

Sorry for the late response. I need to run the model to a point where I can illustrate the problem.

I have no problem getting smooth flows across pressure zone boundaries in the sample case per your advice. However, after similar adjustments in the actual model, I am afraid the problem with temperature slices cannot be resolved.

The project is a 11 story building and is made up of a number of pressure zones (essentially elevator shafts and stair cases leaking through doors). Referring to the two renderings attached, one for temperature slice and the other for visibility slice in exactly the same plane, I can notice differences in the flow patterns specifically as a result of the interim zone boundaries (removed at 1s). These interim zone boundaries are required because they straddle over stair zone with door and elevator lobby without door. Such boundaries are thick because I need them to cover the physical boundaries as far as possible. All the pressure zones are contained within their corresponding physical boundaries.

The results have been consistent with the many variations in defining the zone boundaries. While the visibility (as well as 3dSmoke and other properties) slices demonstrate smooth flow across the interim boundaries, the temperature slice shows to me that there is no flow across such boundaries. Hence, hot air (from a fire in the lowest floor) leaks into the elevator shaft, rises up and apparently flows into the elevator lobby and is then trapped there by the remaining interim boundaries. That results in hot trapped air in the elevator lobby which is inconsistent with the visibility results.

I hope that would be good enough to present the encountered problem.

Kin

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image003.jpg@01D0D026.092E0550]

**Comment by mcgratta** [comment] 2015-08-06 17:11
I need to have a simple example in order to fix the problem.

**Comment by kinmanwong** [comment] 2015-08-06 18:19
That was what I hope to illustrate with my first submitted example. There may be inappropriate definition of the boundaries but the result do show the trapped feature of the temperature slice. Once again, the 3dSmoke and say density slices show flow across the interim zone boundary but temperature slice does not. I would highlight that the actual model was NOT built with this zone definition but this example allows me to reproduce the difference in behavior between temperature slice and the others.

The fds file is once again attached.

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image003.jpg@01D0D039.C0AD23B0]

**Comment by mcgratta** [comment] 2015-08-07 13:55
I do not see the attachment. You might have to paste it into the browser.

**Comment by kinmanwong** [comment] 2015-08-07 16:44
The file is attached.

Just to re-iterate, this is the same fds file I posted earlier. There may be syntax issues but this is a simplified case which I can reproduce the point that I want to illustrate, i.e. difference between temperature slice and others relative to flow across the interim obstruction. Please note that if I run the case for longer, the problem becomes more obvious.

zone_test.fds
Generated by PyroSim - Version 2012.1.1221
6-Aug-2015 10:33:59 AM

&HEAD CHID='zone_test', TITLE='Zone_test'/
&TIME T_END=200.0/
&DUMP RENDER_FILE='zone_test.ge1', DT_PL3D=10.0, MASS_FILE=.TRUE./

&MESH ID='Mesh', IJK=50,50,12, XB=0.0,10.0,0.0,10.0,0.0,2.4/

&ZONE ID='ZONE1', XB=0.0,5.4,0.0,5.0,0.0,2.4, LEAK_AREA(2)=0.016/
&ZONE ID='ZONE2', XB=5.4,10.0,0.0,10.0,0.0,2.4/
&ZONE ID='ZONE3', XB=0.0,5.4,5.0,10.0,0.0,2.4/

&REAC ID='display',
      FYI='Display',
      C=3.0,
      H=8.0,
      O=0.0,
      N=0.0/

&DEVC ID='pres_1', QUANTITY='PRESSURE', XYZ=1.0,1.0,1.0/
&DEVC ID='pres_2', QUANTITY='PRESSURE', XYZ=7.5,5.0,1.0/
&DEVC ID='pres_3', QUANTITY='PRESSURE', XYZ=2.5,7.5,1.0/
&DEVC ID='door 3', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=20.0, INITIAL_STATE=.TRUE./
&DEVC ID='TIMER', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=1.0, INITIAL_STATE=.TRUE./
&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=500.0/

&OBST XB=5.0,5.2,0.0,2.0,0.0,2.4, SURF_ID='INERT'/ Obstruction #1a
&OBST XB=5.0,5.2,3.0,5.2,0.0,2.4, SURF_ID='INERT'/ Obstruction #1b
&OBST XB=0.0,5.2,5.0,5.2,0.0,2.4, SURF_ID='INERT'/ Obstruction #2
&OBST XB=0.0,0.0,6.0,7.0,0.0,2.0, SURF_ID='INERT', DEVC_ID='door 3'/ Obstruction #3
&OBST XB=5.0,5.2,5.2,10.0,0.0,2.4, OUTLINE=.TRUE., SURF_ID='INERT', DEVC_ID='TIMER'/ Zone_obst
&OBST XB=5.0,5.2,2.0,3.0,2.0,2.4, SURF_ID='INERT'/ Obstruction #1c

&VENT SURF_ID='Fire', XB=2.0,3.0,2.0,3.0,0.0,0.0/ Fire block
&VENT SURF_ID='OPEN', XB=0.0,0.0,6.0,7.0,0.0,2.0/ Vent #2

&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBZ=1.0/
&SLCF QUANTITY='PRESSURE', PBZ=1.0/
&SLCF QUANTITY='DENSITY', PBZ=1.0/

&TAIL /

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image003.jpg@01D0D0F5.94535AC0]

**Comment by mcgratta** [comment] 2015-08-07 16:51
Why do you still define Zone 1 outside of the first compartment, at x=5.4 m?

**Comment by kinmanwong** [comment] 2015-08-07 21:33
When I first built my project model, I had it with the zone extending beyond the compartment because that was what I interpreted from the user guide. Then I prepared the earlier sample case which I was able to repeat the problem of weird temperature display.

I have since modified the zone definitions following your earlier advice. (The following fds file shows the general format of the geometry and zone setup.)

However, while the simple example below does not show any trapped temperature phenomenon, my actual project model (which had been prepared in the same manner) exhibits this afore-mentioned problem.

In order to forward you with an example that would repeat the problem, I have no choice but to re-send you the earlier fds file. What I hope to find out is why such inconsistency between temperature results and the others. Is the zonal definition the culprit. But my project model was built correctly.

Following fds file represents the way I used in my project model but it cannot repeat the temperature slice problem:

zone_test_r.fds
Generated by PyroSim - Version 2012.1.1221
7-Aug-2015 2:01:56 PM

&HEAD CHID='zone_test_r', TITLE='Zone_test_r'/
&TIME T_END=100.0/
&DUMP RENDER_FILE='zone_test_r.ge1', DT_PL3D=10.0, MASS_FILE=.TRUE./

&MESH ID='Mesh', IJK=50,50,12, XB=0.0,10.0,0.0,10.0,0.0,2.4/

&ZONE ID='ZONE1', XB=0.0,5.0,0.0,5.0,0.0,2.4, LEAK_AREA(2)=0.017/
&ZONE ID='ZONE2', XB=5.6,10.0,0.0,10.0,0.0,2.4/
&ZONE ID='ZONE3', XB=0.0,5.0,5.2,10.0,0.0,2.4/

&REAC ID='display',
      FYI='Display',
      C=3.0,
      H=8.0,
      O=0.0,
      N=0.0/

&DEVC ID='pres_1', QUANTITY='PRESSURE', XYZ=1.0,1.0,1.0/
&DEVC ID='pres_2', QUANTITY='PRESSURE', XYZ=7.5,5.0,1.0/
&DEVC ID='pres_3', QUANTITY='PRESSURE', XYZ=2.5,7.5,1.0/
&DEVC ID='door 3', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=20.0, INITIAL_STATE=.TRUE./
&DEVC ID='TIMER', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=1.0, INITIAL_STATE=.TRUE./
&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=500.0/
&SURF ID='Leak_door',
      RGB=146,202,166,
      LEAK_PATH=1,2/

&OBST XB=5.1,5.3,0.0,2.0,0.0,2.4, SURF_ID='INERT'/ Obstruction #1a
&OBST XB=5.1,5.3,3.0,5.2,0.0,2.4, SURF_ID='INERT'/ Obstruction #1b
&OBST XB=0.0,5.2,5.0,5.2,0.0,2.4, SURF_ID='INERT'/ Obstruction #2
&OBST XB=0.0,0.0,6.0,7.0,0.0,2.0, SURF_ID='INERT', DEVC_ID='door 3'/ Obstruction #3
&OBST XB=5.0,5.6,0.0,10.0,0.0,2.4, OUTLINE=.TRUE., SURF_ID='INERT', DEVC_ID='TIMER'/ Zone_obst
&OBST XB=5.1,5.3,2.0,3.0,2.0,2.4, SURF_ID='INERT'/ Obstruction #1c
&OBST XB=5.3,5.5,9.0,10.0,0.0,2.4, SURF_ID='INERT'/ Obstruction #4
&OBST XB=5.1,5.3,2.0,3.0,0.0,2.0, RGB=153,51,0, SURF_ID='Leak_door'/ Door

&VENT SURF_ID='Fire', XB=2.0,3.0,2.0,3.0,0.0,0.0/ Fire block
&VENT SURF_ID='OPEN', XB=0.0,0.0,6.0,7.0,0.0,2.0/ Vent #2

&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBZ=1.0/
&SLCF QUANTITY='PRESSURE', PBZ=1.0/
&SLCF QUANTITY='DENSITY', PBZ=1.0/

&TAIL /

PS: I will be out of office for the next 2 weeks and may not have access to internet.

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image002.jpg@01D0D11E.06FE0840]

**Comment by mcgratta** [comment] 2015-09-24 19:32
Is the issue resolved?

**Comment by kinmanwong** [comment] 2015-09-28 15:38
Hi Kevin

Thanks for your email.

I’m afraid the issue had not been resolved. The case is not large for me to present to you and I am not able to repeat the error with a simplified model.

Kin

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image003.jpg@01D0F9C9.0388BCE0]

**Comment by mcgratta** [comment] 2015-09-28 15:51
We have this same problem from time to time with the Fortran compiler we use (Intel Fortran). We find a problem, and we report the bug to Intel. They cannot fix the problem unless I present a simpler version of the code. I cannot present them 100,000 lines of code and tell them to fix the problem. But I cannot present them a "simpler" version of FDS. Sometimes, however, I am able to pinpoint the exact line of code that causes the problem, and I show that when I remove the line or write it differently, the problem is solved. Can you do this with your case?

**Comment by kinmanwong** [comment] 2015-09-28 15:56
I will try my best to work on it. It will probably take some time but I will report to you. Thanks a ton.

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image003.jpg@01D0F9CB.754FB660]

**Comment by mcgratta** [comment] 2015-12-23 19:38
I am closing this issue. If new problems arise, start a new issue.

**Closed as completed by mcgratta** 2015-12-23 19:38 UTC

**Comment by kinmanwong** [comment] 2015-12-24 17:20
Thank you.

Kin Man Wong, M.Sc., P.Eng., CP
[cid:image003.jpg@01D13E2C.4BA82950]
