### ISSUE TITLE
ERROR: Numerical Instability - FDS stopped (CHID: G-70)

### ISSUE THREAD

**Issue by 123yiyiyi** [firemodels/fds#12250] opened 2023-11-29 02:39 UTC
hi, I`m trying to set up a fire insulation material for high-rise buildings, but there is a problem of numerical instability after 200s of simulation. May I ask why?
[G-70.fds.txt](https://github.com/firemodels/fds/files/13495488/G-70.fds.txt)

**Comment by mcgratta** [comment] 2023-11-29 14:39
What version of FDS are you using? Have you looked at the Plot3D output that is created when the job fails and identified where the problem is occurring? Is there something special happening at 200 s, like the activation of a sprinkler or opening or closing of a door?

**Comment by 123yiyiyi** [comment] 2023-11-30 02:44
> With the latest version of FDS, this case does not run due to an imbalance in the reaction stoichiometry. Clean that up, and if possible simplify the case. There are over 105,000 lines of input for this case. Unless there are an obvious problem in the setup, it will be almost impossible to find the cause of the instability.

Thank you so much for your help! I have simplified the model and found that it may be a problem that the grid boundaries are not sufficiently open. But I also wonder if it is because I set the complex reaction of polyurethane in FDS users, the atomic weight of C25H42O6 is too large.

**Comment by 123yiyiyi** [comment] 2023-12-01 01:44
I see. I'm trying. Thank you.

**Comment by 123yiyiyi** [comment] 2023-12-04 03:41
hi, I want to realize that the facade insulation material gradually disappears with burning to judge its damage. However, the obstructions of 2021 pyrosim does not disappear gradually as the grid burns, but disappears in a whole block, which makes me have to divide many small obstacles to achieve my goal. But in the 2016 version, the material can gradually disappear as the grid burns. Is there any good way to solve this problem?

**Comment by mcgratta** [comment] 2023-12-04 15:22
`BURN_AWAY=T` on the `SURF` line and `BULK_DENSITY` on the `OBST` line.

**Closed as completed** 2023-12-12 21:31 UTC
