### ISSUE TITLE
UGLMAT/GLMAT and network access

### ISSUE THREAD

**Issue by pathenri** [firemodels/fds#10692] opened 2022-06-20 13:31 UTC
I  am trying to understand why all my UGLMAT/GLMAT runs stopped unexpectedly at the exact same time, while the FFT kept running (same cases as the GLMAT). The only event that coincided with the sudden stop is my internet connection getting rebooted. So I ran the handy glmat test case "tunnel_demo_glmat.fds" from the Examples directory to investigate the matter. I use the binary version of FDS 6.7.7 on a windows PC. This is what I get when stopping the internet connection during the run:

 Starting FDS ...

 MPI Process      0 started on Perf1

 Reading FDS input file ...

 Fire Dynamics Simulator

 Current Date     : June 19, 2022  03:33:19
 Revision         : FDS6.7.7-0-gfe0d4ef38-release
 Revision Date    : Thu Nov 18 17:10:22 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Fri 11/19/2021  08:57 AM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.4 for Windows* OS

 Job TITLE        : Example of a tunnel simulation
 Job ID string    : tunnel_demo_glmat

 Time Step:      1, Simulation Time:      0.16 s
 Time Step:      2, Simulation Time:      0.32 s
 Time Step:      3, Simulation Time:      0.46 s
 Time Step:      4, Simulation Time:      0.58 s
 Time Step:      5, Simulation Time:      0.70 s
 Time Step:      6, Simulation Time:      0.79 s
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
libfabric.dll      00007FF87B1AC5BC  Unknown               Unknown  Unknown
libfabric.dll      00007FF87B123FCD  Unknown               Unknown  Unknown
libfabric.dll      00007FF87B127194  Unknown               Unknown  Unknown
libfabric.dll      00007FF87B12771F  Unknown               Unknown  Unknown
libfabric.dll      00007FF87B125B11  Unknown               Unknown  Unknown
impi.dll           00007FF851A0E62A  Unknown               Unknown  Unknown
impi.dll           00007FF8519CBD7D  Unknown               Unknown  Unknown
impi.dll           00007FF8517C3715  Unknown               Unknown  Unknown
impi.dll           00007FF8517C2CD4  Unknown               Unknown  Unknown
impi.dll           00007FF851753CDC  Unknown               Unknown  Unknown
impi.dll           00007FF8519A65EF  Unknown               Unknown  Unknown
impi.dll           00007FF8519A6234  Unknown               Unknown  Unknown
impi.dll           00007FF851906E3F  Unknown               Unknown  Unknown
impi.dll           00007FF851A4C34C  Unknown               Unknown  Unknown
impi.dll           00007FF851A2DAC3  Unknown               Unknown  Unknown
impi.dll           00007FF8519C48F6  Unknown               Unknown  Unknown
impi.dll           00007FF8518F937F  Unknown               Unknown  Unknown
impi.dll           00007FF8519076C4  Unknown               Unknown  Unknown
fds.exe            00007FF7BB595A28  Unknown               Unknown  Unknown
fds.exe            00007FF7BB00371E  Unknown               Unknown  Unknown
fds.exe            00007FF7BAFBC81A  Unknown               Unknown  Unknown
fds.exe            00007FF7BAFB9CFC  Unknown               Unknown  Unknown
fds.exe            00007FF7C284549C  Unknown               Unknown  Unknown
fds.exe            00007FF7C2706473  Unknown               Unknown  Unknown
fds.exe            00007FF7C26CAA46  Unknown               Unknown  Unknown
fds.exe            00007FF7C26897EE  Unknown               Unknown  Unknown
fds.exe            00007FF7C30D6AE4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF8B3DF7034  Unknown               Unknown  Unknown
ntdll.dll          00007FF8B4D22651  Unknown               Unknown  Unknown

If I leave the internet connection on, it goes all the way and exits gracefully.
If I try to start the job without internet, then it hangs up at:
Reading FDS input file ...

If I replace GLMAT by FFT then no effect from my internet connection.
I  re-tried the experiment after rebooting my computer, and same result: (U)GLMAT fails to run.

Does the PARDISO library require some kind of steady network connection?
I am puzzled!
Can anyone reproduce that issue on their computer or is it just mine ?

Cheers,

Pat

**Comment by marcosvanella** [comment] 2022-06-20 16:30
Hi Pat, both UGLMAT and GLMAT use the cluster version of the mkl pardiso library. Running one process jobs (or more processes in a single computer) should not be affected by having or not having internet connection. I'll try the tunnel case in windows tomorrow and let you know what I find. Can you see if you can reproduce this with the latest version 6.7.8? ThanksReply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by pathenri** [comment] 2022-06-20 17:57
Hi Marcos, I can only have access to 6.7.1 and 6.7.7 on my company desktop. On 6.7.1, I get the same error, but it has been more verbose during the crash:
it complains about FDS_ip_PRESSURE_I and MAIN_ routines in main.f90 (line 621, and 1262).
I have a colleague who does not have that problem, and he has a similar machine and the same version of FDS as me. I don't understand, I will check with my IT department what they can think of (again with FFT, not a problem). Cheers.

**Comment by marcosvanella** [comment] 2022-06-20 20:17
What windows version are you using?On Jun 20, 2022 1:57 PM, pathenri ***@***.***> wrote:
Hi Marcos, I can only have access to 6.7.1 and 6.7.7 on my company desktop. On 6.7.1, I get the same error, but it has been more verbose during the crash:
it complains about FDS_ip_PRESSURE_I and MAIN_ routines in main.f90 (line 621, and 1262).
I have a colleague who does not have that problem, and he has a similar machine and the same version of FDS as me. I don't understand, I will check with my IT department what they can think of (again with FFT, not a problem). Cheers.

**Comment by pathenri** [comment] 2022-06-20 21:36
Windows 10 Enterprise version 21H2.

**Comment by marcosvanella** [comment] 2022-06-21 19:43
I tried the tunnel_demo_glmat case on my windows computer here, both disconnecting the internet (ethernet cable), reconnecting and starting the job without internet connection, using different number of OMP threads. I could not reproduce this mysterious issue, I used version 6.7.7 and have Windows 10 Enterprise 20H2. I cannot tell you what is going on with your machine. Something I noted was that I had to allow access to several windows defender screens, one for mpiexec.exe. Not sure if this is something you have to do all the time. 
I would talk to you IT people regarding permissions in the machine, and also there is a maintenance release coming up this week. I would have the IT people install this upcoming release with latest intel compilers and libraries and test it.

**Comment by pathenri** [comment] 2022-06-21 20:24
Thanks for your time on this Marcos. It looks like under the hood, some parts of our file system are available online only. I have the feeling the pardiso library or something else specific to the glmat solvers triggers an indirect call to some zone that is not "there" when offline. I thought I had bypassed that by installing FDS on my local drive, I even restricted the environment variables (fdspath.bat) to only what fds needs before running a long job. That works for FFT but not for GLMAT :(  I'll have my IT look further into it. If we ever find what it was, I'll report back on the Forum. For now we can close the issue I guess.

**Comment by marcosvanella** [comment] 2022-06-21 21:13
So just to make sure, you use the CMDfds terminal and run with **fds_local -p 1 case.fds**  correct?
what is puzzling on the original post is that the exception happens in the libfabric.dll library. Fabrics are libs that manage at a low level the communication among processes for different types of networks (local, ethernet, infiniband). 
Try after opening the CMDfds running the case with **mpiexec -n 1 -env OMP_NUM_THREADS 1 case.fds**, to see if the -localonly flag fds_local adds is interfering with your system setup.

**Comment by pathenri** [comment] 2022-06-21 21:45
Yes, fds_local case.fds is what I use (I don't bother with -p 1 though when I do serial). I'll give the explicit mpiexec command a try tonight when my current fds job completes (don't want to lose that one when I disconnect!). Thanks.

**Comment by pathenri** [comment] 2022-06-22 16:16
I tried the mpiexec without the local flag. The job still gets interrupted when I disconnect the internet :(
I'll let IT take it from there and check the extent of my permissions. If they figure out something, I'll let you know. Cheers.

**Comment by marcosvanella** [comment] 2022-06-22 17:52
Ok, thanks. I'll close the issue but let us know if you have any additional info.

**Closed as completed by marcosvanella** 2022-06-22 17:52 UTC
