### ISSUE TITLE
Seg fault in HVAC routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8835] opened 2020-10-12 18:54 UTC
This case creates an overflow integer in the HVAC loop
```
Newton method to find solution of T (and hence cpbar) from enthalpy
```
ETOT appears to go bad sending temperature to a fictitiously high value

```
&HEAD CHID='untitled'/
&TIME T_END=10.0/
&DUMP DT_RESTART=300.0, DT_SL3D=0.25/
&MISC TMPA=42.0/

&MESH ID='Mesh02-a-a-merged-a-a-a-merged-a-merged-b', IJK=34,164,28, XB=-3.35,3.45,96.6,129.4,0.0,5.6/

&DEVC ID='Node31', QUANTITY='NODE TEMPERATURE', NODE_ID='Node31'/
&DEVC ID='GAS', QUANTITY='TEMPERATURE', XYZ=0.05,102.0,2.0/

&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      ADIABATIC=.TRUE./

&OBST ID='Obstruction', XB=-1.15,1.05,105.8,109.8,4.2,4.6, COLOR='INVISIBLE', THICKEN=.TRUE., SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=-1.15,1.05,119.4,123.4,4.2,4.6, RGB=153,255,255, THICKEN=.TRUE., SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=-1.55,-1.35,104.2,125.2,1.4,3.8, THICKEN=.TRUE., SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-1.35,-1.15,104.2,125.2,1.0,4.2, THICKEN=.TRUE., SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-1.15,0.85,104.2,125.2,0.8,4.2, THICKEN=.TRUE., SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=0.85,1.45,104.2,125.2,1.0,4.2, THICKEN=.TRUE., SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=1.45,1.65,104.2,125.2,1.6,3.0, THICKEN=.TRUE., SURF_ID='INERT'/ 

&VENT ID='Vent18', SURF_ID='HVAC', XB=-0.95,-0.55,106.8,107.4,4.6,4.6/ 
&VENT ID='Vent19', SURF_ID='HVAC', XB=-0.95,-0.55,106.0,106.6,4.6,4.6/ 
&VENT ID='Vent22', SURF_ID='HVAC', XB=-0.35,0.05,106.8,107.2,4.6,4.6/ 
&VENT ID='Vent23', SURF_ID='HVAC', XB=-0.35,0.05,106.2,106.6,4.6,4.6/ 
&VENT ID='Vent20', SURF_ID='HVAC', XB=0.25,0.65,106.8,107.4,4.6,4.6/ 
&VENT ID='Vent21', SURF_ID='HVAC', XB=0.25,0.65,106.0,106.6,4.6,4.6/ 
&VENT ID='Vent354', SURF_ID='HVAC', XB=0.45,0.85,122.8,123.4,4.6,4.6/ 
&VENT ID='Vent353', SURF_ID='HVAC', XB=0.45,0.85,122.0,122.6,4.6,4.6/ 
&VENT ID='Vent358', SURF_ID='HVAC', XB=-0.15,0.25,122.8,123.2,4.6,4.6/ 
&VENT ID='Vent356', SURF_ID='HVAC', XB=-0.75,-0.35,122.8,123.4,4.6,4.6/ 
&VENT ID='Vent357', SURF_ID='HVAC', XB=-0.15,0.25,122.2,122.6,4.6,4.6/ 
&VENT ID='Vent355', SURF_ID='HVAC', XB=-0.75,-0.35,122.0,122.6,4.6,4.6/ 
&VENT ID='Vent', SURF_ID='OPEN', XB=-3.35,3.45,129.4,129.4,0.0,5.6/ 

&HVAC ID='Duct23', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node30','Node180', ROUGHNESS=1.0E-3, LENGTH=0.214591/
&HVAC ID='Node180', TYPE_ID='NODE', DUCT_ID='Duct23','Duct155', XYZ=0.606917,106.406895,4.5/
&HVAC ID='Duct155', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node180','Node181', ROUGHNESS=1.0E-3, LENGTH=0.6/
&HVAC ID='Node181', TYPE_ID='NODE', DUCT_ID='Duct155','Duct154','Duct158', XYZ=6.917187E-3,106.406895,4.5/
&HVAC ID='Duct154', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node177','Node181', ROUGHNESS=1.0E-3, LENGTH=0.6/
&HVAC ID='Duct158', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node181','Node31', ROUGHNESS=1.0E-3, LENGTH=0.364701/
&HVAC ID='Node28', TYPE_ID='NODE', DUCT_ID='Duct21', VENT_ID='Vent18'/
&HVAC ID='Node27', TYPE_ID='NODE', DUCT_ID='Duct24', VENT_ID='Vent19'/
&HVAC ID='Node25', TYPE_ID='NODE', DUCT_ID='Duct27', VENT_ID='Vent22'/
&HVAC ID='Duct27', TYPE_ID='DUCT', AREA=0.16, PERIMETER=1.6, FAN_ID='Fan01', NODE_ID='Node32','Node25', LENGTH=0.234335/
&HVAC ID='Duct26', TYPE_ID='DUCT', AREA=0.16, PERIMETER=1.6, FAN_ID='Fan01', NODE_ID='Node32','Node26', LENGTH=0.377003/
&HVAC ID='Node26', TYPE_ID='NODE', DUCT_ID='Duct26', VENT_ID='Vent23'/
&HVAC ID='Node32', TYPE_ID='NODE', DUCT_ID='Duct27','Duct26','Duct25', XYZ=-0.093083,106.772682,4.6/
&HVAC ID='Node30', TYPE_ID='NODE', DUCT_ID='Duct23', VENT_ID='Vent21'/
&HVAC ID='Duct21', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node28','Node178', ROUGHNESS=1.0E-3, LENGTH=0.1862/
&HVAC ID='Node178', TYPE_ID='NODE', DUCT_ID='Duct21','Duct157', XYZ=-0.593083,107.106895,4.5/
&HVAC ID='Duct157', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node178','Node182', ROUGHNESS=1.0E-3, LENGTH=0.6/
&HVAC ID='Node182', TYPE_ID='NODE', DUCT_ID='Duct157','Duct159','Duct156', XYZ=6.917187E-3,107.106895,4.5/
&HVAC ID='Duct159', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node182','Node31', ROUGHNESS=1.0E-3, LENGTH=0.335299/
&HVAC ID='Node29', TYPE_ID='NODE', DUCT_ID='Duct22', VENT_ID='Vent20'/
&HVAC ID='Node179', TYPE_ID='NODE', DUCT_ID='Duct22','Duct156', XYZ=0.606917,107.106895,4.5/
&HVAC ID='Duct22', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node29','Node179', ROUGHNESS=1.0E-3, LENGTH=0.1862/
&HVAC ID='Duct25', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, AIRCOIL_ID='Aircoil', NODE_ID='Node31','Node32', LENGTH=0.141426/
&HVAC ID='Node31', TYPE_ID='NODE', DUCT_ID='Duct158','Duct159','Duct25', XYZ=6.917187E-3,106.771596,4.5/
&HVAC ID='Duct156', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node179','Node182', ROUGHNESS=1.0E-3, LENGTH=0.6/
&HVAC ID='Duct24', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node27','Node177', ROUGHNESS=1.0E-3, LENGTH=0.214591/
&HVAC ID='Node177', TYPE_ID='NODE', DUCT_ID='Duct154','Duct24', XYZ=-0.593083,106.406895,4.5/
&HVAC ID='Duct592', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node651','Node657', ROUGHNESS=1.0E-3, LENGTH=0.214591/
&HVAC ID='Node657', TYPE_ID='NODE', DUCT_ID='Duct592','Duct596', XYZ=0.493083,122.993105,4.5/
&HVAC ID='Duct589', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node652','Node658', ROUGHNESS=1.0E-3, LENGTH=0.1862/
&HVAC ID='Node658', TYPE_ID='NODE', DUCT_ID='Duct589','Duct599', XYZ=0.493083,122.293105,4.5/
&HVAC ID='Duct599', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node658','Node662', ROUGHNESS=1.0E-3, LENGTH=0.6/
&HVAC ID='Node662', TYPE_ID='NODE', DUCT_ID='Duct599','Duct598','Duct601', XYZ=-0.106917,122.293105,4.5/
&HVAC ID='Duct598', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node659','Node662', ROUGHNESS=1.0E-3, LENGTH=0.6/
&HVAC ID='Duct601', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node662','Node655', ROUGHNESS=1.0E-3, LENGTH=0.335299/
&HVAC ID='Node653', TYPE_ID='NODE', DUCT_ID='Duct590', VENT_ID='Vent355'/
&HVAC ID='Node659', TYPE_ID='NODE', DUCT_ID='Duct598','Duct590', XYZ=-0.706917,122.293105,4.5/
&HVAC ID='Duct590', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node653','Node659', ROUGHNESS=1.0E-3, LENGTH=0.1862/
&HVAC ID='Duct593', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node655','Node656', LENGTH=0.141426/
&HVAC ID='Node655', TYPE_ID='NODE', DUCT_ID='Duct601','Duct593','Duct600', XYZ=-0.106917,122.628404,4.5/
&HVAC ID='Duct591', TYPE_ID='DUCT', AREA=0.24, PERIMETER=2.0, NODE_ID='Node654','Node660', ROUGHNESS=1.0E-3, LENGTH=0.214591/
&HVAC ID='Node660', TYPE_ID='NODE', DUCT_ID='Duct591','Duct597', XYZ=-0.706917,122.993105,4.5/
&HVAC ID='Duct597', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node660','Node661', ROUGHNESS=1.0E-3, LENGTH=0.6/
&HVAC ID='Node661', TYPE_ID='NODE', DUCT_ID='Duct597','Duct596','Duct600', XYZ=-0.106917,122.993105,4.5/
&HVAC ID='Duct596', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node657','Node661', ROUGHNESS=1.0E-3/
&HVAC ID='Duct600', TYPE_ID='DUCT', AREA=3.6, PERIMETER=7.6, NODE_ID='Node661','Node655', ROUGHNESS=1.0E-3, LENGTH=0.364701/
&HVAC ID='Node651', TYPE_ID='NODE', DUCT_ID='Duct592', VENT_ID='Vent354'/
&HVAC ID='Node650', TYPE_ID='NODE', DUCT_ID='Duct594', VENT_ID='Vent358'/
&HVAC ID='Node654', TYPE_ID='NODE', DUCT_ID='Duct591', VENT_ID='Vent356'/
&HVAC ID='Node649', TYPE_ID='NODE', DUCT_ID='Duct595', VENT_ID='Vent357'/
&HVAC ID='Node652', TYPE_ID='NODE', DUCT_ID='Duct589', VENT_ID='Vent353'/
&HVAC ID='Node656', TYPE_ID='NODE', DUCT_ID='Duct593','Duct594','Duct595', XYZ=-6.917187E-3,122.627318,4.6/
&HVAC ID='Duct594', TYPE_ID='DUCT', AREA=0.16, PERIMETER=1.6, FAN_ID='Fan01', NODE_ID='Node656','Node650', LENGTH=0.377003/
&HVAC ID='Duct595', TYPE_ID='DUCT', AREA=0.16, PERIMETER=1.6, FAN_ID='Fan01', NODE_ID='Node656','Node649', LENGTH=0.234335/
&HVAC ID='Fan01', TYPE_ID='FAN', TAU_FAN=-5.0, VOLUME_FLOW=2.0/
&HVAC ID='Aircoil', TYPE_ID='AIRCOIL', FIXED_Q=35.0, RAMP_ID='Aircoil_RAMP_ID'/
&RAMP ID='Aircoil_RAMP_ID', T=0.0, F=0.0, DEVC_ID='GAS'/
&RAMP ID='Aircoil_RAMP_ID', T=10.0, F=0.0/
&RAMP ID='Aircoil_RAMP_ID', T=20.0, F=0.0/
&RAMP ID='Aircoil_RAMP_ID', T=30.0, F=1.0/
&RAMP ID='Aircoil_RAMP_ID', T=40.0, F=1.0/
&RAMP ID='Aircoil_RAMP_ID', T=50.0, F=1.0/
&RAMP ID='Aircoil_RAMP_ID', T=52.0, F=1.0/
&RAMP ID='Aircoil_RAMP_ID', T=53.0, F=0.8/
&RAMP ID='Aircoil_RAMP_ID', T=54.0, F=0.6/
&RAMP ID='Aircoil_RAMP_ID', T=55.0, F=0.4/
&RAMP ID='Aircoil_RAMP_ID', T=56.0, F=0.3/
&RAMP ID='Aircoil_RAMP_ID', T=57.0, F=0.2/
&RAMP ID='Aircoil_RAMP_ID', T=58.0, F=0.0/
&RAMP ID='Aircoil_RAMP_ID', T=60.0, F=0.0/
&RAMP ID='Aircoil_RAMP_ID', T=70.0, F=0.0/


&TAIL /
```

**Comment by drjfloyd** [comment] 2020-10-12 19:35
A couple of problems I see just inspecting the case.

The FAN has a 5 s t^2 ramp. TMPA is 42. This means the RAMP for the AIRCOIL will return 1 and at the start of the case the AIRCOIL will be trying to add 35 kW to a very low amount of flow. If the initial timestep is 0.1 s, then the initial volume flow will be 0.1^2/5^2 * 0.2 = 0.00008. Dumping 35 kW into this will result in a temperature over 400,000 K (I ignored the TAU of 1 for the AC but still it looks like the issue is too much heat into too little flow).

This case is predicting HVAC flow (there are multiple tees in the system) but lacks losses in system. Add appropriate losses to the network. At a minimum there will be entrance and exit losses at each connection to a VENT or AMBIENT and for any node with more than two ducts connected to it will also have significant losses. Non-physical duct and node definitions can easily result in non-physical behavior

**Comment by rmcdermo** [comment] 2020-10-12 19:40
Jason,
Again, I would recommend adding default losses for the components of the network.  If we spell out what these are in the .out file, I think it is sufficient.  The losses for inlets, exits, tees, friction loss per unit length, etc. are pretty standard.  I do not see why we have to specify these every time.

**Comment by drjfloyd** [comment] 2020-10-12 19:45
Losses depend on the types and number of fittings, diameter, shape, change in flow area, type of duct material, type of duct construction, etc. Anything I pick as a default is basically guaranteed not to result in a prediction of the true behavior of the system.

**Comment by rmcdermo** [comment] 2020-10-12 19:49
My view is that this is true of many of the defaults we put in the code to get it to run.

I would use K factors of 1 or 0.5, in that range, and print these in the .out file.  This is better than crashing the code.

**Comment by rmcdermo** [comment] 2020-10-12 19:53
Option B should be to simply stop with an ERROR if the loss coefficient is not specified.

**Comment by drjfloyd** [comment] 2020-10-12 19:54
If someone is modeling HVAC in a performance based design, that generally means its functionality is contributing to a life safety objective. Bad default vales could easily result in a design passing that would really fail. 

We don't define a default fire size, a default soot yield, a default CO yield.

**Comment by drjfloyd** [comment] 2020-10-12 20:01
We crossed paths. I'll add a section to the User's Guide discussing predictive vs. prescriptive HVAC inputs. 

The error option isn't trivial as there are many ways to specify losses that would get you a valid solution.  If have a duct with two nodes and a fan, I can give losses at each node and in the duct, put all the losses as effective duct losses, or put all the losses as an effective loss at one node. Now add a second duct connected to the first (with another node). This will need a recursive routine that checks every possible permutation of flow direction to ensure that any continuous segment of duct somehow has a flow loss.

**Comment by mcgratta** [comment] 2020-10-12 20:06
Whatever you do, avoid a seg fault or invalid floating error. Even if you
have to ERROR out of the HVAC routine during run time.

>

**Comment by rmcdermo** [comment] 2020-10-12 20:06
Is there some concept like a "minimum loss for stability"?  I think of something like the molecular viscosity for DNS very the turbulent viscosity for LES.  If all components of the system had a very small loss, it would act as a stability mechanism, allowing the code to function, but would not get in the way of specified losses for design purposes.

**Comment by drjfloyd** [comment] 2020-10-12 20:19
I don't think there is one characteristic loss. I could have a simulation where the networks sees only fractions of Pa change in pressure at its VENTs or I could have simulation with a fire in closed room where the network sees 100s of Pa.

**Comment by rmcdermo** [comment] 2020-10-12 20:21
Right... this would not be physical.  It would be numerical default set at fractions of a Pa.  This prevents instability.  Then anyone doing design will be specifying the losses needed.  Just like anyone who cares about smoke must specify the soot yield.

**Comment by drjfloyd** [comment] 2020-10-12 21:14
For the aircoil power issue which would be better: Forcing a stop if we wind up with a node temperature over 5000 K or forcing a clip using the CLIP value?

There are two ways HVAC can work. You can specify the flow, in which case no losses are needed. You can predict the flow in which case you need to define the losses. I don't see an easy way we can do this as a default.

Say I have a duct that sees VENT pressures that differ by 1 Pa. I might keep things stable with a default loss of 0.01 for each component (the two nodes and the duct). However, that would mean flow speeds of 7 m/s which would be unheard of in a real system for that kind of pressure. Sure FDS runs, but the result is meaningless. If instead the simulation had a fire in a closed room where I get to 100 Pa, using that same loss of 0.01 in each component would mean flows over 60 m/s. For this concept to work at each timestep there would have to be some assessment of how big to make the loss. That assessment would implicitly mean assuming something about the expected flow speeds in the system which can vary greatly depending on the specific type of system. 

I will add this text to the start of the HVAC chapter in the User's Guide:

A set of HVAC inputs will consist at a minimum of one or more interconnected sets of ducts and duct nodes. For any interconnected set of ducts and duct nodes, there are two basic methods in which that portion of the HVAC system can be defined. The first is prescribed flow. In this case inputs are provided such that the volume flow of gas is known in every duct segment in the interconnected set. For example, if the set consists of three ducts connected to a tee, then the system would be fully specified if two of the ducts had flows explicitly defined. In this example, the third duct's flow would be known from the conservation of mass at the tee. The second is predicted flow. In the second case, one or more duct segments in an interconnected set has an unknown flow. FDS must then rely upon prediction the pressure drop inside that segment of duct. In the second method, losses must be defined such that FDS can predict the pressure drop in any segment of duct where the flow is unknown. These inputs will be discussed in the sections that follow.

**Comment by rmcdermo** [comment] 2020-10-12 21:30
Well, for better or worse, right now I believe we CLIP temperatures above 5000 K.

Your addition to the user guide is good.  I go back to the idea that if the segment needs a loss and it has not been specified by the user, then I would throw an error.  Is that doable?

**Comment by drjfloyd** [comment] 2020-10-12 21:49
It is doable, it is just not trivial with the current flexibility in HVAC loss inputs. I could have a section of a system where the I have six nodes and five ducts connected together as a single length of duct. It would be valid for me to take all the losses and define them in just one node. As long as the total pressure drop over the length is correct, it doesn't matter how the losses get split up over the components. I would need to have logic to figure that somewhere along this collection of components that there was a loss. Now add in a tee where there are six combinations of flow (three combinations of in  one and out two and three combinations of in two and out one) to check to see if all possible paths have losses.

Error checking would be simpler if we made defining HVAC more restrictive and force user's to always define node losses with duct losses remaining optional (right now you can combine node losses into the losses of ducts). Then it would be a simpler case of seeing which duct segments don't have fixed flow (already have a routine for checking that) and checking to see if all the nodes have all the needed losses defined (we could allow for a loss of zero at an internal node connecting two ducts as that might needed in the case of a filter which must to be in a node). Any node connected to ambient or the FDS domain would physically have some kind of loss so we could force that a positive value be defined. I don't think that loss of flexibility is a big deal. It will mean FDS won't be backwards compatible with any old input files where only duct losses are provided.

**Comment by rmcdermo** [comment] 2020-10-12 22:16
Well, I see I've taken the "red pill".

I really did not intend to create any kind of massive work or overhaul.  Let me ask this, is there a way to look at the system as a whole and determine that not enough losses have been specified without necessarily pinpointing which segment or node?  If so, we could shutdown with a setup error.

**Comment by drjfloyd** [comment] 2020-10-12 23:36
If I have a system where at least one duct has its flow being solved, then there could be a simple check to see if there no losses defined at all and give an error. This would be easy to do and not having any losses when they are needed is a much more common error than having some but not enough losses. 

If some losses are defined, knowing whether or not it is enough losses would mean inspecting the network to make sure every flow path has a loss assigned to it somewhere in that path for both flow directions. In this case the idea in my prior post would not be terribly difficult to do. In the figure the duct from B to F and the two ducts from B to E have undefined flow. The user would have to give losses at B (for the ducts where flow is being solved),E, and F. Losses at C or in the ducts would be optional. I wouldn't have search along the flow path and figure out if somehow there is a loss since with this approach I don't care about ducts or a node connected to only two ducts. I just need to make sure end points of undefined flow paths are all fully defined. The error message would be easy. I just give the node and say it needs losses. I already have a routine where I figure out which ducts have flow specified and which need flow solved. 

Right now the HVAC solver would be perfectly happy if the losses B to F and B to E were combined into losses in just the ducts connected to B. This approach would not allow those as the only losses. Keeping this ability would make the checking process more difficult especially if additional tees start getting thrown in the mix as FDS would have to march through the network and see if somewhere it comes up with a uniquely assigned loss to all flow paths in both directions. For example if nothing in the figure was defined, then node F and its duct could not have any losses as long as somewhere in both A-B and B-E have losses in both directions. If that were true, then any flow direction in F would see a loss in the solution process.

![image](https://user-images.githubusercontent.com/12799217/95797259-0bb9a480-0cbd-11eb-8b15-d03d439bd7af.png)

**Comment by rmcdermo** [comment] 2020-10-13 11:40
I would start with the first, simple check and go from there.  My bet is that, as you said, this is the most common error.  It would at least force the user to open the manual.

**Comment by drjfloyd** [comment] 2021-12-16 16:57
The PR adds:

-A check in the aircoil routine to see if a FIXED_Q drops the temperature below 0 or above I_TMP_MAX. If it does it limits FIXED_Q. 
-A routine in the HVAC setup to see if at least some loss is defined for any flow path in a system where the flow is not specified. The check just looks to see if any LOSS array entry as been set and doesn't check all possible permutations of flow direction. Typical error is specifying no losses when they are needed so this should at least catch that.
-Add some discussion to User's Guide about specified flow vs unspecified flow networks and why the later needs losses.

**Closed as completed** 2022-06-21 13:24 UTC
