### ISSUE TITLE
Numerical instability on NS2D verification cases using GCC on linux machines

### ISSUE THREAD

**Issue by marcfehling** [firemodels/fds#4757] opened 2017-02-24 14:49 UTC
Dear FDS community,

I am currently playing around with the verification of FDS, but running any of the NS2D tests in their present form located in Verification/NS_Analytical_Solution yields to errors, namely:
`STOP: Numerical Instability (CHID: ns2d_64)`

This error can only be a result from unmet conditions in line 1741 of velo.f90.
`IF (DT_NEW(NM)<DT_INITIAL*LIMITING_DT_RATIO .AND. (T+DT_NEW(NM)<(T_END-TWO_EPSILON_EB))) STOP_STATUS = INSTABILITY_STOP`

Interestingly, this error only occurs using GCC compilers on linux machines. I tried both GCC 6.3.1 and 5.4.0 on Archlinux and CentOS releases resulting in the above errors. Interestingly, using both versions of GCC on MacOS or using the Intel compiler (on any machine) will run all simulations as intended. I have not tried this on Windows machines, though.

Even more interesting, the time steps differ: For example for ns2d_64.fds, configurations resulting in errors use time steps of size 0.155e-1. In the working configurations, the time step is 0.539e-2. This may be a hint on the solution of the problem.

Using locked time step sizes or other tests with dynamically chosen time steps are working correctly, though. Here, the time step sizes are equal.

I am not able to localize the issue any further, but I hope that this information is sufficient. These investigations were carried out using revision FDS6.5.3-825-g2b102fcfb.

Best regards,
Marc Fehling

**Comment by rmcdermo** [comment] 2017-02-24 14:54
I'll have a look.

**Comment by rmcdermo** [comment] 2017-02-24 15:52
Unfortunately, everything runs fine on our system.  We have CentOS 6 and GCC

gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)

I'll leave this open for now in case @gforney has any ideas on what we could try.

**Comment by marcfehling** [comment] 2017-02-28 18:58
I was able to locate the occurrence of the error in the commit history.

First occurrence of error: commit [76a282d](https://github.com/firemodels/fds/commit/76a282d7a63f4e4a6a6a1a0f45331da60454a360) (Feb 18, 2017)
Working fine: commit [ce896eb](https://github.com/firemodels/fds/commit/ce896ebe7084a41923bb5a71ee599a3ba399d012) (Feb 17, 2017)

**Comment by rmcdermo** [comment] 2017-02-28 20:32
Thanks.  This is helpful.

@drjfloyd Do you see anything I'm doing in that commit that is not OK?

**Comment by rmcdermo** [comment] 2017-02-28 22:36
OK, we are making progress... we got things to crash here using OS X 10.11 with gfortran 6.3.1.

**Comment by drjfloyd** [comment] 2017-02-28 23:31
Nothing immediately jumps out at me as a problem.

**Comment by marcosvanella** [comment] 2017-03-01 20:49
Hi Marc, testing with OSX we were able to reproduce the problem. 
It looks like a stack memory size/use problem when using the -O2 optimization flag. Precluding routines of using stack memory adding the -fno-automatic gfortran compile flag seems to fix it in OSX. I've read this can make the application slower but it's a start point.

Check if adding this flag to your Linux targets gives you the right result for ns2d.
As of exactly why this is happening, it's not clear to us. Maybe someone at the JSC supercomputing centre can help?

**Comment by sbenkorichi** [comment] 2017-03-01 21:23
Hi all, 
Just a feedback, I've tested it on my OS Centos 7 with gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
It works fine.

Kind regards,
Salah

**Comment by rmcdermo** [comment] 2017-03-01 21:31
Thanks.  Yes, all seems fine up to gcc 4.9.2, which is what we have on our linux cluster.

**Comment by marcfehling** [comment] 2017-03-02 08:46
Hi Marco,
using the '-fno-automatic' flag fixes the problem on GCC 6.3.1 and 5.4.0 on both machines.
I will try to find out who at JSC could help us with that issue.
Best,
Marc

**Comment by marcosvanella** [comment] 2017-03-02 15:36
Hi Marc,
Good, thank you. It's an interesting issue.

I have a question on your linux system. Could you run the command 
`>>ulimit -a`
on your command window and show me what you get? I'm interested in the stack size you are using. In my Mac this size is set to a hard limit of 64KB. 

We'll leave the case open for now, so we can post if anyone gets new insights.

Best,
Marcos

**Comment by marcfehling** [comment] 2017-03-03 13:19
Hi Marcos!

My local machine running Archlinux with GCC 6.3.1:
```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62049
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62049
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Our cluster running CentOS with GCC 5.4.0:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1030313
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) 7200
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Best,
Marc

**Comment by marcosvanella** [comment] 2017-03-03 15:03
Hi Marc, I was trying to infer if the problem has to do with the stack size defined in your systems. It doesn't look that way as your second machine has unlimited stack size defined.
We need a software engineer to look at this.
Best,
Marcos

**Comment by marcfehling** [comment] 2017-03-08 13:41
Dear community,

we can report some progress in the location of the error.
We commented out every occurance of the newly introduced `ONE_D_WORK1-8` variables to check if their allocation would be the problem. Interestingly, only lines 149&150 of file `mesh.f90` of commit 76a282d seem to play a role on this issue.

Error occurs:
```
REAL(EB), ALLOCATABLE, DIMENSION(:) :: ONE_D_WORK1,ONE_D_WORK2,ONE_D_WORK3,ONE_D_WORK4,&
                                       ONE_D_WORK5,ONE_D_WORK6,ONE_D_WORK7
```
Working fine:
```
REAL(EB), ALLOCATABLE, DIMENSION(:) :: ONE_D_WORK1,ONE_D_WORK2,ONE_D_WORK3,ONE_D_WORK4,&
                                       ONE_D_WORK5,ONE_D_WORK6
```

It seems like the overlying `MESH_TYPE` type somehow reaches critical mass. Trying the `-frecursive` flag to put everything on stack does not solve the problem. Up to this point, only completely omitting the stack memory with `-fno-automatic` seems to fix it.

Best,
Marc

**Comment by rmcdermo** [comment] 2017-03-08 14:26
Hi Marc,

We found the same.  Given that older versions of GCC work, to me this suggests a compiler bug has been introduced.  There does not seem to be anything wrong with the code.  Is it possible for you to dial back to GCC 4.9, or better yet, get the Intel compiler; FDS will run significantly faster.

**Comment by marcosvanella** [comment] 2017-03-08 14:32
Hi Marc, that's right. We found the same behavior with the ONE_D_WORK arrays. 
The problem appears with -02 optimization on newer gfortran versions (5.0 up?) but not with -O1, or older gfortran versions (or ifort compilers). Also, the problem happens without allocation of these arrays. 
As Randy said, this is probably an issue with the compiler, beyond our control. Would be nice to get a gfortran developer to take a look at this.

**Comment by mcgratta** [comment] 2017-09-07 21:32
Is this still a problem with the latest version of the compiler?

**Comment by sbenkorichi** [comment] 2017-09-07 21:56
5 and 6 are having issues except from certain flavors such as CentOS ( 5.4 works fine) as for other flavors, they're not stables, and only old releases such as  4.7 and 4.8 are standing sound.

**Comment by mcgratta** [comment] 2017-09-08 15:44
I'm closing this issue. We cannot debug the Gnu Fortran compiler, and we don't have any indication that our coding is not correct.

**Closed as completed by mcgratta** 2017-09-08 15:44 UTC

**Comment by sbenkorichi** [comment] 2017-09-08 15:54
I agree, the problem with these latest releases are each time pointing to different piece of the code. I think it's better if one would take this issue to the Gnu developers.
