### ISSUE TITLE
CTRL: No devices output until event becomes true

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#9170] opened 2021-01-31 02:31 UTC
Could you please look into this?
I've noticed that the devices outputs file doesn't record any data until the unfreeze is true following the activation of the smoke detector.
Attached is a dummy example to replicate it with the latest bundle release (happens under Windows and Linux).
For this example, the data will only be dumped after the delay period passes. 
[dummy.txt](https://github.com/firemodels/fds/files/5899091/dummy.txt)

**Comment by drjfloyd** [comment] 2021-01-31 15:59
I'll take a look.

As a note you don't need three CTRL functions; you only need one. You can set LATCH for the smoke detector DEVC (actually the default value is already TRUE), use that as the input to the time delay CTRL, and use the time delay CTRL for the pressure DEVC.

**Comment by sbenkorichi** [comment] 2021-01-31 16:05
Cheers Jason, yeah I agree on this dummy example it could be simplified, my original case is more complex, I have a smoke exhaust ramps up/down based on a deadband using a pressure device, and I want the exhaust to turn on until the smoke detector is activated, that's why I had to freeze the pressure device at the start and then once it starts reading the exhaust fan will be activated. The issue is that I can't read any other devices until the smoke detector is activated (which could be a delay of 200 to 300s).

**Comment by drjfloyd** [comment] 2021-01-31 16:29
I see what you are seeing. It isn't immediately obvious what the problem is. The NO_UPDATE variables only appear in a couple of locations in dump.f90a and those aren't where outputs are being written. Toggling of outputs is controlled with the variable DV%OUTPUT but this is only set once in read.f90.

**Comment by drjfloyd** [comment] 2021-01-31 16:57
The problem is related to NO_UPDATE being true at the start. With this a TIME_INTERVAL isn't being set for the device which is causing the output writing routine not to be called. The fix is to make sure a TIME_INTERVAL is set but I'll need to make sure whatever we set still results in the correct output being written. This looks like maybe it never worked with a NO_UPDATE true at the start.

**Comment by sbenkorichi** [comment] 2021-01-31 17:42
Thanks, just forgot to mention that this was working fine with 6.7.0. I'll try to bisect and see at which point this has started occurring.

**Comment by sbenkorichi** [comment] 2021-01-31 21:03
I've tracked it down and it was due to this [commit](https://github.com/firemodels/fds/commit/94c53d695c8623b9989d7d8281ef9d4dcc6367de)

**Comment by drjfloyd** [comment] 2021-02-01 14:10
Should be fixed now. Changed your test case to have the NO_UPDATE cycle on and off a couple of times with it off at the start and this new case works fine.

&HEAD CHID='dummy', /

&MESH XB=0.,1.,0.,1.,0.,1.,IJK=20,20,20/

&TIME T_END=10.0/

&VENT XB=0.4,0.6,0.4,0.6,0.0,0.0,SURF_ID='FLOW'/
&SURF ID='FLOW',VEL=-0.05,COLOR='ORANGE'/

&CTRL ID='Unfreeze', FUNCTION_TYPE='CUSTOM', LATCH=.FALSE., INPUT_ID='P1',RAMP_ID='PRAMP'/
&DEVC ID='Pressure', QUANTITY='PRESSURE', XYZ=0.5,0.5,0.5, ID='P1'/
&DEVC ID='Pressure', QUANTITY='PRESSURE', XYZ=0.5,0.5,0.5, ID='P2',NO_UPDATE_CTRL_ID='Unfreeze'/

&RAMP ID='PRAMP',T=0,F=1/
&RAMP ID='PRAMP',T=90,F=1/
&RAMP ID='PRAMP',T=110,F=-1/
&RAMP ID='PRAMP',T=190,F=-1/
&RAMP ID='PRAMP',T=210,F=1/
&RAMP ID='PRAMP',T=290,F=1/
&RAMP ID='PRAMP',T=310,F=-1/

&TAIL /


![image](https://user-images.githubusercontent.com/12799217/106469473-58dca480-646d-11eb-8b65-01b85ce0ef30.png)

**Comment by sbenkorichi** [comment] 2021-02-01 21:08
Thanks, Jason, I've just had a chance to look at it. That did the trick, but for some reason, I'm not able to get the below case to work. 
Trying to unfreeze the pressure device following SD activation, which happens at near 4s, but prior to that, the other devices such as temperature don't dump anything until activation of SD. I tried to use that RAMP function but no luck. Could you please advise where am I getting wrong. 
Cheers,

`&HEAD CHID='dummy'/
&TIME T_END=10.0/

&MESH  IJK=20,20,20, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1/

&PROP ID='Cleary Ionization I1',
      QUANTITY='CHAMBER OBSCURATION',
      ALPHA_E=2.5,
      BETA_E=-0.7,
      ALPHA_C=0.8,
      BETA_C=-0.9/
&CTRL ID='unfreeze', FUNCTION_TYPE='ALL', LATCH=.FALSE., INITIAL_STATE=.TRUE., INPUT_ID='latch'/
&CTRL ID='latch', FUNCTION_TYPE='ALL', LATCH=.TRUE., INPUT_ID='SD', RAMP_ID='PRAMP'/
&DEVC ID='P1', QUANTITY='PRESSURE', XYZ=0.5,0.5,0.7/
&DEVC ID='P2', QUANTITY='PRESSURE', XYZ=0.5,0.5,0.7, NO_UPDATE_CTRL_ID='unfreeze'/
&DEVC ID='TEMPERATURE', QUANTITY='TEMPERATURE', XYZ=0.25,0.2,0.85/
&DEVC ID='SD', PROP_ID='Cleary Ionization I1', XYZ=0.65,0.35,0.85/

&SURF ID='FIRE',
      COLOR='ORANGE',
      HRRPUA=500.0/

&VENT ID='ZMAX', SURF_ID='OPEN', XB=0.0,1.0,0.0,1.0,1.0,1.0/ 
&VENT ID='ZMIN', SURF_ID='FIRE', XB=0.0,1.0,0.0,1.0,0.0,0.0/ 


&TAIL /`

**Comment by drjfloyd** [comment] 2021-02-01 21:41
I am seeing this. It looks to me like it is working OK.

![image](https://user-images.githubusercontent.com/12799217/106521446-3fa71880-64ac-11eb-91bc-8c251103c462.png)

**Comment by sbenkorichi** [comment] 2021-02-01 21:56
I've just compiled and tested it with the fix, it works perfect. My question earlier was more with regards to the current release if there is a work-around to this, but it's not a major thing and I can live with it till the next release.
I'm closing this now. Cheers for sorting.

**Closed as completed** 2021-02-01 22:00 UTC

**Comment by sbenkorichi** [comment] 2022-04-15 00:10
Hi Jason,

going back to this thread. 
For some reason, the above function that allows unfreezing an item until a certain condition is met isn't working in the FDS6.7.7 or (latest source code). When running it with fds6.7.5 it works fine. I'll check what happened between the two revisions but if you could advise in the meantime that would be of help. 
What I expect from the below example is the fan to turn on after detection is activated but it appears from the start and doesn't seem to be controlled. 
Thanks

```
&HEAD CHID='dummy'/
&TIME T_END=10.0/

&MESH ID='MESH', IJK=16,35,28, XB=-0.7,0.9,19.0,22.5,-0.2,2.6/


&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1,
      HEAT_OF_COMBUSTION=2.0E+4/

&PROP ID='Cleary Ionization I1',
      QUANTITY='CHAMBER OBSCURATION',
      ALPHA_E=2.5,
      BETA_E=-0.7,
      ALPHA_C=0.8,
      BETA_C=-0.9/
&CTRL ID='Pressure', FUNCTION_TYPE='DEADBAND', SETPOINT=-30.0,-15.0, ON_BOUND='UPPER', LATCH=.FALSE., INPUT_ID='pressure'/
&CTRL ID='Extract Detection', FUNCTION_TYPE='ALL', LATCH=.FALSE., INITIAL_STATE=.TRUE., INPUT_ID='latch'/
&CTRL ID='latch', FUNCTION_TYPE='ALL', LATCH=.TRUE., INPUT_ID='SD'/
&DEVC ID='pressure', QUANTITY='PRESSURE', XYZ=0.2,20.9,1.5, NO_UPDATE_CTRL_ID='Extract Detection'/
&DEVC ID='SD', PROP_ID='Cleary Ionization I1', XYZ=0.1,20.6,2.3/

&SURF ID='EXTRACT',
      COLOR='RED',
      VOLUME_FLOW=1.0/

&OBST ID='Obstruction', XB=-0.7,0.9,22.3,22.5,-0.2,2.6, SURF_ID='INERT'/ 

&VENT ID='fan', SURF_ID='EXTRACT', XB=-0.3,0.7,22.3,22.3,1.4,2.2, CTRL_ID='Pressure'/ 

&VENT MB='XMAX',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='ZMAX',SURF_ID='OPEN'/
&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/

&TAIL /
```

**Comment by drjfloyd** [comment] 2022-04-15 11:32
I'll take a look.

**Comment by drjfloyd** [comment] 2022-04-15 12:41
At t=0, PRESSURE is going to be near zero everywhere.  So this device will measure ~0 Pa:

&DEVC ID='pressure', QUANTITY='PRESSURE', XYZ=0.2,20.9,1.5, NO_UPDATE_CTRL_ID='Extract Detection'/

This control function says that when 'pressure' > -15 Pa (ON_BOUND='UPPER') , the value of the function is TRUE.  0 Pa > - 15 Pa so the control function is TRUE. The control function will stay true until 'pressure' < -30 Pa; however, with all the OPEN boundaries this is not going to happen.

&CTRL ID='Pressure', FUNCTION_TYPE='DEADBAND', SETPOINT=-30.0,-15.0, ON_BOUND='UPPER', LATCH=.FALSE., INPUT_ID='pressure'/

Your VENT input says to turn the fan on whenever the above control function is TRUE. The above control function is always TRUE so the fan is always on.

&VENT ID='fan', SURF_ID='EXTRACT', XB=-0.3,0.7,22.3,22.3,1.4,2.2, CTRL_ID='Pressure'/

**Comment by sbenkorichi** [comment] 2022-04-15 13:18
Hi Jason,
What you said above is true. I didn't want to complicate the input. I expect in this condition the fan not to turn on until the smoke detector is activated. I have frozen the pressure reading device, so the fan shouldn't be turned on until the pressure device is enabled (I.e after activation of detector).

**Comment by drjfloyd** [comment] 2022-04-15 14:50
NO_UPDATE_CTRL_ID just stops the outptut value of the DEVC from changing value. It does not do anything to change how the output of the device is used in other control functions. At t=0, pressure is 0.  Freezing the output at 0 just means the input to your deadband is always zero and the deadband will always be true.

**Comment by sbenkorichi** [comment] 2022-04-15 18:23
In the previous releases, I was able to control the activation of the vent until the device of the pressure is unfreezed. 
To explain more what I'm trying to achieve. I want to control the fan via the deadband, but I don't want the fan to be activated until the smoke detector is activated. As such, the pressure device, which gives a reading to deadband is frozen until the detector is activated then it will turn on and provide a reading to enable the deadband to control the fan.
If you run the below example with fds6.7.5, you will see the fan won't activate until the detector is activated. If you run it with the latest release you see the fan is always activated. I'm trying to understand what has changed, and if that's no longer possible, is there any workaround to do to achieve the same objective? Thanks

I will do some bisect to find what changes that lead to this and report later.

```
&HEAD CHID='dummy'/
&TIME T_END=20.0/

&MESH ID='MESH', IJK=20,43,27, XB=-0.9,1.1,18.4,22.7,-0.1,2.6/


&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1,
      HEAT_OF_COMBUSTION=2.0E+4/

&PROP ID='Cleary Ionization I1',
      QUANTITY='CHAMBER OBSCURATION',
      ALPHA_E=2.5,
      BETA_E=-0.7,
      ALPHA_C=0.8,
      BETA_C=-0.9/
&CTRL ID='Extract-CTRL', FUNCTION_TYPE='DEADBAND', SETPOINT=-30.0,-25.0, ON_BOUND='UPPER', LATCH=.FALSE., INPUT_ID='pressure'/
&CTRL ID='Unfreeze-Pres-DEVC', FUNCTION_TYPE='ALL', LATCH=.FALSE., INITIAL_STATE=.TRUE., INPUT_ID='latch'/
&CTRL ID='latch', FUNCTION_TYPE='ALL', LATCH=.TRUE., INPUT_ID='SD'/
&DEVC ID='pressure', QUANTITY='PRESSURE', XYZ=0.2,20.9,1.5, NO_UPDATE_CTRL_ID='Unfreeze-Pres-DEVC'/
&DEVC ID='SD', PROP_ID='Cleary Ionization I1', XYZ=0.1,20.6,2.3/

&SURF ID='EXTRACT',
      COLOR='RED',
      VOLUME_FLOW=1.0/
&SURF ID='Fire',
      RGB=255,153,51,
      HRRPUA=200.0/

&OBST ID='Obstruction', XB=-0.7,0.9,22.3,22.5,-1.665335E-16,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-0.9,1.1,18.8,22.7,-0.1,-3.330669E-16, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-0.9,-0.7,19.0,22.5,0.0,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-0.9,1.1,18.8,19.0,0.0,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-0.9,1.1,22.5,22.7,0.0,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=0.9,1.1,19.0,22.5,0.0,2.6, SURF_ID='INERT'/ 

&HOLE ID='Leakage', XB=-0.4,0.55,18.75,19.1,0.0,0.3/ 

&VENT ID='fan', SURF_ID='EXTRACT', XB=-0.3,0.7,22.3,22.3,1.4,2.2, CTRL_ID='Extract-CTRL'/ 
&VENT ID='Fire-Vent', SURF_ID='Fire', XB=-0.3,0.4,20.3,21.0,5.551115E-17,5.551115E-17/ 

&VENT MB='XMAX',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/

&TAIL /
```

**Comment by drjfloyd** [comment] 2022-04-15 18:39
Freezing the device, does not stop the device from sending an output to the control function. Freezing the device just means that the value being output does not change.  No matter what the state of the NO_UPDATE_CTRL is, the device will still have a numerical value associated with it and that value will used by the deadband function. 

The control functions in this case are working properly. There is no bug to fix.

If the logic you want is the fan is on only if BOTH the deadband AND the smoke detector are true, then you need to control the fan with a control function that is deadband AND smoke detector. This function would be never be true unless the detector has operated at which point it will then be true if the deadband is also true.

**Comment by sbenkorichi** [comment] 2022-04-15 23:44
Thanks Jason, I tried your suggestion and it worked. Before it used to damp larger numerical numbers as the device was freezed but now it looks much realistic and better.
