### ISSUE TITLE
Query regarding Numerical instability error

### ISSUE THREAD

**Issue by RakeshRanga** [firemodels/fds#5563] opened 2017-10-10 12:27 UTC
Please find attached the .txt file of the case which I am trying to simulate. It is a parallel burning of two cellulose sheets. It is a 2D case. 
It gave numerical instability error after 5 seconds. There were no temperature or velocity overshoots.
I wanted to know what the problem is and how to resolve the issue.
Thank you.
Regards,
Rakesh
[Cellulose.txt](https://github.com/firemodels/fds/files/1371825/Cellulose.txt)

**Comment by sbenkorichi** [comment] 2017-10-10 13:10
I'm leaving it running now.
However, things to be considered
1. Your meshes aren't set up properly.
2. How do you consider this as 2D case? I see it nothing but a mere 1D case(even it's not set up properly). The thickness should be in the Y direction not the X.
3. I don't see why you have to use these loads of  finer meshes, you can have a simple mesh with a thin sheet.

**Comment by RakeshRanga** [comment] 2017-10-10 13:21
Dear Salah,

I have given the number of cell divisions along Y (i.e J) as 1. So, does'nt
it mean that it is 2D?

Thanks and regards,
Rakesh

**Comment by sbenkorichi** [comment] 2017-10-10 13:32
I know, but what type of changing are you studying in the X direction?

**Comment by RakeshRanga** [comment] 2017-10-10 13:44
I want to study how the flame structure changes in the presence of another
burning substance in the vicinity. I want to plot the temperature profiles
normal to the sheet surface at various locations along the length of the
sheet and then compare this with single sheet burning case.

**Comment by sbenkorichi** [comment] 2017-10-14 11:10
It's at 6.30 with no errors so far.
1. Can you post the error lines if you still have them recorded?  
2. Are you able to restart it after the error, or it doesn't let you?

**Comment by RakeshRanga** [comment] 2017-10-14 13:34
At 5:09, it gave numerical instability error. Every time I restart it from
5, it is giving the same error .

**Comment by sbenkorichi** [comment] 2017-10-14 13:39
I'm running it with the up to date version, no errors so far (6.5 s).
1. Which version are you using? 
2. Show the line how you run the case.

**Comment by RakeshRanga** [comment] 2017-10-14 13:55
I am using FDS 6.5.3

This is how I executed the command:
mpirun -np 4 fds Cellulose.fds

**Comment by sbenkorichi** [comment] 2017-10-14 13:58
Ok. I haven't used mpirun. 
I will rerun the case with what you mentioned to see if I can reproduce the error.

**Comment by sbenkorichi** [comment] 2017-10-14 14:01
Another question, did you use openmpi supplied with the bundle, or you did compile it yourself? If so, which compiler did you use( intel or gnu)?

**Comment by RakeshRanga** [comment] 2017-10-14 14:06
I used the one supplied with the bundle.
I gave this command: export OMP_NUM_THREADS=5.

I have another question. If you didnt run the case using mpirun then how
did you run it in parallel ? Are you running it in windows ?

**Comment by sbenkorichi** [comment] 2017-10-14 14:11
Ok, first OMP_NUM_THREADS= should be set to 1, don't set it to higher number when you have multiple mesh lines.
2. I didn't use it simply because I had other stuff running, as I don't have a cluster yet.
My OS is Linux.

**Comment by RakeshRanga** [comment] 2017-10-14 14:57
Salah, did you run it in parallel or serial? If you didn't run it in
parallel how did it run so fast? May I know the configuration of the
machine you are running it in?

**Comment by sbenkorichi** [comment] 2017-10-14 15:02
Not using mpirun means it's not in parallel.
How it's fast when it took 4 days to get 6.5 s done?
I have Intel i7 with 32 GB ram.

**Comment by RakeshRanga** [comment] 2017-10-14 15:31
It took me 7 days.
I am running on i5 with 16 GB ram.

**Comment by RakeshRanga** [comment] 2017-10-14 15:34
Then, may i know the command you are giving to run it ?

On 14-Oct-2017 9:01 PM, "Rakesh Ranga" <rakeshrangarocky@gmail.com> wrote:

It took me 7 days.
I am running on i5 with 16 GB ram.

**Comment by sbenkorichi** [comment] 2017-10-14 15:47
I run it simply by using the fds job.fds nothing new. I think the difference could be in the CPU speed.
Try this and report back: 
`cat /proc/cpuinfo `
Check **model name**, mine has 3.4GHZ , I reckon yours is gonna be less than mine.
You've also slowed the running time when you set nbr of threads to 5.

**Comment by RakeshRanga** [comment] 2017-10-14 16:25
I have 2.7 GHz .

**Comment by sbenkorichi** [comment] 2017-10-14 16:36
That answers your question.

**Comment by RakeshRanga** [comment] 2017-10-14 18:34
Salah,

If it isn't too much trouble, can you please share the files of the case
that you have run till 6.5 seconds. I will try to restart that in my system
from that point and check if it runs properly?


On Sat, Oct 14, 2017 at 10:06 PM, Salah Benkorichi <notifications@github.com

**Comment by sbenkorichi** [comment] 2017-10-14 18:44
Not possible, I can't upload 2gb of data. 
You have to run it on your system.

**Comment by RakeshRanga** [comment] 2017-10-14 18:49
Salah, in one of the comments you wrote 'not using mpirun does not mean not
running in parallel'. Then how are you running in parallel? You told you
are just using fds job.fds to run.

**Comment by sbenkorichi** [comment] 2017-10-14 18:56
I said "Not using mpirun means it's not in parallel." -- i.e. in serial.
I've left it running in parallel after you showed how you run it to see if I can reproduce the error.

**Comment by sbenkorichi** [comment] 2017-10-17 08:30
7s with no errors.
I think you might have done something wrong.

Here is what you should do:
1. In a new directory, copy the input file/or delete all other files except .fds in the current one.
2. In terminal : `export OMP_NUM_THREADS=1`
3. On the same terminal run the case: `mpirun -np 4 fds Cellulose.fds`

After you test it, and finishes with no error, you can close this issue, if the error appears again, paste it here.

**Comment by RakeshRanga** [comment] 2017-10-17 10:30
Thank you Salah. I will try it.
Sorry for the trouble....

**Comment by RakeshRanga** [comment] 2017-10-20 08:39
Hello Salah !

I tried running that case by setting number of threads to 1. It is running fine without any errors. Thank you for the help !!

I wanted to know how does changing the number of threads affect the solution?
Also, I had another similar case which I was running in windows system in series. It had run till 1.5 seconds. I transferred that to linux system so as to run it in parallel. After 1.6 seconds it gave numerical instability error. So I continued it back in windows system itself from 1.5 seconds. It is running without any errors. Does the machine in which you run also play any role?

**Comment by sbenkorichi** [comment] 2017-10-20 08:54
No, you can not start a job in series then turn it into parallels it won't work as run time was for individual mesh so they weren't running together and communicating with each other. Either you doing parallel jobs from the beginning or keep it in serial, it's not a system issue. 
As for the threads you are running at least 4 process in each you have 3 meshes you at slowing your run by exporting 5 threads, usually in parallel it's recommended to use only 1, if it was in serial it appropriate since you have i5.

**Comment by RakeshRanga** [comment] 2017-10-20 09:21
Thank you.

**Closed as completed** 2017-10-20 09:27 UTC
