### ISSUE TITLE
Numerical instability for a simple tunnel

### ISSUE THREAD

**Issue by MrSiss** [firemodels/fds#4538] opened 2016-12-08 07:43 UTC
Hello,

I modelled a simple tunnel with differents VENT : one boundary condition (X=0) [the other extrimity is OPEN], 6 VENT at the ceiling to suck air, 107 VENT to blow air. A fire is situated at X=450. VENT and FIRE are controlled by RAMP.

At T=390 s, the simulation stops for a numerical instability close to the fire (CFL = 10^7 !!). I don't understand...the model is very simple. 

Please help me to find what i should do?

[Tunnel_ScA.txt](https://github.com/firemodels/fds/files/638681/Tunnel_ScA.txt)

**Comment by mcgratta** [comment] 2016-12-08 13:50
What version of FDS are you using? If it is not the latest (6.5.2), then install it and run the case again.

**Comment by MrSiss** [comment] 2016-12-08 13:53
I'm using the last version of FDS 6.5.2 (Revision : Git-r21-0-g4e9103f).

**Comment by mcgratta** [comment] 2016-12-08 14:02
If you are running the latest version of FDS, you should see this error message:
```
ERROR: Specify orientation of DEVC mass flow T2 using the parameter IOR (CHID: Beat)
MPI process      0 has completed

STOP: FDS was improperly set-up (CHID: Beat)
```

**Comment by MrSiss** [comment] 2016-12-08 14:10
Sorry but it was not the right file...here is the right file :
[Tunnel_ScA.txt](https://github.com/firemodels/fds/files/639615/Tunnel_ScA.txt)

**Comment by rmcdermo** [comment] 2016-12-09 13:51
Just wanted to give an update.  I broke the domain into 4 meshes and it has run up to about 1312 s.  Here is the input file I'm using (just changed mesh lines).

[Tunnel_ScA-2.fds.txt](https://github.com/firemodels/fds/files/642297/Tunnel_ScA-2.fds.txt)

It is hard to know exactly what is happening here.  You say this is a "simple" case, and perhaps it is in terms of the tunnel  geometry, but very long domains with heat release are problematic for an elliptic flow solver.  It is possible that the errors we incur at mesh boundaries are actually helping, giving some wiggle room to the solver.

I'll report back if the simulation finishes ok.  If you have the processors available, I would break the domain up still further, to say 16 meshes.

**Comment by mcgratta** [comment] 2016-12-09 15:24
I ran the single mesh case with the latest version of FDS. The instability still occurs at 385 s. The problem is related to the pressure solver. Because of the low Mach number assumption, pressure fluctuations caused by the fire propagate instantaneously throughout the entire tunnel. If you look at a a slice of `PRESSURE`, you will see these large variations in pressure. These changes in pressure make it difficult for FDS to force the normal component of velocity at the fuel bed surface to the specified value. If you look near the end of the .out file, you will see that the `Maximum Velocity Error` and `Maximum Pressure Error` occur around cell (900,4,4), the top corner of the burning train car. You will also see that the number of iterations of the pressure solver is hitting its default maximum value of 10. Here are some options:

1. Increase the number of pressure iterations to, say, 50:
&PRES MAX_PRESSURE_ITERATIONS=50 /

2. If this tunnel has some leakage, add `OPEN` vents along the lower portion of the walls or floor with comparable leakage area. This will relieve the pressure fluctuations.

3. Try what rmcdermo (Randy) suggests above. This will make the case run faster in any event.

**Comment by drjfloyd** [comment] 2016-12-09 16:11
If the tunnel has leakage it may be better to assign it over multiples region on the floor using the HVAC LEAK inputs.  Typically leakage by area is equivalent to a small number of wall cells and just assigning those as open can result in large velocities at those locations.

**Comment by rmcdermo** [comment] 2016-12-12 17:18
The above input file finished without instability.

**Comment by MrSiss** [comment] 2016-12-14 07:33
Thank you all for your help !
I only used the first option proposed by Kevin : increase the number of pressure iterations to 50 - and it works.

**Comment by mcgratta** [comment] 2016-12-14 13:50
Thanks for letting us know.

**Closed as completed by mcgratta** 2016-12-14 13:50 UTC

**Comment by usmansh0786** [comment] 2019-08-05 08:48
https://github.com/mcgratta  can you please tell me how to change pressure iterations value in fds 2012?

**Comment by mcgratta** [comment] 2019-08-05 12:14
What is "fds 2012"?

**Comment by usmansh0786** [comment] 2019-08-06 05:44
fire dynamics simulator software 2012 version

**Comment by mcgratta** [comment] 2019-08-06 12:46
This is not a valid version designation. In any case, just use the latest version of FDS, 6.7.1. We do not address issues in older versions.
