### ISSUE TITLE
Thermocouple statistics max

### ISSUE THREAD

**Issue by mjpart** [firemodels/fds#3521] opened 2016-02-19 10:40 UTC
Hi!

I have some problems with statistics measurement in FDS (version 6.3.2).
I have examined small scale experiments regarding to smoke and heat control systems (smoke duct sections) and how these components are exposed to heat in fire scenarios. In my test case (1K-K_3,0m) I have set thermocouple devices under the smoke duct and measured thermocouple statistics max inside the certain volume (just under the duct). 

Results and input file are as attachments:
-Point device (green line) measures higher temperature than statistics MAX although measuring properties are same and point device locates inside the statistics measurement volume. I have tested this in different other situations and results are similar.  How is that possible?
Statistics max should give the highest temperature possible… I haven’t noticed this phenomenom in earlier FDS versions. 

Thank you for your comments!

[1K-K_3,0m.zip](https://github.com/firemodels/fds-smv/files/137791/1K-K_3.0m.zip)

Regards
Mikko

**Comment by mcgratta** [comment] 2016-02-19 13:38
Please simplify your case. It is difficult to sort through all these lines of input to diagnose a possible problem. Create a simple test case that demonstrates the problem by removing unnecessary details from your case. For example, RAMPs, multiple MESHes, etc.

**Comment by mjpart** [comment] 2016-02-19 20:51
Hi,
Simplified input file below.

[test_case.fds.txt](https://github.com/firemodels/fds-smv/files/138668/test_case.fds.txt)

**Comment by mcgratta** [comment] 2016-02-22 13:47
The problem is with the `THERMOCOUPLE` output. When you ask for `THERMOCOUPLE`, FDS solves an ordinary differential equation that governs the heating of a small spherical bead. This calculation is only done at a single point, not multiple points when `STATISTICS='MAX'`. I have added an error flag to stop FDS whenever `THERMOCOUPLE` is used with `STATISTICS`. For the moment, do not use the two flags together.

**Comment by Edward101** [comment] 2016-03-31 15:42
I have a similar problem for MIN statistics on VISIBILITY quantity. But I did't use THERMOCOUPLE. I run it using FDS6.2.0.

Besides, I find it took a longer time to dump slices for FDS6.2.0 than FDS6.0.1. The time could be increased from 5min to 30min if the slices are dumped. Is this problem fixed in later versions?

Attached is one modification version based on the hallway example provided by FDS.
[hallways3.1.fds.txt](https://github.com/firemodels/fds-smv/files/197993/hallways3.1.fds.txt)
![hallways3 1_results](https://cloud.githubusercontent.com/assets/18192842/14181610/37913cbc-f72d-11e5-854b-debefc292ce6.png)

**Comment by mcgratta** [comment] 2016-03-31 15:50
I'll take a look.

**Comment by mcgratta** [comment] 2016-03-31 16:08
When I run with the current version of the code, and I plot V11, V12, and V13, I get results consistent with MIN, MAX and MEAN. Same for V21-V23. The slices add about 6 s to your 60 s test case.

**Comment by Edward101** [comment] 2016-03-31 16:14
I didn't explain clearly. Did you find the averaged value of V12 larger than that of V4 or V5? or V10 larger than V5? And did you run it in FDS6.2.0, or later version 6.3.2?

**Comment by mcgratta** [comment] 2016-03-31 16:23
V5 is the predicted value at the cell between z=0.8 and z=0.9. V10 is the minimum of values in cells between z=0.4 and z=0.8.

**Comment by Edward101** [comment] 2016-03-31 16:42
I am confused. I think V5 are measured values at the point (0.8, 0.5, 0.8) with time, while V10 are the minimum values of measured values in XB= 0.7,0.9,0.4, 0.6, 0.4, 0.8 (with time). V5 is located inside the region where V10 located. So V10 should be less than V5 all the time.
Then the time-averaging value of V10 should be less than that of V5. However, the former is 6.08, while the later is 5.67. It doesn't make sense. 
It is the same to V12 (with a time-averaging value of 6.64) vs. V4 (6.22) or V5 (5.67).

Attached is the output with time-averaging values (The last 15 seconds are used).
[hallways3.1_devc.xlsx](https://github.com/firemodels/fds-smv/files/198099/hallways3.1_devc.xlsx)

**Comment by mcgratta** [comment] 2016-03-31 16:45
When you specify a single point device using XYZ, FDS chooses the value of the grid cell in which the device is located. V5 is on a cell boundary, and FDS chooses the cell 0.8<z<0.9. This cell is outside the XB range of V10. Try moving the XYZ to be within a cell that is within XB.

**Closed as completed** 2016-04-01 14:37 UTC

**Comment by Edward101** [comment] 2016-04-06 21:47
[hallways.fds.txt](https://github.com/firemodels/fds-smv/files/207402/hallways.fds.txt)
I changed the locations to ensure V4 or V5 not on a cell boundary. Now I run it in FDS6.3.2.
However, the results are still confused. Time-averaging value of V12 is still larger than that of V4 or V5.

**Comment by mcgratta** [comment] 2016-04-07 13:20
You should specify a volume using `XB`, not a line as you have done here. It's best to define a volume that clearly encompasses a volume of grid cells. Then set your point `DEVC`s using `XYZ` to be INSIDE that volume.

```
&DEVC   XB=  0.81,  0.81, 0.51, 0.51, 0.31, 0.81, ID='V12',     QUANTITY='VISIBILITY', STATISTICS="MIN" /
```

**Comment by Edward101** [comment] 2016-04-07 13:56
It works now. Thanks for your help.

**Comment by mcgratta** [comment] 2016-04-07 14:18
No problem.
