### ISSUE TITLE
FDS manual values for default O2 and CO2 not correct

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#5127] opened 2017-05-30 19:20 UTC
Just a detail. The FDS manual values for default O2 and CO2 (Section 13.1.1 and Table 18.14) do not match the values printed in the OUT file. See attached images.

Thanks,
Dan

![table 18 14](https://cloud.githubusercontent.com/assets/13338306/26600796/1256496e-4543-11e7-91ca-8b35d37ca73e.PNG)
![air from out file](https://cloud.githubusercontent.com/assets/13338306/26600803/15d5fea4-4543-11e7-8c79-64a4fe0b476d.PNG)

**Comment by rmcdermo** [comment] 2017-05-30 19:28
Good catch, Dan.  I'll fix.

**Comment by drjfloyd** [comment] 2017-05-30 19:29
The manual is dry air

**Comment by drjfloyd** [comment] 2017-05-30 19:31
We don't seem to state that in the User's Guide.

**Comment by rmcdermo** [comment] 2017-05-30 19:36
Jason,
So how do you want the _INFTY defaults to read?  Do you want some kind of asterisk that says these values are for dry air but that the default humidity is 40% or do you want me to change the default _INTY parameters in table 18.14?

**Comment by drjfloyd** [comment] 2017-05-30 19:59
Right now we take Y_CO2 and Y_O2 and compute Y_N2.  Then we add the water vapor and renormalize.  

Table 18.14 should (hopefully) match what is in cons.f90.  

Right now the Guide says (12.1.3): 

The ﬁrst predeﬁned species is the default background species of AIR. This is a lumped species consisting of oxygen, nitrogen, carbon dioxide, and water vapor whose mass fractions are controlled by the Y_CO2_INFTY, Y_O2_INFTY, and HUMIDITY inputs.

Maybe add to that: "The Y_CO2_INFTY and Y_O2_INFTY values are defined assuming dry air and are corrected by FDS to account for HUMIDTY." ?

**Comment by rmcdermo** [comment] 2017-05-30 20:53
I think the problem is that we expect the table in sec 18 to be self-contained to some degree.  I think I'll just add a footnote saying these values assume dry air but that by default AIR is not dry (no good deed goes unpunished).

**Comment by mcgratta** [comment] 2017-05-30 20:55
We typically leave blank those parameters that do not have a fixed value. We would need lots of footnotes to explain each. Best to send the reader to the proper section for more explanation.

**Comment by rmcdermo** [comment] 2017-05-30 20:55
OK.

**Comment by rmcdermo** [comment] 2017-05-30 21:12
Should be fixed.

**Closed as completed by rmcdermo** 2017-05-30 21:12 UTC

**Comment by drjfloyd** [comment] 2017-05-30 22:05
Randy,

Thanks for fixing.  I coded the routine for dry air for CO2 and O2 since most tabulations of the standard atmosphere are dry air (since water vapor varies) and since a measured value of O2 in a test is often from a gas analyzer after water vapor has been removed (a paramagnetic O2 analyzer also responds to water vapor).
