### ISSUE TITLE
Simple supply VENT suppresses airflow from HVAC system in a tunnel 

### ISSUE THREAD

**Issue by 19ap** [firemodels/fds#9555] opened 2021-06-08 07:47 UTC
Dear developers,
 
I would like to ask for your suggestions regarding the following issue (FDS 6.7.5).
There is a possibility of natural airflow in a tunnel caused by weather conditions (say, 1 m/s). When in this situation one of the tunnel portals is used as an air supplier (in a form of a big fan whose outlet corresponds to a portal size), this "fan" acts not as a fan (like a source of a flow) but rather as a source of a stable and constant 3D airfield (that is very similar to a "wind" field). This transformation (from just a fan to a 3D field source), as it seems, is dependant on the size (or ratio) of the supply VENT (and the portal area) because when smaller air supply vents are used, no such problem arises.
So if another blower (using an HVAC model: 32.9 m3/s, outlet diameter 0.9 m) is added to the tunnel to simulate, e.g. a jet fan, then this "natural" flow suppresses the flow from the "jet fan". This suppression does not happen (to its full extent) when a jet fan model with a simple supply VENT (as for the "natural" flow) is used.
FDS text with a simple case model:
[Test_case_Airflows.txt](https://github.com/firemodels/fds/files/6614455/Test_case_Airflows.txt)
Thank you for your time and help.

BR
Aleks

**Comment by drjfloyd** [comment] 2021-06-08 12:04
This is not a bug. When you use VEL, you are forcing the boundary to always have that velocity no matter what else is happening in the simulation.  With VEL, the jet fan can't cause more air to enter the tunnel end to feed the jet fan. The overall air flow in the tunnel is fixed by VEL. If you want to see how a jet fan interacts with wind driven flow in a tunnel, try using the DYNAMIC_PRESSURE input for the VENT rather than VEL.

**Closed as completed by drjfloyd** 2021-06-08 12:04 UTC
