### ISSUE TITLE
MISC options for EVAC in FDS 6.7.5

### ISSUE THREAD

**Issue by scireNam** [firemodels/fds#8707] opened 2020-08-26 16:12 UTC
Hi everyone.
I would like to report that since FDS 6.7.5, maybe was introduced an error in starting a simulation with these 2 parameters in MISC namelist:
EVAC_TIME_ITERATIONS and EVAC_PRESSURE_ITERATIONS, normally 50 by default.
If written in &MISC will cause FDS to throw following error:
_**ERROR: Input line 8 is not formatted properly; NAMELIST: MISC**_

Previous versions work perfectly. 
Bye.

**Comment by gjaeger** [comment] 2020-08-26 16:18
@scireNam Can you upload a small inputfile so we can reproduce the problem?

**Comment by gjaeger** [comment] 2020-08-26 16:46
With this example ([issue8707.fds](https://github.com/firemodels/fds/files/5131195/issue8707.fds.zip)), I can't reproduce your problem.

```
&HEAD CHID  = "issue8707"  /

&MESH IJK     = 150,100, 1,
      ID      = "GroundFloor",
      XB      = 0.0,15.0, 0.0, 10.0, 0.8, 1.6,
      EVACUATION      = .TRUE.,
      EVAC_HUMANS     = .TRUE.,
      EVAC_Z_OFFSET   = 1.2 /

&MISC NO_EVACUATION            = .FALSE.,
      EVACUATION_MC_MODE       = .TRUE.,
      EVACUATION_DRILL         = .FALSE.,
      EVAC_TIME_ITERATIONS     = 100,
      EVAC_PRESSURE_ITERATIONS = 25 /

&DUMP DT_PART = 0.5,
      DT_HRR  = 1.0,
      DT_SLCF = 1000000.0,
      DT_PL3D = 1000000.0,
      DT_ISOF = 1000000.0 /

&TIME T_BEGIN           =   0.0,
      T_END             = 120.0,
      EVAC_DT_FLOWFIELD =   0.01 /

&EXIT ID         = "EXIT",
      IOR        = +1,
      COLOR      = "BLUE",
      COUNT_ONLY = .FALSE.,
      XYZ        = 14.8, 5.0, 2.0
      XB         = 15.0,15.0, 4.5, 5.5, 0.8, 1.6 /

&PERS ID                   = "Adults",
      DEFAULT_PROPERTIES   = "Adult",
      PRE_EVAC_DIST   = 0,
          PRE_MEAN    = 0.0,
      DET_EVAC_DIST   = 0,
          DET_MEAN    = 0.0,
      VELOCITY_DIST   = 0,
          VEL_MEAN    = 1.00,
      DENS_INIT       = 6.0,
      OUTPUT_SPEED         =.TRUE.,
      COLOR_METHOD         = 0 /

&EVAC ID                      = "Agents",
      NUMBER_INITIAL_PERSONS  = 25,
      XB                      =  0.0, 15.0, 0.0, 10.0, 0.8, 1.6,
      AVATAR_COLOR            = "BLUE",
      PERS_ID                 = "Adults" /

&SLCF PBZ        = 1.0,
      QUANTITY   = "VELOCITY",
      VECTOR     = .TRUE.,
      EVACUATION = .TRUE. /

&TAIL /
```

The simulation is running:
```bash
% fds issue8707.fds

 Starting FDS ...

 MPI Process      0 started on MacBookPro

 Reading FDS input file ...

 EVAC: Emesh 1 GroundFloor has 1 door flow fields
 FDS+Evac pressure method : FFT

 Fire Dynamics Simulator

 Current Date     : August 26, 2020  18:40:27
 Revision         : FDS6.7.5-0-g71f025606-release
 Revision Date    : Thu Aug 20 16:19:01 2020 -0400
 Compiler         : Intel ifort 19.1.1.216
 Compilation Date : Aug 21, 2020  16:33:14

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Open MPI v3.1.2, package: Open MPI gforney@bevo.el.nist.gov Distribution, ident: 3.1.2, repo rev: v3.1.2, Aug 22, 2018

 Job TITLE        :
 Job ID string    : issue8707

 Time Step:    -99,    Evacuation Initialization Time:    -0.990 s
 Time Step:      1, Simulation Time:      0.05 s
 Time Step:      2, Simulation Time:      0.10 s
```

Can you show your `&MISC` line?

**Comment by scireNam** [comment] 2020-08-27 07:57
I'm sorry, but for unexpected reasons my script wrote a tab after namelist name, this lead to **Error : not formatted properly.**
So no problem with that parameters, but i didn't know that a tabulation "\t" could lead to this format error:

![image](https://user-images.githubusercontent.com/48561721/91413612-aebc7900-e84b-11ea-84f1-2fe8c6a9242a.png)

**Comment by gjaeger** [comment] 2020-08-27 08:10
Thanks for the feedback.

See the User Guide for details (section 5.2):
> Parameters within a namelist record can be separated by either commas, spaces, or line breaks. It is recommended that you use commas or line breaks, and never use tab stops because they are not explicitly defined in the namelist data structure.

@scireNam Can you close this issue?

**Closed as completed** 2020-08-27 09:06 UTC
