### ISSUE TITLE
Oscillation in HRR

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#3331] opened 2016-01-06 15:28 UTC
We are testing a previous model and have noticed significantly more oscillation in calculated HRR during the initial transient. The model is an open cube with a burner on the bottom. The attached figures illustrate the differences. I thought it was worthwhile to bring this to your attention, even though it is not necessarily a bug.

Here is the model:
![model](https://cloud.githubusercontent.com/assets/13338306/12146150/bc67dc48-b457-11e5-9b8c-c0ef2dd5a93a.png)
1. FDS 6.1.1 (and FDS 6.1.2) - This is the previous behavior. The initial transient is smooth.
   ![hrr_fds6_1_1](https://cloud.githubusercontent.com/assets/13338306/12145568/9e7aace0-b454-11e5-9af6-e27401c3ee5f.png)
2. FDS 6.2.0 - This shows initial oscillation.
   ![hrr_fds6_2_0](https://cloud.githubusercontent.com/assets/13338306/12145642/15c86530-b455-11e5-8ef3-ae2c4f83652a.png)
3. FDS 6.3.2 - This shows increased initial oscillation compared to FDS 6.2.0.
   ![hrr_fds6_3_2 refined mesh](https://cloud.githubusercontent.com/assets/13338306/12145664/3648e96a-b455-11e5-833d-3b0dbd10e0f2.png)
4. FDS 6.3.2  - Refined mesh. I reduced the size of the mesh in all directions by a factor of 2 (8 times more cells). This still shows oscillation.
   ![hrr_fds6_3_2 refined mesh](https://cloud.githubusercontent.com/assets/13338306/12145703/6ce48ff6-b455-11e5-9088-06ea5fc3a268.png)
5. FDS 6.3.2 - Reduced time step. The default initial time step is 0.056. For this case I set the time step to 0.01. There is small scale oscillation, but it is basically smooth.
   ![hrr_fds6_3_2 with dt_01](https://cloud.githubusercontent.com/assets/13338306/12145759/b8995436-b455-11e5-8f38-a4934a1f6da3.png)

In all cases, the MLR_FUEL shows a smooth increase.
![mlr_fuel](https://cloud.githubusercontent.com/assets/13338306/12145881/57ee1472-b456-11e5-9379-f0bf4d31cf43.png)

Here is the model:

---

radiative_fraction_default.fds
Generated by PyroSim - Version 2015.4.1214
Jan 5, 2016 3:39:54 PM

&HEAD CHID='radiative_fraction_default'/
&TIME T_END=4.0/
&DUMP RENDER_FILE='radiative_fraction_default.ge1', DT_RESTART=300.0/

&MESH ID='Mesh01', IJK=40,40,40, XB=-0.5,1.5,-0.5,1.5,0.0,2.0/

&REAC ID='METHANE',
      FYI='AFT NIST Multi-Floor FDS5 Validation',
      FUEL='REAC_FUEL',
      FORMULA='C1H4',
      AUTO_IGNITION_TEMPERATURE=0.0,
      HEAT_OF_COMBUSTION=5.56E4/

&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=100.0,
      ADIABATIC=.TRUE./

&OBST XB=0.25,0.75,0.25,0.75,0.0,0.0033462, SURF_IDS='Fire','INERT','INERT'/ Obstruction

&VENT SURF_ID='OPEN', XB=1.5,1.5,-0.5,1.5,0.0,2.0/ Mesh Vent: Mesh01 [XMAX]
&VENT SURF_ID='OPEN', XB=-0.5,-0.5,-0.5,1.5,0.0,2.0/ Mesh Vent: Mesh01 [XMIN]
&VENT SURF_ID='OPEN', XB=-0.5,1.5,1.5,1.5,0.0,2.0/ Mesh Vent: Mesh01 [YMAX]
&VENT SURF_ID='OPEN', XB=-0.5,1.5,-0.5,-0.5,0.0,2.0/ Mesh Vent: Mesh01 [YMIN]
&VENT SURF_ID='OPEN', XB=-0.5,1.5,-0.5,1.5,2.0,2.0/ Mesh Vent: Mesh01 [ZMAX]
&VENT SURF_ID='OPEN', XB=-0.5,1.5,-0.5,1.5,0.0,0.0/ Mesh Vent: Mesh01 [ZMIN]

&SLCF QUANTITY='HRRPUV', PBY=0.5/

&TAIL /

![radiative_fraction_default fds](https://cloud.githubusercontent.com/assets/13338306/12145801/efc0b4cc-b455-11e5-8e92-1446d6e91488.png)

**Comment by mcgratta** [comment] 2016-01-06 15:30
I'll take a look at it.

**Comment by dvswenson** [comment] 2016-01-06 15:31
I posted the wrong plot for FDS 6.3.2
![hrr_fds6_3_2](https://cloud.githubusercontent.com/assets/13338306/12146249/45921236-b458-11e5-8580-be1d00270a3e.png)

**Comment by mcgratta** [comment] 2016-01-06 16:05
Tom, I can name that bug in 14 lines...

```
&HEAD CHID='hrr_noise' /
&TIME T_END=4. /
&MESH IJK=40,40,40, XB=-0.5,1.5,-0.5,1.5,0.0,2.0/
&REAC FUEL='METHANE' /
&SURF ID='Fire', COLOR='RED', HRRPUA=100. /
&OBST XB=0.25,0.75,0.25,0.75,0.0,0.0, SURF_IDS='Fire','INERT','INERT'/
&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
 VENT MB='ZMIN', SURF_ID='OPEN' /  <---- Add this line back in and the oscillations will return
&VENT MB='ZMAX', SURF_ID='OPEN' /
&SLCF QUANTITY='HRRPUV', PBY=0.5, VECTOR=.TRUE. /
&TAIL /
```

Actually, I don't think it's a bug, but rather a spurious boundary effect. In your case, the burner surface is aligned with an OPEN boundary. OPEN boundaries are only approximations of reality -- FDS must make an assumption that the pressure is ambient there even though in this case that would not be a good assumption. I'm going to see if this problem occurs when the obstruction is placed away from the OPEN boundary.

**Comment by dvswenson** [comment] 2016-01-06 17:52
Orientation and boundaries definitely make a difference.

Vertical obstruction:
![vertical obstruction](https://cloud.githubusercontent.com/assets/13338306/12149881/daed266e-b46b-11e5-9572-3a864f0c7383.PNG)

Vertical HRR:
![vertical hrr](https://cloud.githubusercontent.com/assets/13338306/12149890/e6a3bf90-b46b-11e5-915b-acc4b5525ede.PNG)

Raised horizontal obstruction:
![raised horizontal obstruction](https://cloud.githubusercontent.com/assets/13338306/12149897/f02b3d40-b46b-11e5-979c-ab1a8372b349.PNG)

Raised HRR:
![raised hrr](https://cloud.githubusercontent.com/assets/13338306/12149902/f99b156c-b46b-11e5-9acd-a8cf9ec74d59.PNG)

**Comment by mcgratta** [comment] 2016-01-06 21:21
I'm not surprised that orientation matters. With the vertically-oriented burner, the air sweeps past from bottom to top fairly smoothly; whereas with the horizontally-oriented burner, you get this initial puff which most of us have experienced turning on the gas barbecue grill. Just be thankful that you didn't singe your eyebrows.

One other thought -- at some point in the past year, we eliminated the hard upper bound on HRRPUV, the heat release rate per unit volume in a single grid cell. We've had this artificial bound since the beginning of FDS, but it is no longer needed with the better turbulent combustion model we use now. But it's possible that the fluctuations are due to relatively large localized bursts of energy, when alot of fuel and oxygen initially mix in a single cell adjacent to the burner. 

I'll close this issue, but reopen if there are other cases that are problematic.

**Closed as completed by mcgratta** 2016-01-06 21:21 UTC

**Comment by dvswenson** [comment] 2016-01-07 15:59
Here is a bit more data.

I ran the original model with a refined mesh (0.0125 m cell size). For this case the calculated HRR was smooth.
![hrr_fds6_3_2_size0_0125](https://cloud.githubusercontent.com/assets/13338306/12174665/a6c8ac2e-b523-11e5-848a-b5e8f9680ec9.png)

That leads to the conclusions that in some specific cases:
1. The oscillation is not a true physical phenomenon, it is the result of the numerical solution. The solution converges as the mesh is refined.
2. Oscillations were first seen after FDS 6.2 that included a Species Mass Density Transport Overhaul to address potential realizability violations.
3. Oscillation increased in FDS 6.3 that removed the heat release rate limiter.

I was able to make a 3x1 cell model that might be useful for future investigation of this phenomenon. In the model, the yellow boundaries are obstructions to limit flow to 1D while still using a 3x3 mesh to accomodate the solver requirement.
![debug_model](https://cloud.githubusercontent.com/assets/13338306/12174842/9aeb3128-b524-11e5-84c0-f24da555b555.png)

If we set the velocity to 1 m/s and the delayed fuel flow rate to 0.001 kg/s then we see the oscillation in HRR.
![debug__fuel_1e-3_vel_1](https://cloud.githubusercontent.com/assets/13338306/12174922/fb27824e-b524-11e5-8c9f-953da93ed5d2.png)

Here is the model:

---

debug_fuel_1E-3_vel_1.fds
Generated by PyroSim - Version 2015.4.1214
Jan 7, 2016 9:42:14 AM

&HEAD CHID='debug_fuel_1E-3_vel_1'/
&TIME T_END=20.0/
&DUMP RENDER_FILE='debug_fuel_1E-3_vel_1.ge1', DT_RESTART=300.0/

&MESH ID='Mesh', IJK=3,3,3, XB=0.0,3.0,0.0,3.0,0.0,3.0/

&REAC ID='METHANE',
      FYI='AFT NIST Multi-Floor FDS5 Validation',
      FUEL='REAC_FUEL',
      FORMULA='C1H4',
      AUTO_IGNITION_TEMPERATURE=0.0,
      HEAT_OF_COMBUSTION=5.56E4/

&DEVC ID='Velocity', QUANTITY='VELOCITY', XYZ=0.5,1.5,1.5, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='HRRPUV', QUANTITY='HRRPUV', XYZ=0.5,1.5,1.5, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='Density', QUANTITY='DENSITY', XYZ=0.5,1.5,1.5, ORIENTATION=1.0,0.0,0.0/
&SURF ID='Supply',
      RGB=26.0,204.0,26.0,
      VEL=-1.0/
&SURF ID='Fire',
      COLOR='RED',
      MLRPUA=0.001,
      RAMP_Q='Fire_RAMP_Q',
      ADIABATIC=.TRUE./
&RAMP ID='Fire_RAMP_Q', T=0.0, F=0.0/
&RAMP ID='Fire_RAMP_Q', T=5.0, F=0.0/
&RAMP ID='Fire_RAMP_Q', T=5.1, F=1.0/
&RAMP ID='Fire_RAMP_Q', T=10.0, F=1.0/

&OBST XB=0.0,3.0,2.0,3.0,0.0,3.0, COLOR='INVISIBLE', SURF_ID='INERT'/ Obstruction
&OBST XB=0.0,3.0,0.0,1.0,0.0,3.0, COLOR='INVISIBLE', SURF_ID='INERT'/ Obstruction
&OBST XB=0.0,3.0,1.0,2.0,2.0,3.0, COLOR='INVISIBLE', SURF_ID='INERT'/ Obstruction
&OBST XB=0.0,3.0,1.0,2.0,0.0,1.0, COLOR='INVISIBLE', SURF_ID='INERT'/ Obstruction

&VENT SURF_ID='OPEN', XB=3.0,3.0,1.0,2.0,1.0,2.0/ Open
&VENT SURF_ID='Supply', XB=0.0,0.0,1.0,2.0,1.0,2.0/ Supply
&VENT SURF_ID='Fire', XB=0.0,1.0,1.0,2.0,1.0,1.0/ Fuel

&SLCF QUANTITY='VELOCITY', PBY=1.5/
&SLCF QUANTITY='HRRPUV', PBY=1.5/

&TAIL /

**Comment by rmcdermo** [comment] 2016-01-07 17:04
Dan,
An LES cannot hope to give reasonable "mixing time" with 3 cells.  Look at the formulas for turbulent viscosity, diffusivity, etc., in the guides.  We need information from neighboring cells and at cells near boundaries (all cells in this case) the problem is even worse.  So, all bets are off in terms of using an LES subgrid model to predict turbulent transport coefficients.  What you can do in FDS at this point is to specify the transport coefficients and do a DNS calculation.  Then things will be smooth.  See attached input file and plot.

![hrr](https://cloud.githubusercontent.com/assets/4418497/12176709/bff249e0-b536-11e5-8ad1-cc204f2146a2.png)

[test.txt](https://github.com/firemodels/fds-smv/files/81435/test.txt)

**Comment by dvswenson** [comment] 2016-01-07 17:09
Kevin,

Thanks.

I really don't understand LES details and it shows.

Dan

On Thu, Jan 7, 2016 at 11:04 AM, Randy McDermott notifications@github.com
wrote:

> Dan,
> An LES cannot hope to give reasonable "mixing time" with 3 cells. Look at
> the formulas for turbulent viscosity, diffusivity, etc., in the guides. We
> need information from neighboring cells and at cells near boundaries (all
> cells in this case) the problem is even worse. So, all bets are off in
> terms of using an LES subgrid model to predict turbulent transport
> coefficients. What you can do in FDS at this point is to specify the
> transport coefficients and do a DNS calculation. Then things will be
> smooth. See attached input file and plot.
> 
> [image: hrr]
> https://cloud.githubusercontent.com/assets/4418497/12176709/bff249e0-b536-11e5-8ad1-cc204f2146a2.png
> 
> test.txt https://github.com/firemodels/fds-smv/files/81435/test.txt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3331#issuecomment-169730854
> .

## 

Daniel Swenson
Thunderhead Engineering
www.thunderheadeng.com
swenson@thunderheadeng.com
+1.785.770.8511 x103

**Comment by rmcdermo** [comment] 2016-01-07 17:11
Think of it like a structural calculation.  If you had 3 elements to describe the World Trade Center collapse, how well would the FEM model work?
