### ISSUE TITLE
Pyrolysis with burn-away modulated by mesh boundary

### ISSUE THREAD

**Issue by errant-ctrl** [firemodels/fds#8518] opened 2020-06-30 02:22 UTC
Hi,

I am attempting to model a rapid pyrolysis process with burn-away on a small axisymmetric object.

During benchmarking, I have found that pyrolysis with burn-away behaves very strangely where OBSTs intersect with mesh boundaries, as if the mesh boundaries act as an interferent to pyrolysate emission. I suspect that this is caused by cells that have faces coincident with mesh boundaries rejecting those faces as valid to emit pyrolysate from. This appears to occur both where an OBST boundary is coincident with a mesh, and where the geometry revealed by burn-away is coincident with a mesh.

Please see the attached MWE, defined with 8 meshes which I have roughly indicated the boundaries of in SmokeView:

![path826-3-6-3](https://user-images.githubusercontent.com/67616637/86075314-1748dd00-bacb-11ea-8f9d-5fa9c3b66c14.png)

Combustion of the rib which extends to the mesh boundary is suppressed, whereas the longer one burns from the end readily, although a transient feature internal to the OBST appears at the mesh boundary.

This behaviour renders parallelism over meshes difficult, because it would appear to require that the fuel OBST must entirely reside within a single mesh. I have not been able to determine a combination of settings that ameliorates this particular problem.

Thanks for any help you can provide.

[meshfail_mwe.txt](https://github.com/firemodels/fds/files/4849036/meshfail_mwe.txt)

**Comment by rmcdermo** [comment] 2020-06-30 12:27
Thanks for the report.  We will take a look.

**Comment by rmcdermo** [comment] 2020-06-30 12:34
3454 atm background pressure?  Please explain.

**Comment by rmcdermo** [comment] 2020-06-30 13:22
I rearranged your input file to use complex stoichiometry and it seems to run fine with the latest source.  I am not sure of the application, but I would suggest you consider Arrhenius chemistry as well---your time scales are too small for infinitely fast chemistry to be a good approximation.  If the background pressure is not a typo then FDS is not the right code to be using---you need a compressible solver.  I would not use FDS for anything over a few atm.  Please check your .out file to see the basic parameters of your problem.  You will see gas densities of 1000s of kg/m3.  Also, 'EXPOSED' is not an appropriate backing for this case, I set it to 'INSULATED' instead.

[meshfail_mwe_new.fds.txt](https://github.com/firemodels/fds/files/4852060/meshfail_mwe_new.fds.txt)

<img width="752" alt="Screen Shot 2020-06-30 at 9 12 06 AM" src="https://user-images.githubusercontent.com/4418497/86130760-a7c6f380-bab2-11ea-9ae7-41195d7afab9.png">

**Comment by errant-ctrl** [comment] 2020-07-01 06:12
Hi,

Yes, the pressure is intended, we are testing FDS under pressure conditions similar to those of a firing cannon, albeit without a time dependency. However, your doubts regarding the applicability of FDS to this pressure regime are giving us serious pause for thought, and we thank you for raising these concerns.

Nevertheless, I believe this issue has been closed prematurely, and the simulation behaviour that we are seeing may indicate a problem that could affect other users of FDS.

I attempted to run the script that you have helpfully modified, and I believe that the problem still exists. If you allow the calculation to run for a little longer, you will note that the burning that is occuring at the upper rib appears to be in a zero-width row of cells (however I assume it has an actual combustible mass determined by the OBST thickness, which may constitute a separate user error on my part). When this layer pyrolyses, it reveals a new layer which is not coloured according to burning rate by SmokeView. The same occurs at the lower rib where it crosses the layer boundary. This suggests that these surfaces are not losing mass despite being exposed, and the anomalous burn-away dynamics in the region of these surfaces seem to confirm that.

Oh, I should note that I'm using a version of FDS which has been modified to report more significant figures in the smv file for the timing of HIDE_OBST, because the timescale is so short (init.f90 line 3166). As such, the finer details of the burn-away dynamics may be obscured in an unmodified build.

![Screenshot from 2020-07-01 16-09-40](https://user-images.githubusercontent.com/67616637/86209199-60755b80-bbb5-11ea-81c7-ae1d254cf0df.png)

**Comment by rmcdermo** [comment] 2020-07-01 12:22
OK, I will have another look.

**Comment by rmcdermo** [comment] 2020-07-02 20:23
@mcgratta I've simplified this case to a 2 mesh version below.  As described above, if the original OBST abuts the interpolated mesh boundary, the burning behavior is incorrect---after the first cell burns away, the reinitialization of the OBST wall cells do not allow burning.  However, note that, as shown in the first image, the cells appear to be initialized correctly at the start of the calculation.

[test_2mesh.fds.txt](https://github.com/firemodels/fds/files/4866494/test_2mesh.fds.txt)

<img width="752" alt="Screen Shot 2020-07-02 at 4 19 43 PM" src="https://user-images.githubusercontent.com/4418497/86405971-4d7b8d80-bc80-11ea-94fb-ce0805a6b387.png">

<img width="752" alt="Screen Shot 2020-07-02 at 4 19 51 PM" src="https://user-images.githubusercontent.com/4418497/86405982-51a7ab00-bc80-11ea-9422-618ba2ef031c.png">

**Comment by mcgratta** [comment] 2020-07-03 16:13
This is tricky. When the burning rate of the positive x-facing cell face appears to stop and the color changes from light blue to orange, Smokeview has removed the thin plate in mesh 2. But the underlying grid cell in mesh 1 doesn't know this. So mass is being extracted from these border cells from cell faces in both meshes, and there is no mechanism now to communicate this.

**Comment by mcgratta** [comment] 2020-07-07 13:21
I did a little work on this issue. The problem is what I thought it was -- a solid obstruction that borders another mesh is begin consumed by surfaces that live in both meshes, and there is no exchange of this information. Good news is that we already exchange some of the information needed to add together the contributions to the consumption.

**Comment by mcgratta** [comment] 2020-07-13 13:28
I'm making progress. I have something working and I'm testing the box_burn_away cases.

**Comment by mcgratta** [comment] 2020-07-15 13:00
I'm still working this issue. It involves some basic assumptions that were made back when FDS was single mesh.

**Comment by mcgratta** [comment] 2020-07-17 21:06
I have fixed the problem, but I need to put together some verification cases. In the meantime, can you check that the original problem is fixed.

**Comment by rmcdermo** [comment] 2020-07-18 12:32
Your PR seems to work fine.  I have some problem with what I pushed that causes a seg fault in _dv mode, though it runs in _db.

**Comment by rmcdermo** [comment] 2020-07-18 13:07
@mcgratta The current code (which includes my commits) seg faults in this block at about line 3556 in init.f90:

```
! Initialize solid properties included in the WALL derived type variable

IF (WC%BOUNDARY_TYPE/=NULL_BOUNDARY) THEN
   IF (IW<=N_EXTERNAL_WALL_CELLS) THEN
      WC%OBST_INDEX = 0
      WC%SURF_INDEX = WC%SURF_INDEX_ORIG
   ENDIF
   IF (OBST_INDEX_C(IC)>0) THEN
      WC%OBST_INDEX = OBST_INDEX_C(IC)
      WC%SURF_INDEX = OBSTRUCTION(WC%OBST_INDEX)%SURF_INDEX(WC%ONE_D%IOR)
   ELSEIF (CREATE .AND. OBST_INDEX>0) THEN
      print *,OBST_INDEX <----------------------------- 146466329
      WC%OBST_INDEX = OBST_INDEX
      WC%SURF_INDEX = OBSTRUCTION(WC%OBST_INDEX)%SURF_INDEX(WC%ONE_D%IOR)
   ENDIF
   PRESSURE_BC_INDEX = WC%PRESSURE_BC_INDEX  ! Save this parameter and restore it after the call to INIT_WALL_CELL
   CALL INIT_WALL_CELL(NM,WC%ONE_D%II,WC%ONE_D%JJ,WC%ONE_D%KK,WC%OBST_INDEX,IW,WC%ONE_D%IOR,WC%SURF_INDEX,IERR,T)
   WC => WALL(IW)
   WC%PRESSURE_BC_INDEX = PRESSURE_BC_INDEX
ENDIF
```

When I print the `OBST_INDEX` it is very large (146466329) and I suspect the seg fault is trying to access `OBSTRUCTION(146466329)`.

When I trace `OBST_INDEX` it does not appear to be initialized.  The OBST_LOOP is looping over `N` in the parent subroutine.  Should `OBST_INDEX` be `N` here?

**Comment by rmcdermo** [comment] 2020-07-18 13:09
This is the input file that crashes.

[test_2mesh.fds.txt](https://github.com/firemodels/fds/files/4941701/test_2mesh.fds.txt)

**Comment by rmcdermo** [comment] 2020-07-18 15:41
@mcgratta I think this is fixed with PR #8595.  Please double check this is how you want OBST_INDEX initialized.

**Comment by mcgratta** [comment] 2020-07-18 15:59
NIce! I was looking for that bug. My test cases would occasionally crash, but I couldn't find the smoking gun. This uninitialized variable probably results from having to split a routine into two parts in order to do an MPI update to get OBST change info from neighboring meshes. I'll check it.

**Comment by mcgratta** [comment] 2020-07-18 16:04
Yup, that's exactly what it was. Thanks.

**Comment by rmcdermo** [comment] 2020-07-18 16:48
OK, good.  I'm going to close this out then.  If something comes up related to it, it can be reopened.

**Closed as completed by rmcdermo** 2020-07-18 16:48 UTC

**Comment by errant-ctrl** [comment] 2020-07-19 05:13
Seems to have fixed the problem, thank you very much for your attention.
