### ISSUE TITLE
Unusual behavoiur in HRR using multiple meshes

### ISSUE THREAD

**Issue by khalidmoinuddin** [firemodels/fds#3856] opened 2016-05-16 04:22 UTC
I carried out simulation with a Fir Tree validation case (2m14PC). When I used a single mesh I got one result  and when I used multi-mesh I got different result . For multi-mesh I symmetrically divided the domain into 4 domains. Both FDS 6.2.0 and 6.4.0 were used. The problem was worse with FDS 6.4.0

There is a known understanding that the FDS' MPI introduces discontinuity in the pressure solver eg see the FDS' roadmap. We understand` that the developers are working towards improvement of pressure solver.  However, in the meantime is there any other way, the simulation can be improved?

There is a suggestion not to put flames at mesh/ sub-domain boundaries. It is difficult to adhere to such suggestion when big fire (several MW) is involved. It becomes even harder when we carry out grid convergence test. 
``
Is there anything else that could cause the problem? Because when in simulation, no flame is involved, we do get expected results eg an isothermal channel flow or a backward facing step case.

Case file with 4 mesh is given below

&HEAD CHID='tree_2_m_14_pc-4Proc', TITLE='Test for burning vegetation mass conservation' /

&MESH IJK=30,30,160, XB=-1.5,0.0,-1.5,0.0,0.0,8.0 /
&MESH IJK=30,30,160, XB=-1.5,0.0,0.0,1.5,0.0,8.0 /

&MESH IJK=30,30,160, XB=0.0,1.5,-1.5,0.0,0.0,8.0 /
&MESH IJK=30,30,160, XB=0.0,1.5,0.0,1.5,0.0,8.0 /

&TIME T_END=30. / 

&REAC FUEL='CELLULOSE', C=6, H=10, O=5, SOOT_YIELD=0.015 /

&SPEC ID='WATER VAPOR' /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
&VENT MB='ZMIN', SURF_ID='FOIL' /

&SURF ID='FOIL'
      COLOR = 'SILVER'
      MATL_ID='ALUMINUM','CONCRETE'
      THICKNESS(1:2) = 0.0002,0.01 /

&MATL ID='ALUMINUM'
      DENSITY = 2707.
      SPECIFIC_HEAT = 0.896
      CONDUCTIVITY = 204.
      EMISSIVITY = 0.1 /

&MATL ID='CONCRETE'
      DENSITY = 1500.
      SPECIFIC_HEAT = 1.
      CONDUCTIVITY = 0.3  /

&SURF ID                        = 'foliage'
      MATL_ID(1,1:2)            = 'vegetation','MOISTURE'
      MATL_MASS_FRACTION(1,1:2) = 0.877,0.123
      THICKNESS                 = 0.0005
      LENGTH                    = 0.05
      GEOMETRY                  = 'CYLINDRICAL' /

&SURF ID                        = 'small roundwood'
      MATL_ID(1,1:2)            = 'vegetation','MOISTURE'
      MATL_MASS_FRACTION(1,1:2) = 0.877,0.123
      THICKNESS                 = 0.001
      LENGTH                    = 0.10
      GEOMETRY                  = 'CYLINDRICAL' /

&SURF ID                        = 'medium roundwood'
      MATL_ID(1,1:2)            = 'vegetation','MOISTURE'
      MATL_MASS_FRACTION(1,1:2) = 0.877,0.123
      THICKNESS                 = 0.002
      LENGTH                    = 0.10
      GEOMETRY                  = 'CYLINDRICAL' /

&SURF ID                        = 'large roundwood'
      MATL_ID(1,1:2)            = 'vegetation','MOISTURE'
      MATL_MASS_FRACTION(1,1:2) = 0.877,0.123
      THICKNESS                 = 0.003
      LENGTH                    = 0.10
      GEOMETRY                  = 'CYLINDRICAL' /

&MATL ID = 'vegetation'
      DENSITY = 514.
      CONDUCTIVITY = 2.0
      SPECIFIC_HEAT= 1.2
      N_REACTIONS = 1
      REFERENCE_TEMPERATURE = 200.
      REFERENCE_RATE = 0.0005
      HEATING_RATE = 1.6
      NU_SPEC = 0.74
      SPEC_ID = 'CELLULOSE'
      NU_MATL = 0.26
      MATL_ID = 'CHAR'
      HEAT_OF_COMBUSTION = 17700.
      HEAT_OF_REACTION = 418. /

&MATL ID = 'CHAR'
      DENSITY = 300.
      CONDUCTIVITY = 2.0
      SPECIFIC_HEAT= 1.2
      N_REACTIONS = 1
      REFERENCE_TEMPERATURE = 350.
      REFERENCE_RATE = 0.0002
      HEATING_RATE = 1.6
      NU_SPEC = 1.00
      SPEC_ID = 'CELLULOSE'
      HEAT_OF_COMBUSTION = 17700.
      HEAT_OF_REACTION = 418. /

&MATL ID = 'MOISTURE'
      DENSITY = 1000.
      CONDUCTIVITY = 2.0
      SPECIFIC_HEAT= 4.184
      N_REACTIONS = 1
      REFERENCE_TEMPERATURE = 100.
      REFERENCE_RATE = 0.002
      HEATING_RATE = 1.6
      NU_SPEC = 1.0
      SPEC_ID = 'WATER VAPOR'
      HEAT_OF_REACTION= 2500. /

&PART ID='foliage', DRAG_LAW='CYLINDER', SAMPLING_FACTOR=10, SURF_ID='foliage', PROP_ID='needle image'
      QUANTITIES='PARTICLE TEMPERATURE','PARTICLE MASS','PARTICLE DIAMETER', STATIC=.TRUE., COLOR='FOREST GREEN' /
&INIT PART_ID='foliage', XYZ=0.0,0.0,0.15, RADIUS=0.85, HEIGHT=1.9, SHAPE='CONE', N_PARTICLES=100000, MASS_PER_VOLUME=2.0  /
&PROP ID='needle image', SMOKEVIEW_ID='TUBE', SMOKEVIEW_PARAMETERS='L=0.05','D=0.001','RANDXYZ=1' /

&PART ID='small roundwood', DRAG_LAW='CYLINDER', SAMPLING_FACTOR=10, SURF_ID='small roundwood', PROP_ID='small roundwood image'
      QUANTITIES='PARTICLE TEMPERATURE','PARTICLE MASS','PARTICLE DIAMETER', STATIC=.TRUE., COLOR='BROWN' /
&INIT PART_ID='small roundwood', XYZ=0.0,0.0,0.15, RADIUS=0.85, HEIGHT=1.9, SHAPE='CONE', N_PARTICLES=10000, MASS_PER_VOLUME=0.4  /
&PROP ID='small roundwood image', SMOKEVIEW_ID='TUBE', SMOKEVIEW_PARAMETERS='L=0.10','D=0.002','RANDXYZ=1' /

&PART ID='medium roundwood', DRAG_LAW='CYLINDER', SAMPLING_FACTOR=10, SURF_ID='medium roundwood', PROP_ID='medium roundwood image'
      QUANTITIES='PARTICLE TEMPERATURE','PARTICLE MASS','PARTICLE DIAMETER', STATIC=.TRUE., COLOR='BROWN' /
&INIT PART_ID='medium roundwood', XYZ=0.0,0.0,0.15, RADIUS=0.85, HEIGHT=1.9, SHAPE='CONE', N_PARTICLES=10000, MASS_PER_VOLUME=0.3  /
&PROP ID='medium roundwood image', SMOKEVIEW_ID='TUBE', SMOKEVIEW_PARAMETERS='L=0.10','D=0.004','RANDXYZ=1' /

&PART ID='large roundwood', DRAG_LAW='CYLINDER', SAMPLING_FACTOR=10, SURF_ID='large roundwood', PROP_ID='large roundwood image'
      QUANTITIES='PARTICLE TEMPERATURE','PARTICLE MASS','PARTICLE DIAMETER', STATIC=.TRUE., COLOR='BROWN' /
&INIT PART_ID='large roundwood', XYZ=0.0,0.0,0.15, RADIUS=0.85, HEIGHT=1.9, SHAPE='CONE', N_PARTICLES=10000, MASS_PER_VOLUME=0.5  /
&PROP ID='large roundwood image', SMOKEVIEW_ID='TUBE', SMOKEVIEW_PARAMETERS='L=0.10','D=0.006','RANDXYZ=1' /

&PART ID='ignitor', SAMPLING_FACTOR=1, SURF_ID='burner', STATIC=.TRUE. /
&SURF ID='burner', TMP_FRONT=1300., TAU_T=0.05, RADIUS=0.01, GEOMETRY='SPHERICAL' /
&INIT PART_ID='ignitor', XYZ=0.0,0.0,0.21, RADIUS=0.40, SHAPE='RING', N_PARTICLES=400  /

&DEVC XB=-1.5,0.0,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='foliage', ID='foliage1', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=-1.5,0.0,0.0,1.5,0.0,8.0 , QUANTITY='MPUV', PART_ID='foliage', ID='foliage2', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='foliage', ID='foliage3', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,0.0,1.5,0.0,8.0, QUANTITY='MPUV', PART_ID='foliage', ID='foliage4', STATISTICS='VOLUME INTEGRAL'  /

&DEVC XB=-1.5,0.0,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='small roundwood', ID='small roundwood1', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=-1.5,0.0,0.0,1.5,0.0,8.0 , QUANTITY='MPUV', PART_ID='small roundwood', ID='small roundwood2', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='small roundwood', ID='small roundwood3', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,0.0,1.5,0.0,8.0, QUANTITY='MPUV', PART_ID='small roundwood', ID='small roundwood4', STATISTICS='VOLUME INTEGRAL'  /

&DEVC XB=-1.5,0.0,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='medium roundwood', ID='medium roundwood1', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=-1.5,0.0,0.0,1.5,0.0,8.0 , QUANTITY='MPUV', PART_ID='medium roundwood', ID='medium roundwood2', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='medium roundwood', ID='medium roundwood3', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,0.0,1.5,0.0,8.0, QUANTITY='MPUV', PART_ID='medium roundwood', ID='medium roundwood4', STATISTICS='VOLUME INTEGRAL'  /

&DEVC XB=-1.5,0.0,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='large roundwood', ID='large roundwood1', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=-1.5,0.0,0.0,1.5,0.0,8.0 , QUANTITY='MPUV', PART_ID='large roundwood', ID='large roundwood2', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,-1.5,0.0,0.0,8.0, QUANTITY='MPUV', PART_ID='large roundwood', ID='large roundwood3', STATISTICS='VOLUME INTEGRAL'  /
&DEVC XB=0.0,1.5,0.0,1.5,0.0,8.0, QUANTITY='MPUV', PART_ID='large roundwood', ID='large roundwood4', STATISTICS='VOLUME INTEGRAL'  /

&SLCF PBY=0., QUANTITY='RADIATION LOSS', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='INTEGRATED INTENSITY', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='TEMPERATURE', VECTOR=.TRUE. /

&BNDF QUANTITY='WALL TEMPERATURE' /
&BNDF QUANTITY='GAUGE HEAT FLUX' /

&TAIL /

**Comment by mcgratta** [comment] 2016-05-16 12:21
I'll take a look at it.

**Comment by mcgratta** [comment] 2016-05-16 15:37
The problem is that the particles are not being properly distributed over the 4 meshes. I see in the 4 mesh case 130400 particles in each mesh. There should be a total of 130400 for the entire domain. I'll fix.

**Comment by mcgratta** [comment] 2016-05-16 20:43
I fixed the obvious bug related to how FDS distributes particles within a cone. In short, we need to know how much of the cone volume is in each mesh and parcel out the particles accordingly. I pushed new code (#3863). Compile the new code and run your case again. I still see a difference in HRR. I also split the mesh into 4 meshes stacked one on top of the other and the agreement between single and 4 mesh case is very close.

**Comment by khalidmoinuddin** [comment] 2016-05-18 21:58
Good to know the progress. Where can I get the new code?

**Comment by mcgratta** [comment] 2016-05-19 12:23
Right here at GitHub. It was merged in #3863. Update you local repository and recompile.

**Comment by khalidmoinuddin** [comment] 2016-05-24 04:05
Hi Kevin,

We compiled the code. The case file gives numerical instability after 28 time step. We noticed this with previous versions of the code as well (6.2.0, 6.4.0). This is both single and multimesh cases.

Regards

Khalid

**Comment by mcgratta** [comment] 2016-05-24 12:27
Copy the version number, Git hash, date, etc, of the version you compiled.

**Comment by khalidmoinuddin** [comment] 2016-05-25 04:44
Hi Kevin,

The requested information is given below:

Current Date     : May 25, 2016  14:18:17
 Version          : FDS 6.4.0
 Revision         : Git-r10-517-gc7aa429
 Revision Date    : Tue May 24 16:37:10 2016 -0400
 Compilation Date : May 25, 2016  14:13:11

In the attachment I've copy-pasted all the output from running the cases.

Kind regards

Khalid

**Comment by mcgratta** [comment] 2016-05-25 13:46
I assume you are running the NIST_Douglas_Firs case files in the repository. I am too, and I am using the same FDS version as you. I am not (yet) seeing numerical instabilities. Which Fortran compiler do you use? Do you use the makefile that we provide? What is the version of your compiler?

**Comment by khalidmoinuddin** [comment] 2016-05-26 00:43
Hi Kevin

Following your comments, we tried compiling the debugging version: gnu_linux_64_db, following the standard process with the fds makefile without modifications. The only real difference we can see between these two versions is the level of compiler optimisation -O0 for the db version and -O2 for the standard version.

The simulations is running past the point which it previously failed. It reached 100 steps for 2.11s of simulated time before we stopped it. We'll let it run longer and if there is an issue we will let you know.

The information as requested is below.

> I assume you are running the NIST_Douglas_Firs case files in the repository.
> Yes. tree_2_m_14_pc.fds and tree_5_m_26_pc.fds
> 
> Which Fortran compiler do you use?
> gfortran
> 
> Do you use the makefile that we provide?
> Yes, we used the script in the FDS_Compilation/gnu_linux_64 directory (or the corresponding script in the mpi directory script). This is simply a nice wrapper script to the standard makefile.
> 
> What is the version of your compiler?

GNU Fortran (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

The only packages that we can see linked in the makefile are openmp and MPI.

This is the openmp library

lrwxrwxrwx 1 root root    16 Jan 27 17:35 /usr/lib/x86_64-linux-gnu/libgomp.so.1 -> libgomp.so.1.0.0

MPI version: 3.0

MPI library version: Open MPI v1.10.2,

No other external libraries appear to be linked, which surprises us.

Kind regards

Khalid

**Comment by mcgratta** [comment] 2016-05-26 12:53
If the debug version runs and the optimized version does not, that generally indicates a problem with the compiler. I suggest you upgrade to the latest version if you're not there already, or consider purchasing the Intel Fortran compiler. We have found that it is more reliable and faster than gfortran.

**Comment by khalidmoinuddin** [comment] 2016-05-26 21:49
Thanks, Kevin. We will purchase the Intel Fortran compiler.

Regards

Khalid

**Closed as completed** 2016-06-13 14:06 UTC
