### ISSUE TITLE
Runaway reaction in a simple methane fire

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#2967] opened 2015-10-17 16:03 UTC
This seems like a case where the reaction runs away. I can't pin it down.

```
&HEAD CHID='Simple' / 
&MESH IJK=10,10,16, XB=0.4,1.4,0.4,1.4,0.6,2.2 / 
&TIME T_END=10, DT=0.01 / 

&SPEC ID='AGENT' /
&REAC FUEL='METHANE' /

&SURF ID='BURN', HRRPUA=10, COLOR='RASPBERRY' /
&SURF ID='INJECT',MASS_FLUX=0.001, SPEC_ID='AGENT', COLOR='BLUE' /

&OBST XB=0.6,1.2,0.6,1.2,2.0,2.1, SURF_IDS='INERT','INERT','INJECT' /
&VENT XB=0.6,1.2,0.6,1.2,0.6,0.6, SURF_ID='BURN' /

&SLCF PBY=0.9, QUANTITY='MASS FRACTION', SPEC_ID='AGENT', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.9, QUANTITY='MASS FRACTION', SPEC_ID='METHANE',  CELL_CENTERED=.TRUE. /
&SLCF PBY=0.9, QUANTITY='PRESSURE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.9, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.9, QUANTITY='HRRPUV', CELL_CENTERED=.TRUE. /

&TAIL/
```

**Comment by rmcdermo** [comment] 2015-10-17 16:28
Why did we add "Step Size" to std_err output?  I don't think this is helpful.

**Comment by rmcdermo** [comment] 2015-10-17 16:32
Looks like the problem is related to the viscosity in the near-wall cell, which we obtain from Smagorinsky.  If I lower the C_SMAG the case runs.  I'll think about how to handle this.

**Comment by mcgratta** [comment] 2015-10-17 20:25
I added Step Size because there is now a shorter set of diagnostics for big jobs. So I just added DT to the standard out because I use the same line for .out. You can remove it if you want, but leave it in the .out file.

**Comment by rmcdermo** [comment] 2015-10-19 18:27
I think we have a bug in combustion.  If you set the 'Agent' to be some
inert species we have in our list, like 'NITROGEN' or 'ARGON', then the
case works.  Something weird about the agent also being 'AIR' is causing a
problem.

**Comment by mcgratta** [comment] 2015-10-19 18:35
I assume that AIR is providing oxygen. When I run the case, I see little flashes of high HRRPUV at the interface of rising fuel and descending agent.

**Comment by drjfloyd** [comment] 2015-10-19 18:54
I think this is a numerical precision issue.  We determine  the heat release using the enthalpy of formation.  In input processing we set that to -1E23 to be able to detect when a user makes an input. If I change 
&SPEC ID='AGENT'/
to
&SPEC ID='AGENT',ENTHALPY_OF_FORMATION=0/

it runs fine.  

I think the issue is that we aren't resetting the heat of formation to something rational later in input processing.  In combustion when we do  SUM (Y \* H_F) the large number is washing out the actual reaction.

**Comment by rmcdermo** [comment] 2015-10-19 18:56
I noticed that too.  I was just running the original case to see if that
was happening there as well.  What should happen if the user specifies a
FORMULA?  Do you back out the H_F?

**Comment by rmcdermo** [comment] 2015-10-19 18:58
Yeah, this fixes the original case, too.  Jason, want to take this from
here?

**Comment by drjfloyd** [comment] 2015-10-19 19:00
H_F is the enthalpy of the substance at a reference state, it cannot be determined from the formula.  We just have a use case missing in our input processing of species to compute a meaningful H_F in this case. What we should be doing in this case where c_p is being computed using gamma is also compute H_F as RCON_GAMMA/(GAMMA-1._EB)_enthalpy reference temperature.

**Comment by drjfloyd** [comment] 2015-10-19 19:04
I think we just need to add that line to the CASE(DEFAULT) in GAS_PROPS.

**Comment by drjfloyd** [comment] 2015-10-20 15:49
This was more of a rabbit hole than I anticipated.  We aren't fully consistent with how we treat H_F.   H_F is the enthalpy of a substance at some reference formation temperature. So if we have defined SPECIFIC_HEAT and REFERENCE_ENTHALPY or RAMP_CP, we have implicitly defined H_F.  If we make the assumption that when H_F is not defined explicitly that we use whatever H_F value results from the user's CP inputs, then we will never have undefined H_F values going into PROC_REAC. This means potentially non-sensical HoC is a user doesn't define HoC (as in that case we compute it from H_F of the products and reactants).  I think I am OK with that provided we explain this in the guide.

If we don't assumed a non-explicitly defined H_Fis defined from cp data, then we can have the problems in this issue. So I think we need to do that rather than put the onus on the user to have to make up an H_F value (generally one can find or assume reasonable cp values but not always H_F values).

Another issue though is if the user gives an HoC (or EPUMO2 for SIMPLE_CHEMISTRY) we adjust H_F of the fuel to get the right heat release in fire.f90. This means if the same fuel is used in more than one reaction, the last reaction will define H_F and earlier reactions might not have the correct HoC. Currently no warning or error is being written for this. Additionally we need to make sure we correct the CPBAR values when we change H_F (changing H_F means we change the reference enthalpy).

**Comment by mcgratta** [comment] 2015-10-20 16:14
I am nominating myself for the Boris Prize, 2015, for the input file that started this issue.

**Comment by rmcdermo** [comment] 2015-10-20 16:28
I am not sure I like linking CP and H_F.  I often just think in terms of
CP=1 to a rough idea of what is happening.  I don't like that HoC would
become non-sensical.  I would rather just have H_F set to 0 unless the user
specifies it.

**Comment by drjfloyd** [comment] 2015-10-20 16:46
HoC only becomes non-sensical if it is undefined on the REAC, otherwise we adjust the FUEL H_F to get the right HoC.  I would be concerned that if we had H_F not consistent with cp(T) that we wouldn't get the correct equilibrium state.  Having disconnects like that caused problems in the past with droplet evaporation.

**Comment by rmcdermo** [comment] 2015-10-20 17:03
I am confused about how we can hope to have full consistency.  If a user
specifies HoC on REAC, surely that trumps everything, and we will not go in
and adjust the CP curves to make H_F consistent with CP, right?

In my view H_F only matters for heat release rate.  If a user gives a new
species, then I think they should be on the hook for either HoC or H_F.

**Comment by drjfloyd** [comment] 2015-10-20 17:17
I am not suggesting we change the values of c_p only c_p_bar. We already adjust H_F to get the right HoC. But we do not currently adjust the reference enthalpy to be consistent with H_F. I would argue we need to adjust the reference enthalpy (which affects c_p_bar) to guarantee the correct end state (this was part of why we didn't get the right equilibrium state when comparing to cantera a while back).  When we ignored inconsistencies in properties for evaporation and it wound up biting us.

**Comment by rmcdermo** [comment] 2015-10-20 17:24
OK, you've convinced me.

**Comment by mcgratta** [comment] 2015-10-21 20:31
```
Fires/HoC_Ideal.err:forrtl: error (63): output conversion error, unit 6, file /home/mcgratta/Git_Repositories/FDS-SMV/Verification/Fires/HoC_Ideal.out
Fires/HoC_Ideal.err-Image              PC                Routine            Line        Source
Fires/HoC_Ideal.err-fds_mpi_intel_lin  000000000265E7F3  Unknown               Unknown  Unknown
Fires/HoC_Ideal.err-fds_mpi_intel_lin  00000000026B52D0  Unknown               Unknown  Unknown
Fires/HoC_Ideal.err-fds_mpi_intel_lin  00000000016806CB  dump_mp_initializ        2554  dump.f90
Fires/HoC_Ideal.err-fds_mpi_intel_lin  00000000015DC54A  dump_mp_initializ         562  dump.f90
Fires/HoC_Ideal.err-fds_mpi_intel_lin  000000000220AD85  MAIN__                    345  main.f90
Fires/HoC_Ideal.err-fds_mpi_intel_lin  000000000040931E  Unknown               Unknown  Unknown
Fires/HoC_Ideal.err-libc.so.6          0000003224A1D994  Unknown               Unknown  Unknown
Fires/HoC_Ideal.err-fds_mpi_intel_lin  0000000000409239  Unknown               Unknown  Unknown
Fires/HoC_Ideal.err- Time Step:      1, Simulation Time:      0.16 s
Fires/HoC_Ideal.err-MPI process    0 has completed
Fires/HoC_Ideal.err-
Fires/HoC_Ideal.err-STOP: FDS stopped by user (CHID: HoC_Ideal)
```

This is the problem line:

```
WRITE(LU_OUTPUT,'(3X,A,1X,F12.4)') RN%FUEL,RN%HEAT_OF_COMBUSTION/1000._EB
```

I am currently testing my forked repo, so my line number may not be the same as yours. But in any case, HoC is a huge negative number and there is an error when running in debug mode because of the formatting.

**Comment by drjfloyd** [comment] 2015-10-21 20:51
Should be fixed now. Hopefully we get a firebot tomorrow and can clean up anything else I broke.

**Comment by mcgratta** [comment] 2015-10-21 21:01
I am firebotting now. This was the only error in debug stage.

**Comment by drjfloyd** [comment] 2016-01-05 20:41
still seems to be working in the current source. Closing the issue.

**Closed as completed by drjfloyd** 2016-01-05 20:41 UTC
